.travis.yml
I think this will fix the Python 3.5 issue – found the fix here: https://github.com/pytest-dev/pytest/issues/744
=> TST: fix py35 on Travis

altair/api.py, altair/html.py, altair/tests/test_api.py, altair/utils.py
This PR is largely cleanup and docstring-ing, but there are also some test fixes and a bugfix in the `utils` module. All tests pass now.
=> Pep cleanup

README.md, setup.py
Added the dependencies for the install_requires portion of setup.py
=> Added dependencies to setup

.gitignore, altair/api.py, altair/tests/test_api.py
TODO list to complete issue #42
=> Add TODOs for Vegalite spec completion

altair/api.py, altair/tests/test_api.py
=> Add Scale objects for Vegalite spec completion

altair/api.py, altair/tests/test_api.py
Will help towards completing #42 and #43
=> Complete Band object for Vegalite spec completion

altair/api.py, altair/tests/test_api.py
Will help towards completing #43
=> Add unit tests for X, Y, Size, and Color objects for Vegalite spec completion

altair/api.py, altair/tests/test_api.py
Will help towards completing #42 and #43
=> Complete Axis object for Vegalite spec completion

altair/api.py, altair/tests/test_api.py
Will help towards completing #42 and #43
=> Complete Text object for Vegalite spec completion

altair/api.py, altair/tests/test_api.py
Will help towards completing #42 and #43
=> Complete Detail object for Vegalite spec completion

.travis.yml
- remove lightning
- install pytest via conda rather than pip
=> MAINT: adjust travis settings

altair/api.py, altair/schema/baseobject.py, altair/tests/test_api.py
=> ENH: make method updates augment rather than overwrite

altair/api.py, altair/examples/tests/test_examples.py, altair/schema/_wrappers/channel_collections.py, altair/schema/_wrappers/channel_wrappers.py, altair/schema/baseobject.py, altair/tests/test_api.py, altair/utils/core.py, altair/utils/visitors.py, tools/templates/channel_collections.tpl, tools/templates/channel_wrappers.tpl
Addresses the statefulness issue brought up in https://github.com/ellisonbg/altair/issues/90#issuecomment-226656429
=> [MRG] delay type inference & allow it to handle parent data

README.md
At least for me, they didn't run from just the pip install...
=> Clarify that tests need to be run in source directory.

altair/schema/baseobject.py
=> Expose some public methods to completion

altair/notebooks/01-Index.ipynb
It just corrects the broken link
=> Correct link to Iris Pairgrid notebook

README.md
[pygg](https://github.com/sirrice/pygg) provides nearly identical ggplot2 syntax in python and translates into an R program that executes ggplot2 statements.  Thus, it can take advantage of all of ggplot2's engineering and features.
=> add pygg: python wrapper around ggplot2

.travis.yml
Attempt to build docs on Travis
=> MAINT: build docs on travis

doc/documentation/config.rst
Add documentation on how to set axis limits
=> DOC: add info on axis limits

altair/utils/node.py
for #224 
combining output and error to pass into CalledProcessError output
=> making calledprocesserror python2 compatible

altair/utils/visitors.py
prompted by some stray debugging statements and extra indentation. Then I did a bit more.
=> MAINT: clean up visitor util code

.travis.yml
=> MAINT: add pip install to CI

doc/faq.rst
=> DOC: add FAQ on large notebooks

altair/api.py, altair/tests/test_api.py
=> MAINT: clean up dir() specialization of top-level objects

altair/api.py, altair/schema/baseobject.py, altair/tests/test_api.py
=> BUG: respect empty strings as trait values

doc/conf.py, doc/sphinxext/altair_ext/altair_autodoc.py, doc/sphinxext/altair_ext/altairplot.py
This adds an option to the altairplot extension to specify vega javascript paths. Fixes #306
=> Fix Javascript URLs

altair/notebooks/08-GroupedRegressionCharts.ipynb
Issue solved by replacing ValueError with TypeError
=> Issue #288

altair/utils/node.py
Fix the exception raise so that error output can actually be caught and examined.
=> fix error message generation

altair/__init__.py, requirements.txt, setup.py
=> Set version to 1.2.1 and pin vega to 0.4.4

doc/_static/altair-plot.css
Improved visual design of Altair visualization rendered in our docs:
=> Minor design changes to viz in docs

altair/v1/api.py, doc/_static/theme_overrides.css, doc/conf.py
This implements the fix for #415 cell text wrap issues, adapted from:  http://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html
=> Fix table cell text wrap

altair/utils/schemapi.py, altair/vegalite/v2/api.py, altair/vegalite/v2/schema/channels.py, altair/vegalite/v2/schema/core.py, altair/vegalite/v2/tests/test_api.py, tools/generate_schema_wrapper.py, tools/schemapi/__init__.py, tools/schemapi/codegen.py, tools/schemapi/jsonschema-draft04.json, tools/schemapi/utils.py
Working on generating more useful docstrings in the auto-generated code.
=> WIP: Schemapi docstrings

altair/vegalite/data.py, altair/vegalite/tests/test_data.py
Pretty straightforward stuff. Right now, the data transformers are within the vegalite package. Most of these things will also be relevant to the vega side of things as well, but I will do that work in a separate PR once work on the vega API begins.
=> This fixes some bugs and adds tests for the data transformers.

altair/vegalite/v2/examples/mutli_series_line.py
I added a multi series line example using the `stocks` dataset.
=> Added a multi series line example

altair/vegalite/v2/examples/stacked_bar_chart.py
I tried recreating the canonical "weather type" bar chart.
=> Added a stacked bar chart example

altair/vegalite/v2/examples/anscombe_plot.py
An example of a Trellis scatter plot
=> Anscombe’s Quartet Example

altair/vegalite/v2/examples/layered_chart_bar_mark.py
This is useful to quickly see how performance is against some preset targets.
=> adding layered chart bar and mark

altair/vegalite/v2/examples/interactive_scatter_plot.py
trying this again with clean copies.
=> adding basic scatter plot from vega-lite docs

altair/vegalite/tests/test_common.py, altair/vegalite/v1/api.py, altair/vegalite/v2/api.py
This will make them automatically render correctly when exported to the vega editor.
=> MAINT: add  property to top-level objects on to_dict().

altair/vegalite/v2/examples/horizontal_stacked_bar_chart.py
A horizontal stacked bar chart using the barley dataset.
=> Horizontal stacked bar chart example

altair/vegalite/v2/examples/line_percent.py
trying this again with clean copies.
=> adding simple line example with percent axis

altair/vegalite/v2/examples/table_binned_heatmap.py
only issue is I tried many permutations to get the color scheme defined without using the config dictionary method.  If that is implemented I would love to change it - I just could not figure it out if it is there.
=> adding vega-lite example of table binned heatmap

altair/vegalite/v2/examples/trellis_stacked_bar_chart.py
Added the Trellis Stacked Bar Chart example. Let me know if the dimensions are too big.
=> Trellis Stacked Bar Chart Example

altair/vegalite/v2/examples/stacked_area_chart.py
An example of a stacked area chart. I reshaped the original dataset using `pd.melt` to get it into a tidy format. I can make a simpler example with a different dataset but I thought it could be useful to see.
=> Stacked Area Chart Example

altair/vegalite/v2/examples/steamgraph.py, altair/vegalite/v2/examples/streamgraph.py
Everything is working except turning off the y-axis.
In the vega-lite json it says:
"axis": null
I have tried:
axis = False
and
axis = 'null
neither have worked.
=> added the streamgraph example from vega-lite

altair/vegalite/v2/examples/diverging_stacked_bar_chart.py
The parameters inside the axis don't seem to be doing anything when I change them, but I kept them in as they were in the vega-lite example and they are not throwing errors in altair
y = alt.Y('question:N', axis = alt.Axis(title = 'Question',
offset = 5,
ticks = False,
minExtent = 60,
domain = False))
=> added vega-lite example of diverging stacked bar chart

altair/vegalite/v2/examples/ranged_dot_plot.py
One issue,
it looks like I can't pass the transform on the layered chart (well, I can pass it, but it is not reducing the dataset as requested).
I have to do the filters individually for line and point.
Unless I have missed something.
So right now I have the chart.transform commented out with both the line and point transforms in there.
=> added ranged dot plot example from vega-lite

altair/vegalite/v2/examples/us_state_capitals.py
See also pull request [#5 to vega_datasets](https://github.com/jakevdp/vega_datasets/pull/5) to add the state capitals. 
Please let me know if anything should be adjusted.
=> Add US state capitals from vega-lite.

altair/utils/core.py, altair/utils/tests/test_core.py, altair/vegalite/tests/test_common.py, altair/vegalite/v2/api.py
=> Change default width/height to config.view.width/height

altair/vegalite/v2/examples/gantt_chart.py
This one is complete - but seems to suffer from the same issue as:
https://github.com/altair-viz/altair/pull/481
Where I can add
scale = alt.Scale(rangeStep = 20)
But it does nothing to the chart.
In this example it appears comically large, and can't be shortened.
=> added gantt_chart from vega-lite

altair/utils/schemapi.py, altair/utils/tests/test_schemapi.py, altair/vega/v2/schema/core.py, altair/vega/v3/schema/core.py, altair/vegalite/v1/schema/channels.py, altair/vegalite/v1/schema/core.py, altair/vegalite/v2/api.py, altair/vegalite/v2/examples/grouped_bar_chart.py, altair/vegalite/v2/schema/channels.py, altair/vegalite/v2/schema/core.py, altair/vegalite/v2/schema/mixins.py, tools/generate_schema_wrapper.py
These are auto-generated within a mixin class.
=> ENH: add top-level configure_* methods

altair/vegalite/v2/examples/beckers_barley_trellis_plot.py
All works - but for some reason the rangeStep does not seem to be having the affect of reducing the spaces between the y axis items.
It was throwing errors until I did the capital 'S', but now that there aren't any errors - it also does not seem to be changing the chart, even when using extreme values.
=> adding trellis plot from vega-lite

altair/vegalite/v2/examples/multifeature_scatter_plot.py
Trying to recreated some plots from your book.
=> Multifeature Scatter Plot Example

altair/vegalite/v2/examples/bar_chart_with_highlight.py
There was an extra mention of bar2 - it is now removed
=> removed the second bar2 from chart string

altair/vegalite/v2/examples/layered_histogram.py
I know technically a layered bar chart is the same thing as a layered histogram but I thought this example was useful.
=> Layered Histogram Example

altair/vegalite/v2/examples/aggregate_bar_chart.py, altair/vegalite/v2/examples/binned_scatterplot.py, altair/vegalite/v2/examples/boxplot_max_min.py, altair/vegalite/v2/examples/diverging_stacked_bar_chart.py, altair/vegalite/v2/examples/gantt_chart.py, altair/vegalite/v2/examples/gapminder_bubble_plot.py, altair/vegalite/v2/examples/grouped_bar_chart.py, altair/vegalite/v2/examples/histogram.py, altair/vegalite/v2/examples/histogram_with_a_global_mean_overlay.py, altair/vegalite/v2/examples/layered_bar_chart.py, altair/vegalite/v2/examples/line_percent.py, altair/vegalite/v2/examples/natural_disasters.py, altair/vegalite/v2/examples/normalized_stacked_bar_chart.py, altair/vegalite/v2/examples/ranged_dot_plot.py, altair/vegalite/v2/examples/streamgraph.py, altair/vegalite/v2/examples/table_binned_heatmap.py, altair/vegalite/v2/examples/table_bubble_plot_github.py, altair/vegalite/v2/examples/trellis_scatter_plot.py
I looked over the examples and made changes where necessary. Most changes are adding type information.
=> Nonlocal URL Fix

altair/vegalite/v2/examples/interactive_brush.py, altair/vegalite/v2/examples/interactive_cross_highlight.py, altair/vegalite/v2/examples/interactive_layered_crossfilter.py, altair/vegalite/v2/examples/selection_layer_bar_month.py
This adds a few additional examples that make use of interactive features.
=> Interactive Examples

altair/utils/schemapi.py, altair/utils/tests/test_schemapi.py, altair/vega/v2/schema/core.py, altair/vega/v3/schema/core.py, altair/vegalite/v1/schema/channels.py, altair/vegalite/v1/schema/core.py, altair/vegalite/v2/api.py, altair/vegalite/v2/examples/trellis_histogram.py, altair/vegalite/v2/schema/channels.py, altair/vegalite/v2/schema/core.py, altair/vegalite/v2/schema/mixins.py, altair/vegalite/v2/tests/test_api.py, tools/generate_schema_wrapper.py
This fixes some subtle bugs in ``alt.condition`` that were constructing invalid condition specs.
I prefer not to reveal how long this took me to fix :smile:
=> Fix condition

altair/vegalite/v2/examples/line_percent.py
I changed `transform` to a `transform_filter` for a cleaner example
=> Filter Example Edit

altair/vegalite/v2/examples/ranged_dot_plot.py
In reviewing this the line was on top of the dots and looked strange.
Sorry for missing this before.
=> moved line to be behind the circles

altair/vegalite/v2/examples/multiline_tooltip.py
I think examples which use random numbers should be seeded for repeatability
=> Added Random Number Seed

altair/vegalite/v2/examples/horizon_graph.py
I made the Horizon Graph example from the vega-lite website. I had never heard of these plots before.
=> Horizon Graph Example

altair/vegalite/v2/examples/stem_and_leaf.py
My attempt at a stem and leaf plot.
=> Add stem leaf plot example

README.md, altair/utils/plugin_registry.py, doc/_static/custom.css, doc/case_studies/exploring-weather.rst, doc/conf.py, doc/getting_started/installation.rst, doc/getting_started/overview.rst, doc/getting_started/starting.rst, doc/index.rst, doc/tutorials/index.rst, doc/user_guide/API.rst, doc/user_guide/display.rst, doc/user_guide/importing.rst
This PR contains a bunch of work on the documentation in preparation for the 2.0 release:
=> Reorganizing the documentation for the 2.0 release

altair/vegalite/v2/api.py, altair/vegalite/v2/examples/us_population_over_time.py
Add a Python interface to bindings, plus an example:
=> ENH: add binding interface

altair/vegalite/v2/api.py, altair/vegalite/v2/examples/airports.py, altair/vegalite/v2/examples/choropleth.py, altair/vegalite/v2/examples/choropleth_repeat.py, altair/vegalite/v2/examples/london_tube.py, altair/vegalite/v2/examples/us_state_capitals.py
Adding a function to address some of the boilerplate needed to extract features from a topojson url source.
=> ENH: Add UrlTopoFeature to api

altair/vegalite/v2/api.py
=> Add as_ keyword to transform_lookup

altair/vegalite/v2/examples/cumulative_wiki_donations.py, altair/vegalite/v2/examples/error_bars_with_ci.py, altair/vegalite/v2/examples/gantt_chart.py, altair/vegalite/v2/examples/gapminder_bubble_plot.py, altair/vegalite/v2/examples/grouped_bar_chart.py, altair/vegalite/v2/examples/horizon_graph.py, altair/vegalite/v2/examples/layered_histogram.py, altair/vegalite/v2/examples/line_percent.py, altair/vegalite/v2/examples/line_with_ci.py, altair/vegalite/v2/examples/poly_fit.py, altair/vegalite/v2/examples/step_chart.py
Ahead of the final release, I figured I could contribute by reviewing the docs with my somewhat naive eyes.
Here's the only change I can propose so far. 
Merge if now if you want, or I can continue going through the docs later tonight (US/Pacific TZ).
=> DOC: the most minor of typos

README.md, doc/getting_started/installation.rst
updates to (almost verbatim) the docs instructions for installation
=> readme update

doc/user_guide/config.rst
=> DOC: Added examples of configuring the legend

altair/vegalite/v2/examples/bar.py, altair/vegalite/v2/examples/mutli_series_line.py, altair/vegalite/v2/examples/simple_scatter.py
Some of the basic charts are using a different import style than the other examples. It seems to me that consistency is important here, especially for basic charts that will be picked up by newbies.
=> DOC: Standardized import style in the basic charts examples

altair/vegalite/v2/examples/multiline_tooltip.py
=> fixed typo

altair/vegalite/v2/api.py, altair/vegalite/v2/tests/test_api.py
Small change to fix #626 
@ellisonbg, can you take a look?
=> ENH: allow DataFrame to be passed to LookupData (fixes #626)

altair/sphinxext/altairgallery.py, altair/utils/save.py, altair/vegalite/v1/api.py, altair/vegalite/v2/api.py, altair/vegalite/v2/tests/test_api.py, doc/getting_started/starting.rst, doc/user_guide/saving_charts.rst
=> Refactored 'savechart' as the more concise 'save'

README.md
=> Added the logo to the README 

altair/datasets.py
=> MAINT: add deprecation warning to load_datasets

altair/utils/core.py, altair/utils/tests/test_core.py, altair/vegalite/v1/schema/channels.py, altair/vegalite/v2/api.py, altair/vegalite/v2/examples/binned_scatterplot.py, altair/vegalite/v2/examples/histogram.py, altair/vegalite/v2/examples/histogram_with_a_global_mean_overlay.py, altair/vegalite/v2/examples/interactive_cross_highlight.py, altair/vegalite/v2/examples/interactive_layered_crossfilter.py, altair/vegalite/v2/examples/layered_heatmap_text.py, altair/vegalite/v2/examples/layered_histogram.py, altair/vegalite/v2/examples/seattle_weather_interactive.py, altair/vegalite/v2/examples/stacked_bar_chart.py, altair/vegalite/v2/examples/trellis_histogram.py, altair/vegalite/v2/schema/channels.py, doc/case_studies/exploring-weather.rst, doc/user_guide/compound_charts.rst, doc/user_guide/encoding.rst, doc/user_guide/selections.rst, tools/generate_schema_wrapper.py
=> Simplify ``count()`` aggregation

altair/utils/headless.py
=> BUG: fix tempfile issue when saving to png/eps on windows (#649)

altair/utils/headless.py
=> BUG: fix windows geteuid issue when saving to png/svg

altair/utils/plugin_registry.py, altair/vegalite/v1/display.py, altair/vegalite/v2/display.py, doc/getting_started/installation.rst, doc/index.rst, doc/user_guide/display.rst, doc/user_guide/troubleshooting.rst
@mroswell I'd appreciate your thoughts on this... hopefully it would have addressed some of the issues you faced yesterday
=> Troubleshooting docs

altair/utils/display.py, altair/vega/v2/display.py, altair/vega/v2/schema/core.py, altair/vega/v3/display.py, altair/vega/v3/schema/core.py, altair/vegalite/v1/display.py, altair/vegalite/v1/schema/core.py, altair/vegalite/v2/display.py, altair/vegalite/v2/examples/tests/test_examples.py, altair/vegalite/v2/schema/core.py, tools/generate_schema_wrapper.py
=> MAINT: explicitly decode to utf-8

altair/vegalite/v2/examples/connected_scatterplot.py, doc/user_guide/config.rst, doc/user_guide/encoding.rst
=> Drafted encoding documentation for the order channel

altair/vegalite/v1/schema/channels.py, altair/vegalite/v2/schema/channels.py, tools/generate_schema_wrapper.py
Fixed in the generator level for a more lasting effect.
=> Fixed a PEP8 violation of indenting style in autogenerated code

altair/vega/v2/schema/core.py, altair/vega/v3/schema/core.py, altair/vegalite/v1/schema/channels.py, altair/vegalite/v1/schema/core.py, altair/vegalite/v2/schema/channels.py, altair/vegalite/v2/schema/core.py, setup.cfg, tools/schemapi/utils.py
Also handled upstream to make the fix permanent.
=>  Clean up rstrip and blank line PEP* violations in autogen code

altair/expr/core.py, altair/expr/tests/test_expr.py, altair/vegalite/v2/api.py, altair/vegalite/v2/examples/choropleth.py, altair/vegalite/v2/examples/choropleth_repeat.py, altair/vegalite/v2/tests/test_api.py, doc/index.rst, doc/user_guide/API.rst, doc/user_guide/transform.rst
Adding more rigorous documentation of available transforms.
=> WIP: Transform docs

altair/expr/core.py, altair/expr/funcs.py, altair/expr/tests/test_expr.py, altair/sphinxext/altairgallery.py, altair/sphinxext/altairplot.py, altair/sphinxext/utils.py, altair/utils/save.py, altair/utils/tests/test_core.py, altair/utils/tests/test_execeval.py, altair/vega/data.py, altair/vegalite/data.py, altair/vegalite/v2/api.py, altair/vegalite/v2/examples/__init__.py, tools/schemapi/tests/test_schemapi.py
=> Removed unneeded imports for PEP8 compliance

altair/vegalite/v2/examples/horizon_graph.py
I think the scale needs to be set in the second area for this to work.
=> DOC: Correct scale on horizon example

altair/sphinxext/utils.py, altair/utils/_py3k_compat.py, altair/utils/schemapi.py, altair/utils/server.py
I also trimmed out some of the compatibility module that wasn't being used, or that is already provided by the `six` library.
=> PyFlakes fixes for Python 2/3 compatibility code

altair/vegalite/v2/examples/scatter_with_labels.py
For #715.
Looks like this:
```python
df = pd.DataFrame({
'x': [1, 3, 5, 7, 9], 
'y': [1, 3, 5, 7, 9], 
'label':['A', 'B', 'C', 'D', 'E'], 
})
bars = alt.Chart(df).mark_point().encode(
x='x:Q',
y='y:Q',
)
text = bars.mark_text(
align='left',
baseline='middle',
dx=7
).encode(
text='label'
)
bars + text
```
=> Added example of scatter plot with labels

altair/utils/data.py, altair/vega/data.py, altair/vega/v2/data.py, altair/vega/v3/data.py, altair/vegalite/api.py, altair/vegalite/data.py, altair/vegalite/schema.py
There is one separate issue yet that I will soon file a ticket on. But besides that, this is all that I see remaining in my pyflakes checks.
=> Fixed almost all of the remaining PyFlakes violations

.travis.yml, altair/utils/core.py, altair/utils/display.py, altair/utils/html.py, altair/utils/plugin_registry.py, altair/utils/save.py, altair/vegalite/v1/api.py, altair/vegalite/v1/display.py, altair/vegalite/v2/api.py, altair/vegalite/v2/display.py, altair/vegalite/v2/tests/test_api.py, doc/getting_started/installation.rst, requirements.txt
=> Python 2.7 compatibility

altair/vega/v2/display.py, altair/vega/v3/display.py, altair/vegalite/v1/display.py, altair/vegalite/v2/display.py, doc/index.rst, doc/user_guide/display.rst, doc/user_guide/renderers.rst
and link there from default display
=> DOC: add explicit section on renderers

doc/getting_started/installation.rst
=> Attempt to fix code block that's not rendering in the docs

altair/vegalite/v1/html.py
=> BUG: fix vega-embed version in vegalite.v1.html

altair/vegalite/v2/examples/binned_heatmap.py, altair/vegalite/v2/examples/simple_heatmap.py, altair/vegalite/v2/examples/simple_line_chart.py, altair/vegalite/v2/examples/strip_plot.py
=> DOC: add a few more simple chart examples

altair/vegalite/v1/api.py, altair/vegalite/v2/api.py
=> BUG: make chart.save() work regardless of active data transformer

altair/vegalite/v2/examples/simple_scatter_with_errorbars.py
This is a really simple example, but almost all of my data is of this type and it took me a bit to figure out `transform_calculate`, so I thought it might be useful for someone else to see. 
This is kind of a simpler version of the [errorbar example](https://altair-viz.github.io/gallery/error_bars_with_ci.html), where data points and uncertainties don't have to be calculated from a distribution, but are given as (x, y, yerr).
=> Added an example of data with error bars

doc/user_guide/saving_charts.rst
Thanks for the incredible documentation. This project is amazing!
=> Typo correction

doc/user_guide/customization.rst
=> DOC: fix outdated documentation

doc/user_guide/compound_charts.rst
Previously I committed it to the wrong place.
=> added remark based on mailing list discussion related to layered charts

doc/user_guide/compound_charts.rst
=> DOC: add section on layer ordering

altair/vegalite/v2/examples/candlestick_chart.py, altair/vegalite/v2/examples/cumulative_wiki_donations.py, altair/vegalite/v2/examples/layered_plot_with_dual_axis.py, altair/vegalite/v2/examples/mean_overlay_over_precipitiation_chart.py, altair/vegalite/v2/examples/seattle_weather_interactive.py, altair/vegalite/v2/examples/selection_layer_bar_month.py, altair/vegalite/v2/examples/stacked_bar_chart.py, altair/vegalite/v2/examples/streamgraph.py, altair/vegalite/v2/examples/table_bubble_plot_github.py, doc/case_studies/exploring-weather.rst, doc/user_guide/compound_charts.rst, doc/user_guide/transform.rst
=> DOC: Timeunit examples

doc/user_guide/configuration.rst
=> DOC: add documentation of themes

altair/sphinxext/altairgallery.py, altair/vegalite/v2/examples/airports.py, altair/vegalite/v2/examples/anscombe_plot.py, altair/vegalite/v2/examples/beckers_barley_trellis_plot.py, altair/vegalite/v2/examples/binned_heatmap.py, altair/vegalite/v2/examples/cumulative_wiki_donations.py, altair/vegalite/v2/examples/falkensee.py, altair/vegalite/v2/examples/gapminder_bubble_plot.py, altair/vegalite/v2/examples/london_tube.py, altair/vegalite/v2/examples/natural_disasters.py, altair/vegalite/v2/examples/one_dot_per_zipcode.py, altair/vegalite/v2/examples/seattle_weather_interactive.py, altair/vegalite/v2/examples/us_population_over_time.py, altair/vegalite/v2/examples/us_state_capitals.py
=> Reorganized complex examples into a new case studies section

altair/utils/plugin_registry.py, altair/utils/tests/test_plugin_registry.py, altair/vegalite/v2/api.py, altair/vegalite/v2/tests/test_display.py
=> ENH: allow renderer options to be set in chart.display()

altair/utils/core.py, altair/utils/tests/test_utils.py
=> Add more informative error for timedelta data

altair/utils/headless.py
=> MAINT: avoid selenium import when altair is imported

doc/case_studies/exploring-weather.rst
- changing 'month(date:T)' to 'month(date):T'
- deleting mention of special field *
=> docs: fix chart not displaying and delete mention of field * in Seattle case study

altair/vegalite/v2/examples/top_k_letters.py
Window transform / rank example
=> DOC: add top-k example

altair/vegalite/v2/examples/us_population_pyramid_over_time.py
Adds https://vega.github.io/vega/examples/population-pyramid/ example.
```python
'''
US Population Pyramid Over Time
===============================
A population pyramid shows the distribution of age groups within a population.
It uses a slider widget that is bound to the year to visualize the age
distribution over time.
'''
from altair.expr import datum, if_
pop = data.population.url
slider = alt.binding_range(min=1850, max=2000, step=10)
select_year = alt.selection_single(name='year', fields=['year'], bind=slider)
base = alt.Chart(pop).add_selection(
select_year
).transform_filter(
select_year
).transform_calculate(
gender=if_(datum.sex == 1, 'Male', 'Female')
)
title = alt.Axis(title='population')
color_scale = …
```
=> ADD: Population pyramid example

altair/vegalite/v2/examples/isotype.py
Isotype Visualization example. Credits to @chanwutk vega-lite reference.
```python
df =  pd.DataFrame([
{'country': 'Great Britain', 'animal': 'cattle', 'col': 3},
{'country': 'Great Britain', 'animal': 'cattle', 'col': 2},
{'country': 'Great Britain', 'animal': 'cattle', 'col': 1},
{'country': 'Great Britain', 'animal': 'pigs', 'col': 2},
{'country': 'Great Britain', 'animal': 'pigs', 'col': 1},
{'country': 'Great Britain', 'animal': 'sheep', 'col': 10},
{'country': 'Great Britain', 'animal': 'sheep', 'col': 9},
{'country': 'Great Britain', 'animal': 'sheep', 'col': 8},
{'country': 'Great Britain', 'animal': 'sheep', 'col': 7},
{'country': 'Great Britain', 'animal': 'sheep', 'col': 6},
{'country': 'Great Britain', 'animal': 'sheep', 'col': 5},
{'country': 'Great Britain', 'animal': …
```
=> ADD: Isotype visualization example

altair/vegalite/v2/examples/stem_and_leaf.py
Larges two changes to stem and leaf plot example
- Compact random data construction, stem and leaf using string methods
- Use pandas cumcount instead of apply
=> REF: stem and leaf example with better pandas

altair/vegalite/v2/examples/normalized_stacked_bar_chart.py, altair/vegalite/v2/examples/stacked_bar_chart.py
I've standardized three of the stacked bar chart examples so they use the same the dataset and similar, stripped down configurations. I believe this will make it easier for beginners to grok.
=> DOC: Standardized stacked bar examples

altair/utils/data.py, altair/vegalite/v2/api.py, altair/vegalite/v2/tests/test_api.py
=> Enable dataset consolidation by default

doc/user_guide/API.rst, doc/user_guide/transform.rst
=> DOC: document inherited members in API.rst

CHANGES.md, altair/vegalite/v2/api.py, altair/vegalite/v2/tests/test_api.py
=> BUG: fix selection predicates in filter_transform

doc/index.rst, doc/user_guide/ecosystem.rst
See #1090 for initial discussion. 
This PR is an initial draft of the **Altair Ecosystem** page. Here is an image showing what the page looks like:
=> Add Altair ecosystem page to docs

altair/vegalite/v2/examples/weather_heatmap.py
Added the [Annual Weather Heatmap](https://vega.github.io/vega-lite/examples/rect_heatmap_weather.html) example from the vega-lite examples page.
=> DOC: add weather heatmap example

altair/_magics.py, altair/expr/core.py, altair/expr/funcs.py, altair/expr/tests/test_expr.py, altair/sphinxext/altairgallery.py, altair/sphinxext/altairplot.py, altair/sphinxext/schematable.py, altair/sphinxext/utils.py, altair/tests/test_magics.py, altair/utils/core.py, altair/utils/data.py, altair/utils/headless.py, altair/utils/mimebundle.py, altair/utils/plugin_registry.py, altair/utils/save.py, altair/utils/schemapi.py, altair/utils/server.py, altair/utils/tests/test_schemapi.py, altair/vegalite/v1/api.py, altair/vegalite/v1/schema/channels.py, altair/vegalite/v2/api.py, altair/vegalite/v2/schema/channels.py, tools/generate_schema_wrapper.py, tools/schemapi/codegen.py, tools/schemapi/schemapi.py, tools/schemapi/tests/test_schemapi.py, tools/schemapi/utils.py
https://github.com/asottile/pyupgrade is a tool to automatically upgrade syntax for newer versions of Python.
=> Upgrade Python syntax with pyupgrade

CHANGES.md, altair/utils/core.py, altair/utils/tests/test_utils.py
=> Appropriately handle non-string column names

altair/vegalite/v2/api.py
=> Update test_predicates to include field predicates

altair/vegalite/v2/examples/bar_chart_sorted.py
I thought an example of a sorted bar chart would be a good addition to the examples.
=> DOC: add sorted bar chart example

paper/paper.md
See https://github.com/openjournals/joss-reviews/issues/1024
=> Paper: Add references section

paper/paper.bib
/ cc https://github.com/openjournals/joss-reviews/issues/1024#issuecomment-430900825
=> Bibtex changes to improve JOSS paper formatting

altair/vegalite/v2/examples/scatter_linked_brush.py
=> DOC: fix example title

doc/user_guide/troubleshooting.rst
This would have helped me in this situation.
=> update troubleshooting guide for empty charts caused by adblocker

CONTRIBUTING.md, README.md, paper/paper.bib
In response to https://github.com/openjournals/joss-reviews/issues/1057#issuecomment-437718892
=> Paper review updates

altair/examples/boxplot_max_min.py
IMHO, this is not a traditional box chart and should ultimately be filed elsewhere. For the time being, it can live in the other charts section
=> DOC: Reorg box and whisker

altair/examples/candlestick_chart.py
For now, let's put it in other
=> DOC: Another chart that should find a home outside the bars

altair/examples/beckers_barley_trellis_plot.py
=> DOC: Fixed shorthand mistake in barley plot

tools/generate_schema_wrapper.py
No user-facing changes... this is preparation for an easier upgrade to vega-lite 3.
=> Cleanup: streamline code generation

tools/generate_schema_wrapper.py, tools/schemapi/utils.py
preparation for vega-lite 3 (no user-facing changes)
=> MAINT: Fix schemapi issue with non-object schema defs

altair/utils/html.py, altair/vegalite/v2/tests/test_renderers.py
=> MAINT: improve embedOpt testing

altair/examples/bar_and_line_with_dual_axis.py, altair/examples/bar_chart_horizontal.py, altair/examples/bar_chart_with_highlighted_bar.py, altair/examples/bar_chart_with_highlighted_segment.py, altair/examples/bar_chart_with_labels.py, altair/examples/bar_chart_with_mean_line.py
Requires vega-datasets v0.7 for offline testing
=> DOC: use local wheat dataset in examples

altair/examples/beckers_barley_trellis_plot.py, altair/examples/boxplot_max_min.py, altair/examples/candlestick_chart.py, altair/examples/cumulative_wiki_donations.py, altair/examples/dot_dash_plot.py, altair/examples/error_bars_with_ci.py, altair/examples/horizon_graph.py, altair/examples/iowa_electricity.py, altair/examples/line_with_ci.py, altair/examples/poly_fit.py, altair/examples/scatter_marginal_hist.py, altair/examples/seattle_weather_interactive.py, altair/examples/simple_scatter_with_errorbars.py, altair/examples/stem_and_leaf.py, altair/examples/us_employment.py, altair/examples/us_population_over_time.py, altair/examples/us_population_pyramid_over_time.py, doc/case_studies/exploring-weather.rst, doc/getting_started/starting.rst, doc/user_guide/encoding.rst
Instead of setting encoding titles like this:
```python
x=alt.X('x', axis=alt.Axis(title='title'))
```
we should set them like this:
```python
x=alt.X('x', title='title')
```
=> DOC: change axis=Axis(title=title) to title=title

paper/paper.md
The [corresponding archive](https://zenodo.org/record/2030098) has already been updated.
=> [Paper] Add missing author to paper

altair/examples/boxplot_max_min.py, altair/examples/line_percent.py
=> DOC: ensure examples run offline

altair/examples/multiple_interactions.py
Closes altair-viz/altair-viz.github.io#16
=> Fix typo in title

altair/examples/isotype.py, altair/examples/isotype_emoji.py
Add isotype emoji plot (Similar to https://vega.github.io/vega-lite/examples/isotype_bar_chart_emoji.html)
=> Isotype emoji

altair/utils/core.py
=> MAINT: make docstring rewriting robust to nonexistent docstrings

altair/examples/scatter_alternate_axes_scale.py
=> Add example for alternate axes scale.

.gitignore, requirements.txt
=> MAINT: Add typing package version to requirements.txt

.gitignore, altair/examples/top_k_items.py, altair/utils/core.py, altair/utils/display.py, altair/utils/plugin_registry.py, doc/user_guide/transform.rst, requirements.txt
Adding sorting of 10 items of long list of items.
As mentioned in 
https://github.com/altair-viz/altair/issues/1306
and in notebook example:
https://github.com/altair-viz/altair_notebooks/pull/20
=> added top k items

doc/user_guide/configuration.rst
=> add borderless example

doc/user_guide/faq.rst
Help users avoid hitting things like #1358
=> DOC: add warning about CSV data transformer

altair/examples/select_mark_area.py
Moving this from issues to an example of how to use interval section with `mark_area`.
=> example using selection for mark_area

altair/examples/sorted_error_bars_with_ci.py
An adaptation of the https://github.com/altair-viz/altair/blob/master/altair/examples/error_bars_with_ci.py file. It took me a while to figure out how to do this, so figured I would submit it for others' benefit. 
I tried to stick to the style of the original file, but let me know if that is too many strangely placed parentheses.
=> Adding example of sorted error bars plot.

tools/generate_schema_wrapper.py
By design, this is a no-op for the current vega/vega-lite versions.
=> MAINT: update tools for compatibility with vega 5 & vegalite 3

altair/examples/scatter_with_layered_histogram.py
As mentioned in https://github.com/altair-viz/altair/issues/1376 . Hopefully might be useful to some people.
=> Example of scatter plot with linked layered histogram

altair/vegalite/v3/api.py
General concat chart that supports wrapping.
=> ENH: add VegaLite 3 ConcatChart

altair/examples/parallel_coordinates.py
Use the fold transform rather than pre-preocessing the data.
=> DOC: update parallel coordinates chart

altair/examples/errorbars_with_std.py
Using the new error bar mark to show the standard deviation.
=> ENH: Add Error Bars with Standard Deviation example

altair/sphinxext/altairplot.py, doc/conf.py, doc/user_guide/API.rst, doc/user_guide/configuration.rst, doc/user_guide/encoding.rst, doc/user_guide/internals.rst, doc/user_guide/marks.rst, doc/user_guide/troubleshooting.rst
Lots of small changes due to renaming of internal objects.
Also updated property tables for marks and encodings.
=> DOC: update sphinx docs for Altair 3

doc/Makefile
=> MAINT: update clean-generated in DOC makefile

doc/.gitignore
=> MAINT: Add data.json to doc ignore

altair/examples/bar_and_line_with_dual_axis.py, altair/examples/wheat_wages.py
=> ENH: Add William Playfair Wheat and Wages example

altair/examples/airports_count.py
I cannot find a complete fit dataset from vega-dataset, so I have to do a little by of transformation to demonstrate this example
#1366
=> add example for points overlay on maps

doc/getting_started/installation.rst, doc/user_guide/encoding.rst, doc/user_guide/troubleshooting.rst
=> Doc updates for Altair 3

altair/sphinxext/altairplot.py, altair/vegalite/v3/api.py, altair/vegalite/v3/tests/test_api.py
Fixes for a few issues encountered while trying to build the docs.
=> vegalite 3 fixes

altair/utils/schemapi.py, altair/vegalite/v3/api.py, tools/schemapi/schemapi.py
This makes errors clearer when assigning properties.
=> MAINT: add immediate validation of chart properties

altair/utils/core.py, tools/schemapi/utils.py
Mostly a test that I've got the dev env set up correctly, but whilst I'm there...
* Some pep8 violations
* Some deprecation warnings that show up in py.test
=> MAINT: Fix some minor nits

altair/examples/stacked_bar_chart_with_text.py
=> DOC: add example of stacked text annotations

altair/examples/wrapped_facet.py
@palewire - does this look OK to you?
=> DOC: add wrapped facet example

altair/examples/scatter_linked_table.py
Create an Altair implementation of the Vega-Lite example [Brushing Scatter Plot to show data on a table](https://vega.github.io/vega-lite/examples/brush_table.html).
=> Create brushing scatter plot to show data on a table example

CHANGES.md, altair/examples/us_population_over_time_facet.py, altair/vegalite/v3/api.py, altair/vegalite/v3/tests/test_api.py, doc/user_guide/compound_charts.rst
=> Wrapped facet operator

doc/user_guide/display_frontends.rst, doc/user_guide/faq.rst
=> DOC: add more complete discussion of using Altair outside notebooks

doc/user_guide/data.rst
Fixes #1488 
Tested with local doc build.
=> DOC: add fold transform discussion to data pivoting section

altair/vegalite/v3/api.py, altair/vegalite/v3/tests/test_api.py
=> ENH: add support for wrapped repeat

doc/user_guide/saving_charts.rst
=> fixed incorrect command in documentation - user_guide/saving_charts.rst

altair/vegalite/v3/api.py, altair/vegalite/v3/tests/test_api.py
=> ENH: add saner warnings when trying to layer un-layerable charts

CONTRIBUTING.md
I added some instructions on contributing examples to the project. 
Addresses part of https://github.com/altair-viz/altair/issues/1554
=> DOC: Add details on example contribution

altair/examples/top_k_with_others.py
Implementation of Top-K with Others [Example](https://vega.github.io/vega-lite/examples/window_top_k_others.html) from Vega-Lite website. Uses aggregate, window, and calculate transformations.
=> DOC: Add example for Top-K with Others.

altair/examples/window_rank.py
From Vega-Lite examples: https://vega.github.io/vega-lite/examples/window_rank.html
=> DOC: Add example for World Cup rankings with window transformation.

altair/vegalite/v3/api.py, altair/vegalite/v3/tests/test_api.py
=> BUG: fix top-level add_selection methods & remove LayerChart mark methods

altair/utils/schemapi.py, tools/schemapi/schemapi.py
This is a cleanup to enable functionality needed for refactoring the channel API.
=> MAINT: generalize schemapi from_dict

altair/vegalite/v2/schema/channels.py, altair/vegalite/v3/schema/channels.py, tools/generate_schema_wrapper.py
Should not change anything from the user's perspective.
=> MAINT: clean up channel to_dict()

altair/vegalite/v3/api.py
- remove ``resolve_*`` methods from non-compound chart
- add ``facet()`` method to all top-level charts
This more closely matches what is allowed by the schema.
=> Fix facet() and resolve() methods

doc/index.rst, doc/user_guide/scale_resolve.rst
=> DOC: add some docs for resolve()

altair/vegalite/v3/api.py, altair/vegalite/v3/tests/test_api.py
=> Test resolve() and facet() methods

altair/examples/interactive_layered_crossfilter.py
Same as in https://vega.github.io/editor/#/examples/vega-lite/interactive_layered_crossfilter
=> Update crossfilter to gray/blue scheme

doc/user_guide/faq.rst
=> Fix sentence in faq

altair/vegalite/v3/api.py, altair/vegalite/v3/tests/test_api.py, doc/user_guide/data.rst
I noticed the sphere generator was missing from the data gen wrappers.
=> Add API wrapper for sphere generator

doc/user_guide/transform.rst
=> DOC: Update transform.rst

altair/vegalite/v3/api.py, altair/vegalite/v3/tests/test_api.py, doc/user_guide/interactions.rst
This PR recommit the commits from #1707 which accidentally were removed in https://github.com/altair-viz/altair/pull/1714.
=> ENH: Recommit removed commits #1707

altair/vegalite/v3/api.py
This PR aligns the possible property options in the api function `project()` with the `Projection` class from the Vega-lite schema.
=> ENH: update properties in project shorthand

altair/examples/cumulative_count_chart.py
Hi.
I was looking to plot a cumulative count axis and only found a Vega example, so I thought I might as well PR a simple adaptation.
Hope this helps! Thank you.
=> Add example - Cumulative count

doc/user_guide/compound_charts.rst, doc/user_guide/configuration.rst, doc/user_guide/customization.rst, doc/user_guide/data.rst, doc/user_guide/display_frontends.rst, doc/user_guide/faq.rst, doc/user_guide/renderers.rst, doc/user_guide/times_and_dates.rst, doc/user_guide/transform.rst, doc/user_guide/troubleshooting.rst
=> DOC: Fix typos in user guide

altair/sphinxext/altairgallery.py, altair/sphinxext/utils.py
I've also needed to tweak `altairgallery.py` to finish validation.  Probably Windows specific.
=> Proposed fix for #1781

altair/vegalite/v3/api.py, altair/vegalite/v3/tests/test_api.py
=> BUG: LayerChart.add_selection: apply selection only to first layer

altair/vegalite/v3/api.py, altair/vegalite/v3/tests/test_api.py
=> BUG: fix issue with count() in joinaggregate

altair/utils/html.py
Tested changes on classic notebook, JupyterLab, nbconvert, and Colab
=> clean up universal HTML

altair/sphinxext/altairplot.py, doc/conf.py, doc/user_guide/API.rst, doc/user_guide/configuration.rst, doc/user_guide/customization.rst, doc/user_guide/internals.rst
Still need to add sections on new transforms, etc. Will do that as another PR.
=> DOC: update docs for V4 changes

doc/user_guide/transform.rst
=> V4: Document new transforms

altair/examples/scatter_image_marks.py, doc/user_guide/marks.rst
I added an example and also edited the table on the marks page to link to it
=> DOC: add image mark example

altair/utils/schemapi.py, tools/schemapi/schemapi.py
=> schemapi: use first class match rather than last.

setup.py
=> Fix simple typo: packge -> package

doc/user_guide/transform.rst
See an interactive version of the new chart [here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6bYwIAuy8ArrDQM4DqyAJhQBakAsADLwBooceFVr0GACQJoOFUgGZ+AX2UDwUADYBDAJ4EATqQDaGiKAiWoAW20GA1qUibqBSOqsRIBeHFbV0LAtPLzhNWCMgyApdAAc3LEh4WGtqbU13KBQCTVYnBl1rACNYDLUzT0gAD1IcGPinCgJrWIj0zMhs3KdWbSbIcpCvXVrouISoAEcabVFkCj7kXDchTsJuxNiDZGg3ZQqIfatBy2CrSFsHJ1bqeQ9Knz8A2oPLcnDIsnqJpJS0jNWXTyiQKxVKA3uIWqo2+jWarQM7UB62BUF6-ROUJGUVhiWmsyoCyoyw6QOu212A1emLeFER8AYiAi1hMOBQmianxwDByBGgVAQ+V5-IivAATAAOAbKAC6FRpZzel0ciQMNE0K1e3l8sH88EC2FeXlgsW00Hm2MNQzeIn8Avgo1w6RoE14ADoFKseRr+chBSDhRRRZKIUa3k7NC7SLwwzTzkHSlRYiYw+Yxg08TM5kSlissiinABBQsABQAMqHrWncVMs4TFiTkTlUZBCwBZABaADlK1W6uMnPjsw282tm04AOIAeSnE971v7GdrBPmI9JBcSAEkAEJt+dDRc-If14mjsmJNsAZQAYgAVKnWmWQyo1HEDxJNFptAH58eJdF7NSz5eN6fL …
=> DOC: add pivot/tooltip demo

altair/examples/interactive_legend.py
Adapted from the [vega-lite example](https://vega.github.io/vega-lite/docs/bind.html#legend-binding)
=> DOC: add interactive legend example

doc/user_guide/data.rst
Small code fix in example code
=> Apply orientation to geometry column

altair/vega/v5/schema/core.py, altair/vegalite/v3/schema/core.py, altair/vegalite/v4/schema/core.py, tools/schemapi/tests/test_utils.py, tools/schemapi/utils.py
Fixes #1847 
Write unit tests, people.
=> MAINT: fix auto-generated description of empty schemas

RELEASING.md
Make sure the release notes are updated with the new doc format for releases.
=> Update the release notes to reflect the new release file format

altair/examples/area_chart_gradient.py
I noticed we didn't have a gradient fill example.
=> DOC: add area chart with gradient fill example

altair/utils/data.py
See #1867
Tested locally - works in both JupyterLab and Jupyter notebook.
=> Allow JSON data transformer to specify custom URL path

altair/examples/candlestick_chart.py
I think this example is much better now.
=> DOC: update candlestick example to use ohlc dataset

altair/examples/interval_selection.py
=> DOC: Fix interval selection bug

altair/vegalite/v4/theme.py
PR merged
https://github.com/vega/vega-themes/pull/64
=> add Urban Institute theme

altair/utils/schemapi.py, altair/utils/tests/test_schemapi.py, tools/schemapi/schemapi.py, tools/schemapi/tests/test_schemapi.py
=> ENH: support numpy types within chart specifications

altair/examples/histogram_responsive.py
example datasets should all be offline for testing purposes.
=> DOC: use URL for flights dataset

altair/examples/scatter_with_loess.py
I thought an example of adding multiple grouped LOESS lines to a scatter plot could be a useful addition to the docs.
=> DOC: add scatter with loess example

altair/utils/schemapi.py, tools/schemapi/schemapi.py
=> BUG: fix schema validation error in Python 3.8

altair/examples/layered_chart_with_dual_axis.py
=> DOC: add dual y axis example

altair/expr/core.py
discussed in https://github.com/altair-viz/altair/issues/1972
=> FIX: change datum repr to fix doc build

doc/user_guide/scale_resolve.rst
Add the dual y axis example to the scale resolve user guide
=> DOC: Scale resolve edits

altair/utils/tests/test_mimebundle.py, altair/vegalite/v3/tests/test_api.py, altair/vegalite/v4/tests/test_api.py
This would have been caught by an automated flake checker.
=> TST: fix unintentionally overwritten test

altair/utils/schemapi.py, tools/schemapi/schemapi.py
This issue was uncovered when trying to update to vega-lite > 4.0
=> BUG: fix schema from_dict for schema instance

.github/workflows/lint.yml, .travis.yml, Makefile, altair/_magics.py, altair/utils/core.py, altair/utils/execeval.py, altair/utils/schemapi.py, altair/utils/server.py, altair/vegalite/v3/api.py, altair/vegalite/v3/tests/test_api.py, altair/vegalite/v3/tests/test_data.py, altair/vegalite/v4/api.py, altair/vegalite/v4/tests/test_api.py, altair/vegalite/v4/tests/test_data.py, doc/conf.py, setup.cfg, setup.py, tools/generate_api_docs.py, tools/generate_schema_wrapper.py, tools/schemapi/schemapi.py
Also move flake8 check from Travis to lint github action.
=> MAINT: flake8 check on all but examples & generated files

altair/utils/tests/test_mimebundle.py
=> TST: re-enable mimebundle test

altair/examples/scatter_with_minimap.py
Implements what was discussed here: https://github.com/altair-viz/altair/issues/2037
I think this is a useful recipe for large time-series data -- if you only have one view, you kind of need to choose between having enough detail and having enough context.
=> Add an example showing how to create a minimap

.github/workflows/build.yml, .github/workflows/docbuild.yml, altair/examples/multi_series_line.py, altair/utils/core.py, altair/vega/v5/schema/__init__.py, altair/vega/v5/schema/core.py, altair/vega/v5/schema/vega-schema.json, altair/vegalite/v4/api.py, altair/vegalite/v4/schema/__init__.py, altair/vegalite/v4/schema/channels.py, altair/vegalite/v4/schema/core.py, altair/vegalite/v4/schema/mixins.py, altair/vegalite/v4/schema/vega-lite-schema.json, altair/vegalite/v4/tests/test_api.py, doc/releases/changes.rst, doc/user_guide/API.rst, doc/user_guide/encoding.rst, tools/generate_schema_wrapper.py
Tests will not pass until VL 4.8 is part of altair_viewer.
=> WIP: Update to Vega-Lite 4.8

.github/workflows/docbuild.yml, doc/user_guide/API.rst
These are long testing steps, so it makes more sense to do them in parallel.
=> MAINT: split doc build and test in github CI

altair/utils/save.py, altair/vegalite/v3/api.py, altair/vegalite/v3/tests/test_api.py, altair/vegalite/v4/api.py, altair/vegalite/v4/tests/test_api.py
=> BUG: support pdf format in chart.save

doc/user_guide/encoding.rst
Update reflecting the change in behavior in a recent vega-lite update.
=> DOC: tiny update

altair/expr/core.py, altair/expr/tests/test_expr.py
=> Fix item access for expressions

altair/examples/line_chart_with_points.py
This is a PR to fix #2100.
I couldn't dare to add second chart as it seems that only one per example is desired. So I decided to update text description. I hope that is OK.
=> DOC: Update "Line Chart with Points" example.

tools/generate_schema_wrapper.py
Getting some CI failures on a couple PRs which I think this fixes
=> CI: Fix flake8 import issue

doc/user_guide/encoding.rst
Resolves #2202 as well as fills in some more examples.
=> Update encoding guide table

doc/user_guide/ecosystem.rst
Adding gif to the source Ecosystem instead of generated docs
=> Ecosystem: gif

doc/user_guide/importing.rst
I've updated the Altair version the note is referring to.
=> Changed Altair version to 4

altair/utils/data.py, altair/utils/schemapi.py, altair/utils/tests/test_mimebundle.py, altair/vegalite/v3/tests/test_api.py, altair/vegalite/v4/tests/test_api.py, tools/schemapi/schemapi.py
I noticed #2292 failed due to formatting errors. 
I simply ran `black .` on the root directory, and it reformatted a few files.
=> maint: black formatting

altair/examples/comet_chart.py
Here's the example resulting from https://github.com/altair-viz/altair/issues/2395.
=> add comet chart example

altair/examples/boxplot.py
If you prefer I can change the title instead, but currently it does not match with the example code. I think it is more useful to see the non-default behavior and expanded a bit on the note regarding the default, but up to you.
=> Correct boxplot example to reflect title

CONTRIBUTING.md
I fixed a few typos in Contributing.md.
=> fix typos in Contributing.md

altair/examples/hexbins.py
I like to use hexbin charts, and thought it would be nice to include a example to altair's documentation. Please feel free to review and eventually correct or extend my contribution, if you think it is worth merging with your master branch.
As always, thank you for your great work!
=> Add Hexbin Example to docs

.github/workflows/build.yml, .github/workflows/docbuild.yml, .github/workflows/lint.yml, altair/sphinxext/altairgallery.py, altair/sphinxext/schematable.py, doc/conf.py, requirements.txt, setup.py
Trying to get CI green again...
=> MAINT: fix CI

altair/utils/schemapi.py, requirements.txt, tools/schemapi/schemapi.py
Fixes #2496.
This builds on the commits from #2502; I'll rebase once that's merged.
=> Jsonschema update

altair/examples/layered_histogram.py, altair/examples/scatter_marginal_hist.py
Implements solution discussed in issue #2411 (based on https://github.com/vega/vega-lite/issues/5403) for the examples [Layered Histogram](https://altair-viz.github.io/gallery/layered_histogram.html) and [Facetted Scatterplot with marginal histograms](https://altair-viz.github.io/gallery/scatter_marginal_hist.html).
=> fix histograms

altair/utils/html.py
Tested in Chrome & Safari, with JupyterLab, Jupyter Notebook, and Colab frontends.
cc/ @mattijn
=> ENH: track JS versions in default HTML display

requirements_dev.txt
Fixes https://github.com/altair-viz/altair/pull/2531#issuecomment-992554213
=> MAINT: pin mistune in dev requirements

requirements.txt
jsonschema 4.3 fixes the performance issue.
=> MAINT: remove upper restriction on jsonschema version

altair/examples/pyramid.py
=> Add pyramid example

altair/examples/falkensee.py
This adds a title and cleans up the axis labels. IMHO, our case studies should all strive to be fully polished charts that are ready to for publication.
=> Tidy Falkensee case study

altair/examples/pyramid.py
This chart doesn't demonstrate a general charting technique or tricks. It's a detailed implementation of a notable chart. For that reason, I think it fits the definition of what we include in the case studies group.
=> Add pyramid pie chart to case studies

altair/examples/image_tooltip.py
This seems like a more specific place to put this example.
=> Move image tooltip example to interactive charts section

altair/examples/window_rank.py
This chart is an example of a general technique, not a fully designed out demonstration of a famous chart or in-detail example. So I propose moving it into the category with other line charts.
=> Move window rank technique to line charts section

altair/examples/bar_rounded.py
For consistency with our other examples
=> Style fix to chart headline

altair/examples/binned_heatmap.py, altair/examples/hexbins.py, altair/examples/layered_heatmap_text.py, altair/examples/table_bubble_plot_github.py, altair/examples/wind_vector_map.py, altair/sphinxext/altairgallery.py
The other charts in the "Simple Charts" section at the top of the page have their own sections lower down. If that's our rule of thumb, we should add a heatmaps section too.
=> Create a new tables section

doc/user_guide/marks/geoshape.rst
The geoshape.rst was not well linked with the index.rst, fixing.
=> fix reference geoshape.rst to index.rst and some typos

altair/examples/waterfall_chart.py
Addresses open points from #2621. I also further simplified the code, hopefully making the example a bit easier to understand.
=> Improve waterfall example

doc/user_guide/customization.rst, doc/user_guide/large_datasets.rst
Addresses the two only sphinx warnings we currently have when building the docs
=> Fix minor formatting issues in documentation

altair/utils/plugin_registry.py
=> No longer use deprecated SelectableGroups dict interface of entry points

altair/vegalite/v5/api.py
This PR includes the depcrecation message in the docstring as well.
=> include deprecation message in docstring

README.md, doc/case_studies/exploring-weather.rst, doc/user_guide/compound_charts.rst, doc/user_guide/marks/line.rst, tests/examples_arguments_syntax/dot_dash_plot.py, tests/examples_arguments_syntax/interactive_brush.py, tests/examples_arguments_syntax/interactive_layered_crossfilter.py, tests/examples_arguments_syntax/interval_selection.py, tests/examples_arguments_syntax/multiline_highlight.py, tests/examples_arguments_syntax/multiline_tooltip.py, tests/examples_arguments_syntax/scatter_linked_brush.py, tests/examples_arguments_syntax/scatter_linked_table.py, tests/examples_arguments_syntax/selection_histogram.py, tests/examples_arguments_syntax/selection_layer_bar_month.py, tests/examples_arguments_syntax/us_state_capitals.py, tests/examples_methods_syntax/interactive_layered_crossfilter.py, tests/examples_methods_syntax/interval_selection.py, tests/examples_methods_syntax/multiline_highlight.py, tests/examples_methods_syntax/multiline_tooltip.py, tests/examples_methods_syntax/us_state_capitals.py
More examples that were not (yet) included in https://github.com/altair-viz/altair/pull/2923
=> use selection_point or selection_interval syntax

doc/user_guide/interactions.rst
This is an attempt to resolve #2904. While not addressing all the details of that issue, I feel this PR captures expressions sufficient to understand the capabilities.
=> include section on expressions for interaction

doc/user_guide/interactions.rst
Some examples are not rendering without this
=> Add missing pandas import in docs

altair/vegalite/v5/api.py, doc/releases/changes.rst, doc/user_guide/interactions.rst
fix indentations docstring errors and warnings
=> fix docstrings errors

doc/conf.py
see screenshot, links to https://github.com/altair-viz/altair/issues/2937, currently still placeholder.
=> include issue in announcement

tools/schemapi/tests/test_schemapi.py
In #2931 I didn't apply the changes in the correct tools script. Created #2940 to prevent this from happening in the future.
=> Apply changes of #2931 in tools folder

doc/user_guide/display_frontends.rst, pyproject.toml, tests/vegalite/v5/test_api.py
See https://github.com/altair-viz/altair/discussions/3145#discussioncomment-6693697 for context. Related to this also #2866
=> MAINT: Remove altair viewer as a development dependency

altair/utils/core.py
@jonmmease This should fix the errors you found in #3151. Feel free to merge afterwards so it doesn't block you!
=> MAINT: Fix type hint errors which came up with new pandas-stubs release

tests/examples_arguments_syntax/line_custom_order.py, tests/examples_methods_syntax/line_custom_order.py
Followup to https://github.com/altair-viz/altair/pull/3155.
I think this use case should be more easily discoverable, so it should be in the example gallery. Let me know if I need to do something else, or if just creating this file will trigger discovery and build.
I tweaked the prose from https://altair-viz.github.io/user_guide/marks/line.html#connected-scatter-plot-line-chart-with-custom-path just a little bit
=> docs: examples: add line plot with custom order

governance/org-docs/STEERING-COMMITTEE.md
Based on decision of committee meeting of 2023-08-25. See https://github.com/altair-viz/altair/discussions/3164#discussioncomment-6825302
=> Governance: Mark @binste as committee chair

altair/utils/core.py
=> Remove usage of deprecated Pandas parameter convert_dtypes

tests/utils/test_utils.py
=> Maint: Do not pass literal json to read_json in test

altair/utils/schemapi.py, altair/vegalite/v5/api.py, tools/schemapi/schemapi.py
=> Relax type hint for 'indent' in to_json method

doc/conf.py
As dicussed, this closes #3397
=> docs: Reduce number of items in header to 4

pyproject.toml, tests/utils/test_compiler.py, tests/utils/test_core.py, tests/utils/test_html.py, tests/utils/test_mimebundle.py, tests/utils/test_schemapi.py, tests/vegalite/test_common.py, tests/vegalite/v5/test_api.py, tests/vegalite/v5/test_data.py, tests/vegalite/v5/test_renderers.py, tests/vegalite/v5/test_theme.py
Due to https://github.com/astral-sh/ruff/pull/12106/files, this is currently failing some CI runs
=> chore: fixup ruff-mypy CI job due to Ruff change

pyproject.toml
Related
- https://github.com/vega/altair/pull/3515#discussion_r1706725275
- https://github.com/vega/altair/pull/3523#issuecomment-2271764729
=> ci: Bump `sphinx`, `vl-convert-python`

altair/utils/_transformed_data.py, pyproject.toml
Fixes https://github.com/vega/altair/actions/runs/10306826815/job/28530735560
Merge to solve CI failure on main, that occured due to `ruff` updating
=> fix(ruff): Bump `ruff`, fix `RUF031`

tests/examples_arguments_syntax/us_population_over_time.py, tests/examples_arguments_syntax/us_population_pyramid_over_time.py, tests/examples_methods_syntax/us_population_over_time.py, tests/examples_methods_syntax/us_population_pyramid_over_time.py
=> fix: Update docs to use correct init value for `selection_point`

altair/utils/html.py
- Fix https://github.com/vega/altair/issues/3603
I'm not sure if you want a more sophisticated approach, or even if this is user-error rather than a defect, but this at least fixed my immediate problem and may be "good enough" for the project.
=> fix: Set charset=UTF-8 in HTML templates.

altair/vegalite/v5/api.py
Follow-up to #3662
This PR simply aligns the changes introduced there to provide a consistent UX.
=> docs(typing): Update `selection_point` signature

LICENSE
Yearly copyright bump. Padding my changed LOC! 😛
=> docs: Update LICENSE, fix copyright license year

altair/theme.py, altair/utils/_vegafusion_data.py, altair/utils/compiler.py, altair/utils/core.py, altair/utils/data.py, altair/utils/display.py, altair/utils/execeval.py, altair/utils/plugin_registry.py, altair/vegalite/data.py, altair/vegalite/v5/api.py, sphinxext/code_ref.py, tests/expr/test_expr.py, tests/utils/test_data.py, tests/utils/test_plugin_registry.py, tests/utils/test_schemapi.py, tests/vegalite/v5/test_theme.py, tools/schemapi/codegen.py, tools/update_init_file.py, tools/vega_expr.py
Fixes https://github.com/vega/altair/actions/runs/12582781184/job/35069043773#step:6:494
(https://github.com/astral-sh/ruff/pull/5454) was merged in (https://github.com/astral-sh/ruff/releases/tag/0.8.5) and triggered these existing rules
=> chore(ruff): Fix ruff warnings

altair/utils/data.py
Came across this error while looking into [`pdvega.plotting.andrews_curves()`](https://github.com/altair-viz/pdvega/blob/e3f1fc9730f8cd9ad70e7ba0f0a557f41279839a/pdvega/plotting.py#L107-L186) for #2470
I think this is pretty helpful if you've performed a transformation that *significantly* alters the shape of your data.
In this case, I was confused as the source data had `150` rows, but after transforming this exploded to `30000`.
```
MaxRowsError: The number of rows in your dataset is greater than the maximum allowed (5000) ...
```
Now the number of rows is clearly displayed in the first set of parentheses:
```
MaxRowsError: The number of rows in your dataset (30000) is greater than the maximum allowed (5000).
Try enabling the VegaFusion data transformer which raises this limit by …
```
=> feat: Show `user_rows` in `MaxRowsError` message

doc/getting_started/resources.rst
Adds a link to the altair-upset package!
=> docs: Add altair-upset link

altair/utils/core.py, altair/utils/data.py, pyproject.toml, uv.lock
=> ci: bump `narwhals>=1.27.1`

doc/about/code_of_conduct.rst
Make the Code of Conduct link clickable
https://altair-viz.github.io/about/code_of_conduct.html
=> docs: Make the Code of Conduct link clickable
