vega/altair

.travis.yml, altair/html.py, altair/templates/template.html, altair/tests/test_html.py, example-html-rendering.ipynb, requirements.txt, setup.py
This PR adds simple rendering of the specification's generated by the API via html. Example usage looks like this (here we're targeting display in an IPython notebook):
```
from altair import api, html
from IPython.display import HTML, display
data = dict(x=[1, 2, 3], y=[1, 2, 3])
spec = api.Viz(data).encode(x='x:Q', y='y:Q').mark_line()
out = html.render(s)
display(HTML(out))
```
I included a pretty bare bones test `html`. Also the size handling needs some testing. But otherwise should be functional.
=> Html rendering

README.md
1.2.1 or better will work and releases will be more stable than master
=> update lightning dependency version in readme

altair/api.py
This is a tiny change in the top-level API that makes for less boilerplate. Using the scatterplot example, the current API looks like this:
```python
Layer(data).encode(
X('Horsepower'),
Y('Miles_per_Gallon'),
Color('Origin'),
Size('Weight_in_lbs')
).point()
```
You can also use keywords, e.g.
```python
Layer(data).encode(
x=X('Horsepower'),
y=Y('Miles_per_Gallon'),
color=Color('Origin'),
size=Size('Weight_in_lbs')
).point()
```
With this PR, there is a (to my mind) more intuitive way to do this:
```python
Layer(data).encode(
x='Horsepower',
y='Miles_per_Gallon',
color='Origin',
size='Weight_in_lbs'
).point()
```
The string arguments are converted automatically to the appropriate object. Note that this works only in the ``encode()`` function, not deeper within the object hierarchy.
What …
=> Remove boilerplate from API

altair/api.py, altair/schema/baseobject.py, altair/tests/test_api.py
Two additions to the API here:
First, ``configure()`` is enhanced to handle arguments similarly to ``encode()``. So you can do
```python
Layer(data).configure(MarkConfig(color='red'))
```
as a shorthand for
```python
Layer(data).configure(mark=MarkConfig(color='red'))
```
Secondly, I added the ``data_transform()`` method similar to ``configure()`` and ``encode()``, so you can do this:
```python
population = load_dataset('population')
Layer(data).data_transform(
filter="datum.year==2000"
)
```
in place of the current approach:
```python
Layer(data, transform=Transform(filter="datum.year==2000"))
```
I realize ``data_transform`` is a bit awkward/redundant. This really should be called ``transform``, but that is already used as an attribute name in vega-lite. IMHO, it would be more …
=> [MRG] enhance configure() and add data_transform() method

altair/api.py, altair/tests/test_api.py, altair/utils/html.py, altair/utils/tests/test_html.py
I started comparing our docs to those of Vega-Lite, and noticed that they emphasize how to publish visualizations online: https://vega.github.io/vega-lite/tutorials/getting_started.html#embed
This PR uses that example as a template, and creates a ``to_html()`` method for top-level objects which export charts to stand-alone HTML.
=> ENH: add to_html() methods

altair/api.py, altair/schema/_wrappers/channel_wrappers.py, altair/tests/test_api.py, altair/utils/core.py, altair/utils/tests/test_utils.py, altair/utils/visitors.py, tools/templates/channel_wrappers.tpl
Addresses #46 – parsing of shorthands is now more robust, so that column names with spaces, colons, parentheses, and other characters works.
Additionally, I moved the shorthand parsing to the ``_finalize()`` method, rather than using a traitlet observer. Due to the refactoring, I was also able to remove the specialization of ``type`` within channels, as well as observers of ``shorthand`` and ``type``.
The result is about 70 fewer lines of code overall, excluding the additional tests that are part of this PR.
=> [MRG] Refactor shorthand parser

altair/utils/html.py
When I tried to save a local plot as an HTML file and view in my web browser using `file://`, I could not see the plot. To fix this, in the function `to_html` I added an optional parameter `local_file` which defaults to True. When True, it loads the CDNs with `http://` and if False it loads under `//`.
Currently in the default HTML template, the CDNs are being loaded as `<script src="//vega.github.io/vega/vega.js"></script>` and then because I was viewing local HTML file as `file://`, it tries to load `file://vega.github.io` which obviously doesn't exist.
=> ENH: load CDNs when viewing under file://

altair/api.py
`to_html` function handles kwargs, but `to_html` method doesn't forward any.
=> Forward kwargs from to_html

altair/utils/core.py, altair/utils/tests/test_utils.py
This commit fixes the issue of numpy array scalars in a column with dtype=object not being serializable. Also adds a quick test of the behavior.
=> BUG: fix serialization of numpy scalars (fixes #165)

altair/api.py, altair/tests/test_api.py, altair/utils/_py3k_compat.py, altair/utils/server.py, altair/utils/tests/test_server.py
This PR adds a functionality to create altair plots from outside the Jupyter notebook; e.g.
```python
from altair import Chart, load_dataset
cars = load_dataset('cars')
chart = Chart(cars).mark_point().encode(
x='Horsepower',
y='Miles_per_Gallon',
color='Origin',
)
chart.serve()
```
The final line will create a local web server, and by default launch a web browser window showing this visualization.
=> ENH: add Chart.serve() command to serve HTML

altair/utils/node.py, altair/utils/tests/test_node.py
This PR includes an experimental interface to save Altair charts to PNG or EPS from Python.
This requires several ``nodejs`` packages to be installed. With conda, the following works on my system:
```bash
$ conda install nodejs -c conda-forge
$ npm install canvas vega-lite  # requires python 2.7 for some reason
$ ls ~/node_modules/.bin/
vg2png  vg2svg  vl2png  vl2svg  vl2vg
```
If this works, then the script here should work:
```python
from altair import Chart
from altair.examples import load_example
chart = Chart.from_dict(load_example('area.json'))
savechart(chart, 'chart.png')
```
Then ``chart.png`` is a png of the chart.
=> ENH: add interface to save chart to PNG/SVG

doc/documentation/datasets.rst, doc/documentation/displaying.rst, doc/faq.rst, doc/index.rst, doc/installation.rst
@ellisonbg I noticed this when we looked at the docs earlier today. I've gone through all the files in the `docs` directory. These are the only files that needed edits.
=> DOC: correct case in GitHub

requirements.txt, setup.py
Traitlets 4.3 fixes the issues that you reported wrt Union trait types. Error messages should now make sense.
=> Require traitlets 4.3.1

altair/utils/core.py
Fixes #332 by using the newer API.
Let me know if we'd rather break compat with older pandas and avoid the import check.
=> Migrate to pandas.api from pandas.lib where available

altair/urls.py
The default url for vega-lite.js no longer seems to work which means it has be overwritten in chart.to_html() every time.
=> correct default url for version 1 of vega-lite.js

altair/__init__.py, altair/api.py, altair/utils/__init__.py, altair/utils/core.py, altair/utils/display.py, altair/utils/tests/test_display.py, doc/faq.rst, doc/index.rst, doc/installation.rst
Initial prototype that works with JupyterLab.
Closes https://github.com/altair-viz/altair/issues/294 and https://github.com/altair-viz/altair/issues/172.
=> [WIP] Changing to MIME based rendering

altair/expr/tests/test_expr.py, altair/v1/__init__.py, altair/v1/api.py, altair/v1/tests/test_api.py
Fixes #392 
This introduces a `disable_mime_rendering` function and allows it and `enable_mime_rendering` to be called multiple times without side effects.
=> More robust MIME rendering and fix tests.

doc/documentation/index.rst, doc/documentation/interactive.rst
Mentions package `altair_widgets` in documentation and shows GIFs of examples.
I would add an example in the HTML but #306 is blocking tests.
=> DOC: mention altair_widgets in documentation

doc/documentation/displaying.rst
Goals of this reorganization:
* document `to_*`/`from_*` (in "Obtaining other representations")
* I did not document file IO
* document `Chart.savechart` (in "Representation output to file")
* provide clearer purpose for top section
* labeled top section ("Vega-Lite JSON specification")
* trimmed JSON example from 20 to 9 lines.
* Reordered sections for order of usefulness IMO. Sections reordered, in order from most to least useful IMO:
* "Displaying in Jupyter notebook"
* "Displaying via local HTTP server"
* "Representation output to file" (with a subsection "Obtaining other representations")
This fixes the documentation issue I ran into in #322.
=> DOC: Reorganizes documentation page "Displaying and Saving"

altair/v1/__init__.py, altair/v1/api.py, altair/v1/examples/tests/test_examples.py, altair/v1/tests/test_api.py
This adds a new `_validate_spec` method to the `Chart` object that is called during the last phase of `_finalize` (after shortcuts and expressions have been processed). It catches channels with missing fields and fields that are not in the dataset. It should ignore URL based datasets. Tests are included.
My only concern is how this will function for facetted and layered charts. I fear it will have the same problems that PR #185 does. But it would be a huge usability improvement that would catch the most common sources of silent failures that Altair users see.
I won't merge this until we get a chance to discuss and review...
Fixes #388
=> Check field names

doc/conf.py, doc/index.rst, doc/requirements.txt, doc/sphinxext/altair_ext/altairplot.py
These are the changes required to use the basic ReadTheDocs theme. Only one nontrivial thing in here: because the theme loads javascript at the bottom rather than the top of each page, we need to use a ``DOMContentLoaded`` listener to build the charts once the rest of the content is loaded.
This is supported by all modern browsers, but not by IE8 or before, which according to [this site](http://caniuse.com/#feat=domcontentloaded) only account for about 0.2% of web traffic.
Can we live with that?
=> DOC: change website to ReadTheDocs theme

altair/utils/schemapi.py, altair/vegalite/v2/api.py, altair/vegalite/v2/schema/channels.py, altair/vegalite/v2/schema/core.py, tools/schemapi/decorator.py, tools/schemapi/schemapi.py, tools/schemapi/tests/test_schemapi.py, tools/schemapi/tests/test_utils.py
With the stacking and layering available in VegaLite 2.0, I think it makes sense to have chart methods return copies of the chart rather than mutate the chart.
What this means is that with this PR in place, we could do things like this:
```python
chart = Chart(data).encode(x='x', y='y')
chart.mark_line() + chart.mark_point()
```
The result is a layered chart marked by both points and lines
similarly for faceting:
```python
chart = alt.Chart(data).mark_point().encode(y='y')
chart.encode(x='x1') | chart.encode(x='x2')
```
The result is a two-panel side-by-side chart with a shared y-axis, but different encodings on the x axes. Previously this kind of layering and stacking would require much more boilerplate, or an explicit copy of the chart.
The pattern that will not work anymore after this …
=> API change: make chart methods return copies

.travis.yml, altair/vega/v3/schema/__init__.py, altair/vegalite/v2/api.py, altair/vegalite/v2/examples/tests/test_examples.py, requirements.txt, setup.py
simplify travis tests so things pass... for now :smile:
=> Fix travis

altair/vegalite/v2/examples/layer_line_color_rule.py
Jake, if I notice things not working while building examples - please let me know if you would rather me file a github issue, or do a pull request of the example noting the difficulties.
I saw this example:
https://github.com/altair-viz/altair/blob/master/altair/vegalite/v2/examples/mutli_series_line.py
and then looked at the vega-lite example:
https://vega.github.io/editor/#/examples/vega-lite/layer_line_color_rule
I noticed that I could not get the .config to modify an attribute, in this case the line:
chart.config = {'rule': {'size': 20}}
does not seem to be doing anything, so I commented it out for the moment.  I have looked in the vega-lite documentation and I seem to be using the correct terms so I am not sure what is causing it.
I know you showed me how .config can work in this …
=> add in vega-lite example of line layer rule

altair/vegalite/v2/examples/falkensee.py
This has one issue:
When building the final chart
chart = line + recta + point
recta should be in the first position so it does not cover up the lines and points, but if I put recta there errors will result.  line + point + recta work fine as well, just (at this point) can't have recta in first position where it needs to be for the visual composition to work.
The errors are: KeyError: 'population'
I am assuming vega-lite is expecting the full axis with the item in first position - or it is building components before they are loaded(since population is only in the line/points data and not recta's data)?
The vega-lite example is here:
https://vega.github.io/vega-lite/examples/layer_falkensee.html
=> added vega-lite example of falkensee

altair/vegalite/v2/examples/layered_plot_with_dual_axis.py
Here is one I have been struggling with.  In the vega-lite example:
https://vega.github.io/vega-lite/examples/layer_bar_dual_axis.html
It has this part:
"resolve": {"scale": {"y": "independent"}}
that sits at the same level as:
"$schema": "https://vega.github.io/schema/vega-lite/v2.json",
"data": {"url": "data/seattle-weather.csv"},
I have toyed with ideas like:
y = alt.Y('mean(temp_max)', resolveMode = 'independent'))
also tried to put it in config, but I get errors every time.
I do note that I see resolvemode in here:
https://github.com/altair-viz/altair/blob/0fec41674f062c5e37d5af0b6b318702362f0115/altair/vegalite/v2/vega-lite-schema.json
So I am missing how to connect it up.
Note: the plot included works, it just overwrites the line's y axis with the bar's y axis, if you call out line …
=> adding vega-lite example of layered plot with dual-axis

altair/vegalite/v2/examples/boxplot_max_min.py
Implements https://vega.github.io/vega-lite/examples/box-plot_minmax_2D_vertical_normalized.html .
A few open questions on style:
- Wasn't sure if there's a way to carry over the "create calculated fields and give them names" concept from the vega-lite spec, so I can rewrite this if there's a more idiomatic way to do this.
- The `size` parameter passed into the `mark_rule` and `mark_tick` methods appears to have no effect, as in the rendered chart, the widths of those items stays constant
- The `style` parameter appears to have no effect either (for setting rule style to `boxWhisker`).
=> #457: Add Box Plot (Max/Min Whiskers) Example

altair/vegalite/v2/examples/trellis_histogram.py
Implements the vega-lite example from
https://vega.github.io/vega-lite/examples/trellis_bar_histogram.html
Note that the row labels will show up on the right instead of on the left (as they are in the vega-lite online example).
=> #457: Add Basic Trellis Histogram Example

altair/vegalite/v2/examples/histogram.py
Implements https://vega.github.io/vega-lite/examples/histogram.html .
The primary change compared to Altair 1.3 seems to be that the `Bin` class was renamed `BinTransform`. ( https://altair-viz.github.io/gallery/histogram.html ) . 
I'm not sure if there is a practical difference is between using `:Q` as a suffix, vs explicitly setting `type='quantitative'`. However I felt the second option was more explicit, and so I went with that instead.
=> #457: Add Basic Histogram Example

altair/vegalite/v2/api.py, altair/vegalite/v2/examples/interval_selection.py, altair/vegalite/v2/examples/scatter_linked_brush.py
This PR is an initial attempt at streamlining the creation and use of selections in Altair. I've added a ``SelectionMapping`` object to the API, which users should not have to directly use. I've also added an ``alt.selection`` function which allows users to create and manipulate named selection.
The example file shows how I envision this working, and it creates an interactive example similar to the one [here](https://vega.github.io/vega-lite/examples/interactive_overview_detail.html).
Any thoughts on this Python API for selections? cc/ @ellisonbg @domoritz @kanitw @jheer
=> Interval selection

altair/vegalite/v2/examples/binned_scatterplot.py
I will note that:
size = 'count(*)'
does not work and gives a keyerror of:
KeyError: '*'
I thought this was a capability that was here before.
But for this example I just set it to:
size = 'count(IMDB_Rating)'
And it works fine and matches the vega-lite example.
=> added binned scatterplot example from vega-lite

altair/vegalite/v2/examples/layered_heatmap_text.py
Tried to reproduce [this](https://vega.github.io/vega-lite/examples/layer_text_heatmap.html) plot from the vega docs. No idea how to do the final step, which is to change the text color of those rectangles with values greater than 100 to black.
=> Added layered heatmap + text example

altair/vegalite/v2/examples/bar_chart_with_highlight.py
I have having difficulty moving the text around in the plot, if anyone has ideas.
Here is the json from the vega-lite example:
{
"mark": {
"type": "text",
"align": "left",
"dx": 215,
"dy": -5
}
here is what it should look like:
https://vega.github.io/vega-lite/examples/layer_bar_annotations.html
=> added vega-lite example: bar chart with highlight

altair/vegalite/v2/examples/mean_overlay_over_precipitiation_chart.py
This is working and looks like:
https://vega.github.io/vega-lite/examples/layer_precipitation_mean.html
But, I can't seem to specify a size.
Obviously size = alt.Size(value = 3)) won't work because it requires a field.
In this example there is no field - we are using a calculated average and so we just need to set a static size.
I tried this: mark_rule(color = 'red', size = 3)
Which does not throw an error - but it also does not do anything (changing it to any number even 300).
=> added vega-lite example: mean overlay..bar line layered chart

altair/vegalite/v2/examples/grouped_bar_chart.py
Note, this uses a configuration line:
chart.config = {"view": {"stroke": "transparent"}, "axis": {"domainWidth": 1}}
Which is what was done in:
https://github.com/altair-viz/altair/pull/473/files
Jake, I did not know if you wanted this merged like you did the last one I just mentioned.  I am assuming that when these options show up in the api they will be here:
https://github.com/altair-viz/altair/blob/master/altair/vegalite/v2/api.py#L306
?
Asking as I am trying to dive a bit deeper and learn more.
=> added vega-lite example: grouped bar chart

altair/vegalite/v2/examples/one_dot_per_zipcode.py
Note,
I had to have the row in here:
zipcodes = zipcodes[5000:10000]
to limit the amount of data or I get the error:
MaxRowsError: The number of rows in your dataset is greater than the max of 5000
and searching in the repo I don't see a way to temporarily lift that restriction.
=> added example from vega-lite: one dot per zipcode

altair/utils/schemapi.py, altair/utils/tests/test_schemapi.py, altair/vega/v2/schema/core.py, altair/vega/v3/schema/core.py, altair/vegalite/v1/schema/channels.py, altair/vegalite/v1/schema/core.py, altair/vegalite/v2/api.py, altair/vegalite/v2/examples/scatter_matrix.py, altair/vegalite/v2/schema/channels.py, altair/vegalite/v2/schema/core.py, altair/vegalite/v2/schema/mixins.py, tools/generate_schema_wrapper.py
This PR adds a ``RepeatChart`` which allows repeated specs. For example:
```python
chart = alt.Chart(data.cars.url).mark_circle().encode(
alt.X(alt.repeat_column(), type='quantitative'),
alt.Y(alt.repeat_row(), type='quantitative'),
color='Origin:N'
).properties(
width=250,
height=250
).interactive()
alt.RepeatChart(chart).set_repeat(
row=['Horsepower', 'Acceleration', 'Miles_per_Gallon'],
column=['Miles_per_Gallon', 'Acceleration', 'Horsepower']
)
```
If you run this example live, you'll see that panning and zooming are linked across plots.
I'd initially thought we'd leave the repeat chart out of the top-level API, and instead focus on using Python-side loops to construct these kinds of specs. But in trying to duplicate some of the …
=> ENH: add RepeatChart & example

altair/utils/schemapi.py, altair/utils/tests/test_schemapi.py, altair/vega/v2/schema/core.py, altair/vega/v3/schema/core.py, altair/vegalite/v1/api.py, altair/vegalite/v1/schema/channels.py, altair/vegalite/v1/schema/core.py, altair/vegalite/v2/api.py, altair/vegalite/v2/examples/histogram.py, altair/vegalite/v2/schema/channels.py, altair/vegalite/v2/schema/core.py, altair/vegalite/v2/schema/mixins.py, tools/generate_schema_wrapper.py, tools/schemapi/codegen.py, tools/schemapi/schemapi.py
This PR adds code that validates Schema classes when they're instantiated, rather than only when they're converted to a dictionary. This significantly improves the user experience (see examples below)
The downsides of this change are:
- increased code complexity: much more is happening in ``SchemaBase`` to accomplish this, and to make certain this kind of validation is disabled in cases that it causes issues (for example, when you do something like ``encode(x='Origin')``, the encoding is not valid until you can add type information, which requires data that may not be available until the final serialization).
- chart creation is a bit slower, because lower-level parts of the chart are being repeatedly validated as the chart is built up. In practice, that's only really noticeable when …
=> Validate on instantiation

altair/utils/__init__.py, altair/utils/headless.py, altair/utils/importing.py, altair/utils/tests/test_importing.py
This allows you to save altair charts to PNG without going to the browser.
Dependencies can be installed this way:
```
$ conda install selenium PIL
$ conda install -c clinicalgraphics chromedriver
```
Then you can use the utility this way:
```python
import alt
chart = alt.Chart(...)  # make your favorite chart here
from altair.utils import save_spec
save_spec(chart.to_dict(), 'mychart.png')
```
Eventually we can make this more streamlined for the user (e.g. ``chart.save('mychart.png')``) but we'll have to figure out the dependency story... and I wanted to get the initial version of this utility committed so that I can use it to build docs for the release candidate.
=> Add programmatic export utility based on selenium and chrome-headless

altair/utils/schemapi.py, altair/vegalite/api.py, altair/vegalite/schema.py, altair/vegalite/v2/api.py, tools/schemapi/schemapi.py
This does two things:
- adds a custom exception that wraps ``jsonschema.ValidationError`` and provides tracebacks that are more useful for Altair specifications
- adds a ``validate='deep'`` option that triggers any time there is a validation error on a top-level object.
The result is friendlier tracebacks; for example (compare to #480):
```python
alt.Chart()
---------------------------------------------------------------------------
SchemaValidationError                     Traceback (most recent call last)
~/anaconda/envs/vega3/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj, include, exclude)
968 
969             if method is not None:
--> 970                 return method(include=include, exclude=exclude)
971             return None
972 …
```
=> ENH: wrap to_dict() tracebacks for more user-friendly errors

altair/utils/core.py, altair/vegalite/v2/api.py
This addresses #480, with a workaround of the issue in https://github.com/ipython/ipython/issues/11038
@ellisonbg – I'd appreciate your opinion on the approach I used here.
After this, the traceback in #480 looks like this:
```python
alt.Chart()
```
```python-traceback
---------------------------------------------------------------------------
SchemaValidationError                     Traceback (most recent call last)
~/github/altair-viz/altair/altair/vegalite/v2/api.py in to_dict(self, *args, **kwargs)
254         if dct is None:
255             kwargs['validate'] = 'deep'
--> 256             dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)
257 
258         if is_top_level:
~/github/altair-viz/altair/altair/utils/schemapi.py in to_dict(self, validate, …
```
=> Fix traceback when displaying chart with invalid spec

altair/expr/core.py, altair/expr/funcs.py, altair/expr/tests/test_expr.py, altair/utils/schemapi.py, tools/schemapi/schemapi.py
Previously there was a recursion error when calling the ``copy()`` method on ``expr`` objects, because they weren't being initialized properly.
=> BUG: fix isse with to_dict() in expressions

altair/vegalite/v2/api.py, altair/vegalite/v2/tests/test_api.py
This also makes ``facet()`` a method of ``Chart`` and ``LayerChart`` rather than a top-level function. While writing the docs for facet, it occurred to me that this is a more consistent API (it's similar to ``repeat``)
=> ENH: parse shorthand within alt.facet()

altair/vegalite/v2/api.py, altair/vegalite/v2/examples/choropleth.py
I modified the `transform_lookup` method to take a `from_` parameter. I also included an example of a choropleth map using the method. 
This is in response to #545
=> Modify transform_lookup to take from_ argument

altair/vegalite/v2/api.py
This addresses issue #586 
It turns out that all the transforms require the 'as' keyword argument [https://vega.github.io/vega-lite/docs/transform.html](https://vega.github.io/vega-lite/docs/transform.html).
I have added the 'as_' argument and error handling to be consistent with the changes in #580. I have also modified the transform_calculate function to make it as consistent as possible with the rest of the transforms.
=> Add as_ argument and handling to transform functions

altair/vegalite/v2/api.py
After #589, the auto-generated doctrings no longer match the actual arguments of the ``transform_*`` methods. This adds explicit docstrings to address that.
cc/@malramsay64
=> DOC: update docstrings for transform_* methods

altair/vega/v2/schema/core.py, altair/vega/v3/schema/core.py, altair/vegalite/v2/schema/core.py, tools/generate_schema_wrapper.py, tools/schemapi/codegen.py
Previously, reserved names were ignored in the docstring.
Now the docstring contains a ``Dict-only Attribute`` section that lists these.
=> DOC: adjust handling of reserved names in code generation

altair/utils/headless.py
On systems running on root (typical for many docker/CI set ups) Chrome fails with:
```
[0320/133959.828643:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180
```
This option allows headless chrome to run in such cases.
=> Allow chromedriver to work under the root user

altair/vega/v2/display.py, altair/vega/v3/display.py, altair/vegalite/v1/display.py, altair/vegalite/v2/display.py
cc/ @ellisonbg 
We've already had a couple questions from users who either forgot to run or didn't realize they had to run ``renderers.enable('notebook')`` to use Altair in the notebook.
This PR changes the default output for when rendering fails to a more helpful message with a link to the docs.
Please let me know if this looks OK – I'm not sure if there's anything I'm overlooking.
=> MAINT: add helpful message for when charts don't render

altair/utils/__init__.py, altair/utils/headless.py, altair/utils/savechart.py, altair/vegalite/v1/api.py, altair/vegalite/v2/api.py, altair/vegalite/v2/tests/test_api.py
This PR refactors the ``savechart`` code:
- move the bulk of the code to ``altair/utils`` and make library versions configurable
- change the ``headless`` code to output a mimetype representation, and leave the file saving to ``savechart``
This will allow us to trivially create PNG and SVG renderers for use in the case of large datasets cc/@ellisonbg
=> Refactor savechart

altair/utils/schemapi.py, altair/utils/tests/test_schemapi.py, altair/vega/v2/schema/core.py, altair/vega/v3/schema/core.py, altair/vegalite/v1/schema/channels.py, altair/vegalite/v1/schema/core.py, altair/vegalite/v2/schema/channels.py, altair/vegalite/v2/schema/core.py, altair/vegalite/v2/schema/mixins.py, tools/generate_schema_wrapper.py
These files contain unicode characters, because those characters are present in the vega
and vega-lite schemas. Python 3 defaults to UTF-8, but to make the library more broadly
compatible, it's useful to be explicit.
=> MAINT: add explicit utf8 coding for generated files.

altair/utils/display.py, altair/vega/v2/display.py, altair/vega/v2/schema/core.py, altair/vega/v3/display.py, altair/vega/v3/schema/core.py, altair/vegalite/v1/display.py, altair/vegalite/v1/schema/core.py, altair/vegalite/v2/display.py, altair/vegalite/v2/examples/tests/test_examples.py, altair/vegalite/v2/schema/core.py, tools/generate_schema_wrapper.py
This is necessary to work properly within Google's internal Colab deployment.
=> MAINT: use pkgutil rather than open() to access internal data files

altair/expr/tests/test_expr.py, setup.cfg
For reasons described in #705.
=> Ignore PEP8 errors E711 and E712

altair/utils/save.py, altair/vegalite/v1/api.py, altair/vegalite/v2/api.py
Per @jakevdp's request, to fix when he types 'eps' instead of 'svg'. 'eps' is removed with this pull request and replaced with 'svg'.
Fixes #722.
=> DOC: eps replaced with svg

altair/utils/data.py, altair/utils/tests/test_data.py, altair/vega/data.py, altair/vega/v2/__init__.py, altair/vega/v2/data.py, altair/vega/v3/__init__.py, altair/vega/v3/data.py, altair/vegalite/data.py, altair/vegalite/v1/data.py, altair/vegalite/v2/data.py, doc/user_guide/display.rst
This PR in combination with JupyterLab master (which should be released this week) fixed the path resolution issues of `to_json` and `to_csv`. Things should "just work" now with no extra path hacking in JupyterLab. All paths used by these data transformers are relative to the notebook. Other renderers such as ipyvega should now use this same approach. The key is that the notebook servers baseURL + `/files` + path of the notebook needs to be prefixed to the relative filename.
@jakevdp
=> Fix for `to_json` and `to_csv` path resolving

altair/__init__.py, altair/expr/__init__.py, altair/utils/__init__.py, altair/vega/__init__.py, altair/vega/v2/__init__.py, altair/vega/v2/schema/__init__.py, altair/vega/v3/__init__.py, altair/vega/v3/schema/__init__.py, altair/vegalite/__init__.py, altair/vegalite/v1/__init__.py, altair/vegalite/v1/schema/__init__.py, altair/vegalite/v2/__init__.py, altair/vegalite/v2/schema/__init__.py
Attached are a variety of fixes to manage PyFlakes violations in ``__init__.py`` files.
My reading of the library is that ``*``'s have been used in autogenerated modules to allow for a changing number of imports. To allow that to continue, I have exempted those files from PyFlakes inspection. If you'd prefer another approach, please let me know.
=> PyFlakes fixes to __init__.py files

.travis.yml
As recommended by the [TravisCI documentation](https://docs.travis-ci.com/user/caching/).
=> Cache pip dependencies on TravisCI for faster builds

altair/vegalite/tests/test_common.py, altair/vegalite/v1/api.py, altair/vegalite/v1/theme.py, altair/vegalite/v2/api.py, altair/vegalite/v2/tests/test_api.py, altair/vegalite/v2/theme.py
This addresses #718, adding support for switching between different chart themes.
For example, you can do
```python
import altiar as alt
alt.theme.enable('opaque')
```
and charts will now have a white background. Restore the default theme using
```python
alt.theme.enable('default')
```
Register custom themes using package entrypoints, or using, e.g.
```python
alt.theme.register('black-background', {'config': {'background': 'black'}})
```
and then enable it using
```python
alt.theme.enable('black-background')
```
@afonit – I'd love your input on what other themes we should make available by default. Currently I have "default" (set width and height) "opaque" (set width & height, and background color to white) and "none" (no config settings).
=> ENH: add theme support

altair/__init__.py, altair/_magics.py, altair/tests/test_magics.py, notebooks/MagicTest.ipynb
This changes things so users can use ``%load_ext altair`` in order to get the ``%%vega`` and ``%vegalite`` magics.
=> MAINT: use standard form for magics

altair/vegalite/v2/examples/world_projections.py
Some world map examples:
Note that graticules (lat/long lines) are not yet supported in Vega-Lite; see https://github.com/vega/vega-lite/issues/3337
=> Example: world map projections

setup.py
One of my colleagues installed Altair's new release candidate in Python 2.7 today. He had to install typing himself manually afterwards. I suspect this is because it was not added to setup.py.
=> Typing is in requirements.txt but not setup.py

altair/vegalite/v2/api.py, altair/vegalite/v2/examples/airports.py, altair/vegalite/v2/examples/choropleth.py, altair/vegalite/v2/examples/choropleth_repeat.py, altair/vegalite/v2/examples/one_dot_per_zipcode.py, altair/vegalite/v2/examples/us_state_capitals.py, altair/vegalite/v2/examples/world_projections.py
This adds a ``Chart.project`` method.
Before, applying a geographic projection required something like this:
```python
alt.Chart(data).mark_geojson().properties(
projection=alt.Projection(type='albersUsa', **kwds)
)
```
After this PR, the equivalent is
```python
alt.Chart(data).mark_geojson().project('albersUsa', **kwds)
```
=> ENH: add project() method to Chart

altair/utils/headless.py, altair/utils/save.py, altair/utils/tests/test_headless.py, altair/vegalite/v1/display.py, altair/vegalite/v2/display.py
This closes #441 by adding support for generating Vega spec's from vega
lite specs. It does this by using a headless browser (either chrome
or firefox) and loading a hosted version of the vega lite JS API.
To test this code install seleneium (`pip install selenium`) and
chromedriver (`brew cask install chromedriver`).
I implemented this with minimal changes to the existing API by adding
the `vega` format to the `spec_to_image_mimebundle` function. So it will
return a dictionary mapping the correct vega mimetype (as defined in
https://altair-viz.github.io/user_guide/display_frontends.html#renderer-api)
to the vega spec. It doesn't really make much sense to render vega to vega,
but this is currently supported as a no-op.
=> Add support for generating vega spec in headless

altair/sphinxext/schematable.py, altair/vega/v2/schema/core.py, altair/vegalite/v1/schema/channels.py, altair/vegalite/v1/schema/core.py, altair/vegalite/v2/schema/channels.py, altair/vegalite/v2/schema/core.py, tools/generate_schema_wrapper.py, tools/schemapi/codegen.py, tools/schemapi/decorator.py
Auto-generated docstrings in altair come from vega-lite, which uses markdown format. Sphinx does not properly render markdown from docstrings, and this leads to poorly formatted docs (see generated docs here: https://altair-viz.github.io/user_guide/API.html#module-altair)
This PR uses the [m2r](https://pypi.org/project/m2r/)  package to convert descriptions from markdown to RST in the process of generating Altair's code.
The results aren't perfect, but they're much better than before.
=> DOC: convert markdown docstrings to RST

altair/utils/data.py, altair/utils/display.py, altair/utils/html.py, altair/utils/plugin_registry.py, altair/utils/save.py, altair/utils/tests/test_plugin_registry.py, altair/utils/theme.py, altair/vega/display.py, altair/vegalite/data.py, altair/vegalite/display.py, altair/vegalite/tests/test_common.py, altair/vegalite/v1/__init__.py, altair/vegalite/v1/api.py, altair/vegalite/v1/data.py, altair/vegalite/v1/display.py, altair/vegalite/v1/theme.py, altair/vegalite/v2/__init__.py, altair/vegalite/v2/api.py, altair/vegalite/v2/data.py, altair/vegalite/v2/display.py, altair/vegalite/v2/tests/test_renderers.py, altair/vegalite/v2/theme.py
The goal of this work is to generalize the plugin interface to allow specification of additional options and/or metadata. See below for examples.
TODO list:
**External TODOS:**
- update ipyvega & jupyterlab to use ``embed_options`` from mimebundle metadata
---
This PR addresses (or partially addresses) #758, #742, #674, #673, and #240.
Most of this is internal reorganization, but there are a few primary user-side API enhancements that this PR introduces out-of-the-box.
With this PR, ``plugins.enable`` can optionally be used as a context manager to temporarily enable a specified plugin. For example:
```python
with alt.data_transformers.enable('json'):
do_something()  # executed with the json data transformer
do_something_else()  # executed with the previous data transformer
```
After this …
=> [MRG] Generalized Plugin Interface

altair/utils/display.py, altair/vega/display.py, altair/vega/v2/display.py, altair/vega/v3/display.py, altair/vegalite/display.py, altair/vegalite/v1/display.py, altair/vegalite/v2/display.py, altair/vegalite/v2/tests/test_renderers.py
I realized that mimebundle metadata should be passed with the same mimetype key as the main data. This PR fixes that.
It also cleans up the way that display functions are defined.
=> MAINT: fix handling of display metadata

altair/vegalite/v1/schema/channels.py, altair/vegalite/v2/api.py, altair/vegalite/v2/schema/channels.py, altair/vegalite/v2/tests/test_api.py, tools/generate_schema_wrapper.py
This is valid for the 'detail' and 'tooltip' encodings.
Fixes #825
=> ENH: support multiple fields for single encoding.

altair/utils/tests/test_utils.py, altair/vegalite/v2/examples/select_detail.py
Pandas 0.23 broke our tests. This makes them pass again.
=> BUG: fix examples & tests for pandas 0.23

altair/vegalite/v2/examples/layered_area_chart.py, altair/vegalite/v2/examples/normalized_stacked_area_chart.py, altair/vegalite/v2/examples/simple_stacked_area_chart.py, altair/vegalite/v2/examples/trellis_area.py
The same as the simple area chart example, but normalized. 
```python
source = data.unemployment_across_industries.url
alt.Chart(source).mark_area().encode(
x="date:T",
y=alt.Y("count:Q", stack="normalize"),
color="series:N"
)
```
=> DOC: Normalized Stacked Area Chart example

doc/user_guide/display_frontends.rst, doc/user_guide/faq.rst
This addresses a question that's come up multiple times in recent weeks.
=> DOC: add info about chart.serve() to the docs

altair/vegalite/v2/examples/parallel_coordinates.py
This adds an example of a  parallel coordinates chart:
```python
iris = data.iris()
iris_transformed = iris.reset_index().melt(['species', 'index'])
alt.Chart(iris_transformed).mark_line().encode(
x='variable:N',
y='value:Q',
color='species:N',
detail='index:N',
opacity=alt.value(0.5)
).properties(width=500)
```
=> DOC: add parallel coordinates example

altair/vegalite/v2/examples/scatter_with_histogram.py
Here's something else that took me a while to figure out yesterday, while I was trying to reproduce the [cross-highlights example](https://altair-viz.github.io/gallery/interactive_cross_highlight.html) on some of my own data: the behaviour is different when selecting a bar chart made from nominal categories to when there's a histogram binning step of quantitative information in the middle. 
I found that the only way I could make it work is by applying the `transform_bin` method to both charts. I don't know if that's the correct way to do it, or if there's a better way, but in either case, I thought it might be nice to have an example that shows this behaviour.
=> added example that links an interval selection in a histogram with a scatter plot

altair/vegalite/v2/examples/connected_scatterplot.py, altair/vegalite/v2/examples/multiple_marks.py, altair/vegalite/v2/examples/simple_line_chart_with_markers.py, doc/user_guide/encoding.rst
Added a simple example of a line chart with markers discussed in #876 
I can also update 
- [Connected Scatterplot (Lines with Custom Paths)](https://altair-viz.github.io/gallery/connected_scatterplot.html)
- [Multiple Marks](https://altair-viz.github.io/gallery/multiple_marks.html)
if you think using `mark_line(point=True)` is preferred to the layering method.
=> DOC: Add line chart with markers example

altair/utils/data.py, altair/utils/tests/test_data.py
Addresses #857
The idea here is that when someone uses the ``json`` or ``csv`` data transformer, the dataframes are stored on disk with a filename that is determined from the hash of the data contents. This prevents the proliferation of temporary files when doing a lot of plotting.
=> ENH: make to_json & to_csv transformers have deterministic filenames

altair/utils/core.py, altair/utils/tests/test_core.py, altair/vegalite/v2/api.py, doc/user_guide/transform.rst
Addresses #849 (cc/ @kanitw)
This changes the ``parse_shorthand`` utility so that it parses timeUnits as well as aggregates.
This allows compact expressions of time-binned encodings; e.g.
```python
alt.Chart(data.seattle_weather.url).mark_rect().encode(
x='date(date):O',
y='month(date):O',
color='max(temp_max):Q'
)
```
The old way of specifying this (which does still work) is:
```python
alt.Chart(data.seattle_weather.url).mark_rect().encode(
x=alt.X('date:O', timeUnit='date'),
y=alt.Y('date:O', timeUnit='month'),
color='max(temp_max):Q'
)
```
As an additional benefit, the new approach also makes more clear that the typecode refers to the aggregated data rather than to the input data, which was a confusion that came up several times for …
=> ENH: parse timeUnits in encoding shorthands

altair/vegalite/v2/api.py
Fixes #816 
This contains a backward incompatibility for anyone using the compound chart classes directly (e.g. ``FacetChart``, ``RepeatChart``) but none of our examples or documentation show this or recommend it.
The advantage is that it regularizes the API, and makes it easier to construct compound charts with data at the top level.
=> ENH: make data the first argument of all chart objects

altair/utils/core.py, altair/utils/tests/test_utils.py
JSON has no concept of infinity, so this is the best option to avoid breaking the data stream.
Currently, if dataframes contain infinities, it will result in blank charts.
After this change, the infinities will be treated as missing values.
=> BUG: convert inf to null in dataframe sanitization

CHANGES.md, altair/utils/headless.py, altair/utils/save.py, altair/vegalite/v1/api.py, altair/vegalite/v2/api.py, doc/user_guide/saving_charts.rst
=> ENH: add scale_factor argument to chart.save()

altair/utils/core.py, altair/utils/tests/test_utils.py
Previously all categoricals were converted to strings.
Now the data type is respected, and null values are appropriately handled.
=>  BUG: fix handling of categoricals

altair/utils/display.py
Adds a warning if people try to enable the ``vegascope`` renderer without the [vegascope](https://github.com/diana-hep/vegascope) package installed.
=> MAINT: add helpful error message for vegascope renderer

altair/vegalite/v2/examples/candlestick_chart.py, altair/vegalite/v2/examples/cumulative_wiki_donations.py, altair/vegalite/v2/examples/error_bars_with_ci.py, altair/vegalite/v2/examples/gapminder_bubble_plot.py
Markdown links are not properly rendered in the gallery (e.g. https://altair-viz.github.io/gallery/cumulative_wiki_donations.html). Also includes a minor typo fix.
=> markdown style links in the examples are changed to rst links.

altair/utils/data.py, altair/utils/plugin_registry.py, altair/utils/tests/test_plugin_registry.py, altair/vegalite/v2/api.py, altair/vegalite/v2/tests/test_api.py
With this change, you can run:
```
alt.data_transformers.enable(consolidate_datasets=True)
```
and then in all rendered charts, inline data will be replaced with named data and added to the top-level ``datasets`` attribute. This automatically assigns the name to any identical datasets.
This addresses the issue that typical usage patterns end up embedding multiple copies of the dataset within compound charts. I think that this consolidation behavior should probably be the default, but I'd like to get it in as an option to start with.
As an example, consider the following chart, using a standard concatenation pattern:
```python
data = pd.DataFrame({
'a': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
'b': [28, 55, 43, 91, 81, 53, 19, 87, 52],
'c': …
```
=> Toplevel datasets

doc/user_guide/configuration.rst
For #976.
This is beyond the scope of this patch, but I noticed that the automatically generated documentation for `configure_view` is a little confusing.
It describes the default of `strokeOpacity` as "The stroke opacity (value between [0,1]).  Default value: (none)." But an unconfigured chart does has a stroke. So how can the default be None?
=> DOC: Example of hiding the border using configure_view.

altair/utils/core.py
Fixes #1027 
@palewire – please confirm that this fixes your issue! I've run your example from #1027 with this change, and it seems to be working as expected:
```python
df = pd.read_json("https://raw.githubusercontent.com/datadesk/cpi/master/notebooks/last_13.json", dtype={"date_label": pd.np.datetime64})
alt.Chart(df).mark_bar().encode(
x=alt.X("date:O", timeUnit="yearmonth", axis=alt.Axis(format="%b %y")),
y="pct_change_rounded:Q"
)
```
=> Use ISO format for dates to prevent timezone issues

altair/vegalite/v2/examples/trellis_area_sort_array.py
Example of Trellis Area Chart with sort order.
```python
from altair.expr import datum
alt.Chart(data.stocks.url).transform_filter(
datum.symbol != 'GOOG'
).mark_area().encode(
x='date:T',
y='price:Q',
color='symbol:N',
row=alt.Row('symbol:N', sort=['MSFT', 'AAPL', 'IBM', 'AMZN']
)
).properties(height=50, width=400)
```
=> ADD: Trellis Area Sort Chart Example

doc/user_guide/encoding.rst
This branch adds a "Sorting Legends and Axes" section to the user guide. This is one of the to-dos in issue #1060  and was raised in #1059. 
The documentation adds two examples that show the various ways to sort [`ascending`,`descending`] and specifying an explicit order as well. 
In addition, the same example is expanded adding a color legend and sorting that as well. hope this helps. 
I will try to grab one of the other to-dos in #1060 as well.
=> Documentation of Sorting Columns and Legends

altair/vegalite/v2/api.py, altair/vegalite/v2/tests/test_api.py
=> BUG: preserve format and name keywords when consolidating InlineData

setup.py
Because of an oversight, ``altair/vega/v4/schema/vega-schema.json`` was not included in the version 2.2 package release. This PR fixes that, and should prevent this mistake in the future.
=> BUG: include schemas in package data

README.md
I'm not sure what you think is the right role of the slack channel but I thought it would be good to have the link in the readme.
=> Add link to altair slack

altair/utils/__init__.py, altair/utils/core.py, altair/utils/display.py, altair/utils/html.py, altair/utils/save.py, altair/utils/tests/test_html.py, altair/vega/display.py, altair/vega/v2/display.py, altair/vega/v3/display.py, altair/vega/v4/display.py, altair/vegalite/display.py, altair/vegalite/v1/display.py, altair/vegalite/v2/api.py, altair/vegalite/v2/display.py, altair/vegalite/v2/tests/test_api.py, altair/vegalite/v2/tests/test_renderers.py, requirements.txt, requirements_dev.txt
- adds ``alt.Chart.to_html()`` method
- adds Kaggle renderer, and refactors Colab renderer
- adds ability to specify whether html output is full or partial, as well as whether or not it uses require.js
- adds ``jinja2`` to the core requirements for better HTML templating
=> Refactor HTML output methods

altair/utils/mimebundle.py
simple fix to all saving png files in python 2.7 per https://github.com/altair-viz/altair/issues/994
=>  add python2 support for saving a chart as png 

altair/vegalite/v2/examples/aggregate_bar_chart.py, altair/vegalite/v2/examples/grouped_bar_chart.py, altair/vegalite/v2/examples/horizon_graph.py, altair/vegalite/v2/examples/layered_bar_chart.py, altair/vegalite/v2/examples/layered_heatmap_text.py, altair/vegalite/v2/examples/line_percent.py, altair/vegalite/v2/examples/natural_disasters.py, altair/vegalite/v2/examples/one_dot_per_zipcode.py, altair/vegalite/v2/examples/step_chart.py, altair/vegalite/v2/examples/trellis_area_sort_array.py, altair/vegalite/v2/examples/us_population_over_time.py, altair/vegalite/v2/examples/us_population_pyramid_over_time.py
A handful of examples in the gallery used imports like this:
```python
from altair.expr import datum
```
I changed them to use `alt.datum` instead.
I propose this patch because I think it will reduce the number of imports newbies need to learn and enforce consistency in our examples, which is a good thing in itself.
=> Removed datum imports from example gallery

altair/vegalite/v2/examples/filled_step_chart.py
One chart variation I find myself making occasionally is a step chart with its area filled in. I've added one as an example in this patch by making a few modifications to the existing step chart example.
=> DOC: Create Filled Step Chart example

altair/vegalite/v2/examples/slope_graph.py
The method for handling the x-axis layout offered by the Slope Graph example can be improved, I think, but substituting our handy dandy shorthand.
=> DOC: Trimmed slope_graph.py example

requirements.txt
see  https://ci.appveyor.com/project/ericpre/hyperspy-bundle/builds/19660402/job/gs9l31okjhplckur
=> "typing" package apparently creates issues if installed on Python3.7+

paper/paper.bib, paper/paper.md
A trivial grammar fix and some mildly pedantic bib fixes. Capitalization of proper nouns in titles and `@inproceedings` `booktitle` is necessary when using pandoc-citeproc (or biber, but not classic bibtex). I also populated additional fields (some used by APA style) for [this paper](https://dl.acm.org/citation.cfm?id=3025768).
=> JOSS paper/bib: minor edits

paper/paper.md
Commas separate an optional locator while semicolons separate distinct
references.  This is best documentation I'm aware of:
https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax
The previous formatting was incorrect:
=> JOSS paper: fix multiple citation

doc/user_guide/saving_charts.rst
Small typo Additinoally -> Additionally
=> DOC: fix typo in user guide

altair/utils/display.py, altair/vegalite/v2/tests/test_renderers.py
This adds a renderer method that makes it easier for the user to correctly specify options for vega-embed. Instead of, for example,
```python
alt.renderers.enable(embed_options={'renderer': 'svg', 'actions': False})
```
with this PR you can do
```
alt.renderers.set_embed_options(renderer='svg', actions=False)
```
with tab completion for the available options.
=> ENH: add renderer set_embed_options() method

altair/examples/error_bars_with_ci.py
IMHO, this is a not a traditional bar chart. Grouping it where we have it now has the potential to confuse readers.
=> DOC: Regroup error bars chart in the example gallery

altair/examples/beckers_barley_trellis_plot.py
Here's how Becker published [his own version of the trellis chart](https://hci.stanford.edu/courses/cs448b/papers/becker-trellis-jcgs.pdf).
I've modified our case study to bring it more in line.
```python
source = data.barley()
alt.Chart(source, title="The Morris Mistake").mark_point().encode(
alt.X(
'yield',
scale=alt.Scale(zero=False),
axis=alt.Axis(grid=False, title="Barley Yield (bushels/acre)")
),
alt.Y(
'variety',
sort=alt.EncodingSortField(field='yield', op='sum', order='descending'),
scale=alt.Scale(rangeStep=20),
axis=alt.Axis(title="", grid=True)
),
color=alt.Color('year:N', legend=alt.Legend(title="Year")),
row=alt.Row(
'site',
title="",
sort=alt.EncodingSortField(field='yield', op='sum', order='descending'),
)
)
```
=> DOC: Improved barley case study

altair/sphinxext/altairgallery.py
I tried a fresh doc build to see all of the changes that have happened recently. It threw a `keyerror: 'General'` when running `altairgallery.py`
I poked around to try to figure out what was going on. It seems that when populating the examples the default category was 'general' but that category has since been abandoned. 
I changed the default to be 'other charts' which fixed the error when building the docs. 
Not sure if that is the best solution but it's a start.
=> DOC: Change the default category to Other Charts

altair/examples/us_employment.py
I'm still not sure how to get the January bar on the left to start exactly where I'd like it, but here's a run at further developing this new dataset into a case study example.
```python
source = data.us_employment()
presidents = pd.DataFrame([
{
"start": "2006-01-01",
"end": "2009-01-19",
"president": "Bush"
},
{
"start": "2009-01-20",
"end": "2015-12-31",
"president": "Obama"
}
])
bars = alt.Chart(source, title="The U.S. employment crash during the Great Recession").mark_bar().encode(
x=alt.X("month:T", axis=alt.Axis(title="")),
y=alt.Y("nonfarm_change:Q", axis=alt.Axis(title="Change in non-farm employment (in thousands)")),
color=alt.condition(
alt.datum.nonfarm_change > 0,
alt.value("steelblue"), …
```
=> DOC: Added more fully developed us_employment case study

doc/user_guide/ecosystem.rst
pdvega is no under altair-viz. The old link was not working anymore.
=> DOC: Replace link of pdvega repo

altair/examples/line_chart_with_points.py, altair/examples/simple_line_chart.py
I was a little confused by the labels used on the simple line chart example. The label was `'sin(x)'` but then the equation was `sin(x / 5)`. I think it would make more sense just to have `'x'` and `'f(x)'` as labels. I modified the other example where this occurs.
=> DOC: Relabel line chart variable

altair/examples/trellis_scatter_plot.py
The current example is too wide and breaks out of the template. I'd also like to try to gradually standardize this section of examples to use a common local dataset. Cars seems like a good one we're already using in other examples, and it fits pretty well here.
=> DOC: Cleaned up trellis scatter example

doc/user_guide/data_transformers.rst
The example shows how the json data transformer can be used to store the
data files in a separate directory.
=> Add example of custom data transformer to docs

altair/examples/co2_concentration.py
Working backward from the [Vega-Lite docs](https://vega.github.io/vega-lite/examples/layer_line_co2_concentration.html), I recreated an example of Gregor Aisch's CO2 chart.
I suspect you might have thoughts about how to best format the window function. It was a first time writing one so I'm sure there is room for improvement.
```python
source = data.co2_concentration()
base = alt.Chart(
source,
title="Carbon Dioxide in the Atmosphere"
).transform_calculate(
year="year(datum.Date)"
).transform_calculate(
decade="floor(datum.year / 10)"
).transform_calculate(
scaled_date="(datum.year % 10) + (month(datum.Date)/12)"
).transform_window(
window=[
{'op': 'first_value', 'as': 'first_date', 'field': 'scaled_date'},
{'op': 'last_value', 'as': …
```
=> DOC: Added CO2 Concentration case study

altair/examples/weather_heatmap.py
I think a mistake was made in #1286 where the weather heat map was moved to the line chart section instead of the case studies.
=> DOC: Really move Seattle weather heatmap example into case studies

altair/examples/isotype_grid.py
Mirrors a [Vega-Lite example](https://vega.github.io/vega-lite/examples/isotype_grid.html) upstream.
```python
data = pd.DataFrame([dict(id=i) for i in range(1, 101)])
alt.Chart(data).transform_calculate(
col="ceil (datum.id/10)"
).transform_calculate(
row="datum.id - datum.col*10"
).mark_point(filled=True, size=50).encode(
x=alt.X("col:O", axis=None),
y=alt.Y("row:O", axis=None),
shape=alt.ShapeValue("M1.7 -1.7h-0.8c0.3 -0.2 0.6 -0.5 0.6 -0.9c0 -0.6 -0.4 -1 -1 -1c-0.6 0 -1 0.4 -1 1c0 0.4 0.2 0.7 0.6 0.9h-0.8c-0.4 0 -0.7 0.3 -0.7 0.6v1.9c0 0.3 0.3 0.6 0.6 0.6h0.2c0 0 0 0.1 0 0.1v1.9c0 0.3 0.2 0.6 0.3 0.6h1.3c0.2 0 0.3 -0.3 0.3 -0.6v-1.8c0 0 0 -0.1 0 -0.1h0.2c0.3 0 0.6 -0.3 0.6 -0.6v-2c0.2 -0.3 -0.1 -0.6 -0.4 -0.6z")
).properties(width=400, …
```
=> DOC: Simple Isotype grid example

doc/user_guide/interactions.rst
A couple of spelling errors (and a typo) I noticed when reading the documentation. I've prefixed the summary with _DOC_ because that seems to be a repository convention.
=> DOC: correct spelling errors

altair/utils/display.py, altair/utils/plugin_registry.py
In the most recent version of flake8, typing comments are flake-checked, so we need to update this here.
=> MAINT: fix flake8 errors in type comments

doc/user_guide/transform.rst
This is my attempt to address #1301. Although it's not comprehensive, I hope that is a foundation for future improvements.
There are two substantive commits. One replaces the window transform example (see issue and commit for my rationale). The second adds a table of window transform aggregation functions, from the Vega-Lite documentation.
Whilst I'd like to keep chipping away at #1301, I feel that it's better to open many smaller PRs early, rather than one large PR late. Doing so will also help me determine whether my writing/formatting style is consistent (or at least consistent enough) with other Altair committers.
=> Improve documentation for window transform? #1301

doc/user_guide/transform.rst
This example shows that aggregation functions aren't only for aggregate transforms. By using two aggregation functions within a window transform we are able to compute z-scores within a calculate transform.
See also: https://vega-js.slack.com/archives/C0NG6SXFX/p1548451285140300
=> DOC: Add window transform example

.travis.yml
jsonschema's 3.0 release introduces an incompatibility with the pytest version installed by default on travis. This should fix the issue.
=> MAINT: fix travis issue with jsonschema

doc/user_guide/ecosystem.rst
Hi, I updated broken links in the ecosystem documentation page.
I also wanted to mention https://github.com/Kitware/seaborn_altair but it is very similar to https://github.com/PythonCharmers/starborn (authors have discussed joining forces in [here](https://github.com/PythonCharmers/starborn/issues/1)).
=> DOC: update ecosystem

altair/examples/normed_parallel_coordinates.py
Add example for normalized parallel coordinates to demo `.transform_joinaggregate()` usage:
=> add example for normalized parallel coordinates

altair/examples/beckers_barley_wrapped_facet.py
Replicate of https://vega.github.io/vega-lite/docs/facet.html#facet-full to demo `columns` usage.  It's very similar from the original barley trellis plot, but the `columns` documentation is not ready now, so this example might be helpful.  Let me know if any modification is preferred to make it more useful.
=> example of wrapped facet

altair/utils/schemapi.py, tools/schemapi/schemapi.py
This has no impact on the typical user; these are methods I wish had existed when I was developing altair-transform.
=> MAINT: add convenience methods to SchemaBase

CHANGES.md, altair/examples/interactive_cross_highlight.py, altair/examples/interactive_layered_crossfilter.py, altair/examples/interval_selection.py, altair/examples/scatter_with_histogram.py, altair/utils/schemapi.py, altair/vegalite/v2/api.py, altair/vegalite/v3/api.py, altair/vegalite/v3/tests/test_api.py, doc/user_guide/compound_charts.rst, tools/schemapi/schemapi.py
This cleans up the syntax of ``alt.selection_*()``. The main effects are
- you no longer need to use ``selection.ref()`` when referencing the selection (e.g. as a scale domain). Concretely, if ``selection=alt.selection_interval()`` then ``alt.Scale(domain=selection.ref())`` can now be written ``alt.Scale(domain=selection)``.
- it's no longer possible to pass a selection directly as a property; it must be passed via the ``add_selection`` function
- it's no longer possible to use the addition operator to combine two selections; so, rather than ``chart.properties(selection=sel1+sel2)``, we instead do ``chart.add_selection(sel1, sel2)``.
=> Clean up alt.selection (fixes #1431)

altair/vegalite/v3/api.py, altair/vegalite/v3/tests/test_api.py
The selection counter was not being properly incremented, breaking charts with multiple selectors.
=> BUG: fix Selection counter issue

altair/examples/errorbars_with_ci.py, altair/examples/errorbars_with_std.py, altair/examples/interactive_brush.py, altair/examples/interactive_scatter_plot.py, altair/examples/multiline_tooltip.py, altair/examples/scatter_linked_brush.py, altair/examples/select_mark_area.py, altair/examples/selection_layer_bar_month.py, altair/examples/stem_and_leaf.py, altair/examples/us_state_capitals.py, altair/vegalite/tests/test_common.py, altair/vegalite/v3/tests/test_api.py, altair/vegalite/v3/theme.py
In Vega-Lite 2, tooltips would only be added to a chart if they were specifically listed in encodings.
Vega-Lite 3 changed this so that tooltips are shown unless explicitly disabled.
This uses a new theme argument (equivalent to ``chart.configure_mark(tooltip=None)``) to restore the previous behavior, in which tooltips are opt-in rather than opt-out.
=> MAINT: make tooltips opt-in

CHANGES.md, altair/vegalite/v3/api.py, altair/vegalite/v3/tests/test_api.py
In Altair 3, layered charts can have their own marks which are inherited by all layers.
This PR adds ``mark_*()`` methods to the layered chart to make this easier to use.
=> ENH: add mark_*() methods to layer charts

doc/user_guide/troubleshooting.rst
Would have been helpful to the user who asked this question: https://stackoverflow.com/questions/56152270/python-3-6-altair-chart-prints-object-not-graph
=> DOC: add non-notebook environments to display troubleshooting doc

altair/examples/ridgeline_plot.py
As discussed in #1524, using `mark_area` instead of `mark_line` ensures that the fill is between the line and the x-axis.
=> Use mark_area in ridgeline plot example

altair/vegalite/data.py, altair/vegalite/v2/tests/test_data.py, altair/vegalite/v3/api.py, altair/vegalite/v3/tests/test_data.py, doc/user_guide/faq.rst
=> Add disable_maxrows function & make serve() and save() respect data_transformer

altair/vegalite/v3/tests/test_theme.py, altair/vegalite/v3/theme.py
This PR adds support for vega themes. For example:
```python
alt.themes.enable('dark')
cars = data.cars()
alt.Chart(cars).mark_point().encode(
x='Horsepower',
y='Miles_per_Gallon',
color='Origin',
).interactive()
```
This requires your frontend to use the most recent release of vega-embed.
Fixes #781
=> ENH: support vega-themes

altair/examples/scatter_with_rolling_mean.py
I thought a nice addition to the examples would be one where a rolling mean is overlaid with a scatter plot, often used when visualizing dense time series.
=> DOC: Add rolling mean scatter plot example

doc/getting_started/installation.rst
I propose to add the following note in "Quick Start: Altair + Notebook" section:
> If you have multiple Python environments, you need to install the
> vega package in the Python environment that runs ipykernel *and*
> the Python environment that runs the Jupyter Notebook server.  You
> only need to install Altair in the Python environment that runs
> ipykernel.
=> Clarify that vega needs to be installed for server as well

doc/user_guide/encoding.rst
The [Selection Detail Example](https://altair-viz.github.io/gallery/select_detail.html#gallery-select-detail) does not actually use the detail encoding so I changed the example to [Ranged Dot Plot](https://altair-viz.github.io/gallery/ranged_dot_plot.html) which does.
=> DOC: Change detail encoding example

altair/vegalite/v3/api.py
Any time there is a rendering error Jupyter defaults to printing the chart repr. This can sometimes be _very_ long, and obscure the actual error. This change suppresses the full chart repr.
=> Truncate top-level chart repr

altair/examples/airport_connections.py
From the Vega-Lite examples: https://vega.github.io/vega-lite/examples/airport_connections.html
NOTE: I can't seem to get the tooltip to work on the points layer like in the Vega-Lite Example.
=> DOC: Add example for Connections Among U.S. Airports Interactive

altair/vegalite/v2/schema/channels.py, altair/vegalite/v3/schema/channels.py, altair/vegalite/v3/tests/test_api.py, tools/generate_schema_wrapper.py
=> BUG: properly propagate context in multiply-specified encodings

altair/utils/__init__.py, altair/utils/core.py, altair/utils/tests/test_core.py, altair/vegalite/v2/api.py, altair/vegalite/v2/schema/channels.py, altair/vegalite/v3/api.py, altair/vegalite/v3/schema/channels.py, tools/generate_schema_wrapper.py, tools/schemapi/codegen.py
=> BUG: fix encoding channel argument parsing

altair/expr/core.py, altair/vegalite/v3/api.py, altair/vegalite/v3/tests/test_api.py, doc/user_guide/interactions.rst
Addresses #1013 
This PR adds the ability to access selector values within filter & condition expressions; for example:
```python
import numpy as np
df = pd.DataFrame({
'xval': range(100),
'yval': np.random.randn(100).cumsum()
})
slider = alt.binding_range(min=0, max=100, step=1, name='cutoff')
selector = alt.selection_single(fields=['cutoff'], bind=slider, init={'cutoff': 50})
alt.Chart(df).mark_point().encode(
x='xval',
y='yval',
color=alt.condition(alt.datum.xval < selector.cutoff, alt.value('red'), alt.value('blue'))
).add_selection(
selector
)
```
=> ENH: add selector value access for expressions

altair/utils/core.py, altair/utils/tests/test_core.py
Currently Altair's type inference fails with pandas version 0.20.X (it works with older or newer versions)
Confirmed that this fix works with all pandas versions back to at least 0.14.X (and probably further, but I didn't check): https://colab.research.google.com/drive/1SaigNiN-W8DY54zzKoou0cPc5XvjxMSt#scrollTo=UyS-QGDzIQCL
Replaces #1610
=> BUG: make infer_dtype utility work with pandas 0.20

requirements_dev.txt
0.15.1 was released, so it should work properly now.
=> MAINT: unpin docutils in dev requirements

altair/utils/html.py, altair/vegalite/v3/display.py
This PR is to support Altair in Apache Zeppelin. I create a new render for Zeppelin. The changes I made in HTMLTemplate is especially for Zeppelin. Without this change. The rendering only works for the time, afterwards, I will get js error of `el is already defined`.
Here's the screenshot in Zeppelin.
=> Support Altair in Apache Zeppelin

altair/utils/core.py, altair/utils/data.py, altair/vegalite/v3/api.py, altair/vegalite/v3/tests/test_geo_interface.py, doc/user_guide/data.rst
I'm not sure if I've understood you correctly here: https://github.com/altair-viz/altair/issues/588#issuecomment-522193822
But in this PR I tried to integrate serialising data objects with a `__geo_interface__` attribute.
And it worked OK for Python packages that deal with geographical data types that support the `__geo_interface__`. I tried the packages `shapely`, `pyshp`, `geojson`, `geopandas`.
It works for:
* `InlineData`
* `json` data transformer and
*  `data_server` data transformer.
See animated gif:
After I got this working, I compared it to https://github.com/altair-viz/altair/pull/818/files, but the idea is very much the same. Maybe @iliatimofeev can shed a light on this proof of concept as well.
=> accept __geo_interface__ attribute as data

altair/vegalite/v3/api.py, altair/vegalite/v3/tests/test_api.py, doc/user_guide/data.rst
Fixes #1660 
cc/@jheer how does this API look to you?
=> Add API wrappers for data generators

altair/vegalite/v3/api.py, altair/vegalite/v3/tests/test_api.py, doc/user_guide/interactions.rst
This PR has still some issues, but it adds some documentation + inline example to compose multiple selections as discussed in https://github.com/altair-viz/altair/issues/1704.
I tried to emulate the Vega-Lite example from [here](https://vega.github.io/vega-lite/docs/selection.html#compose), but preferred to hold the ctrl-key or shift-key to separately initiate the selections.
I don't know how to make the following Vega-Lite example with bitwise operators work in Altair:
```
"selection": {"not": {"and": ["alex", "morgan"]}}
```
I tried some (eg. `~alex & ~morgan` and `~[alex & morgan]`), but got none working.
=> BUG: composing multiple selections

doc/user_guide/customization.rst
Hello,
This PR contains minor edits in the  "Customizing Visualizations" doc chapter (doc/user_guide/customization.rst).
First typo was a `:ref:` nested in an italic markup that didn't render. Proposed solution: paragraph erased and merged with the similar one at the end of the section.
Second typo was a missing space in an `.. altair-plot::` directive which prevented the plot to get rendered.
Finally, I've added a small enumeration to introduce the three subsection on configuration (global, local, and encoding channels). This is not related to the typos.
=> fix typos in the "Customizing Visualizations" doc chapter

altair/utils/core.py
Hi,
I'm not sure if this really counts as a typo. While reading through the source code I noticed this tiny missing ">" in a function docstring. Turns out it's the only occurrence of its kind in the whole codebase.
Hope this helps!
=> Missing character in util-core doc

altair/utils/html.py, altair/vega/v4/display.py, altair/vega/v5/display.py, altair/vegalite/v2/display.py, altair/vegalite/v3/display.py
This adds the ``html`` renderer to Altair. If you use
```python
alt.renderers.enable('html')
```
The chart will render correctly, with the correct versions of Vega/Vega-Lite/Vega-Embed, in a variety of frontends.
I have tested that this renderer displays charts correctly in Jupyter Notebook, JupyterLab, Colab, Kaggle, nbviewer, and nbconvert HTML, without the need for any separately installed frontend extensions.
The downside is that unlike the vega labextension and nbextension the HTML renderer loads JS resources from the web, and so it cannot be used offline.
=> ENH: add universal HTML renderer

altair/utils/schemapi.py, altair/vega/v4/schema/core.py, altair/vega/v5/schema/core.py, altair/vegalite/v2/api.py, altair/vegalite/v2/schema/core.py, altair/vegalite/v3/api.py, altair/vegalite/v3/schema/core.py, doc/user_guide/API.rst, tools/generate_schema_wrapper.py, tools/schemapi/codegen.py, tools/schemapi/schemapi.py
The set of schema definitions in Vega-Lite have a hierarchical structure, but up until now Altair's class structure constructed from them has been flat. This PR uses the structure declared by the schema definitions to infer a hierarchical structure for the classes, which simplifies instances of type checking within the API code.
=> Internal: add inheritance structure to core classes

altair/utils/schemapi.py, altair/utils/tests/test_schemapi.py, tools/schemapi/schemapi.py, tools/schemapi/tests/test_schemapi.py
=> ENH: support pickle and copy in schemapi

altair/vegalite/v4/display.py, altair/vegalite/v4/tests/test_renderers.py
This makes the html renderer the default. I have tested this in Jupyter Notebook, JupyterLab, nbconvert, and nbviewer. It should also work properly in hosted notebooks like zeppelin, colab, kaggle, and databricks.
The former default renderer now can be enabled using ``alt.renderers.enable('mimetype')`` (or equivalently, ``'jupyterlab'`` or ``'nteract'``.
=> V4: make HTML renderer the default

altair/examples/wilkinson-dot-plot.py
I noticed the link in the wilkinson example wasn't properly formatted.
=> DOC: Fix wilkinson link

doc/user_guide/transform.rst
Found a small typo while reading over the new transform docs
=> DOC: fix typo in transform guide

altair/_magics.py, altair/utils/core.py, tools/schemapi/tests/test_decorator.py
Cleaned up a few deprecation warnings I found when running `pytest`.
Specifically:
1. Added a `Loader` parameter when loading `yaml`
2. Changed `getargspec` to `getfullargspec` and the `keywords` attribute to `varkw`
3. Changed `import collections` to `from collections.abc import Mapping` and modified the corresponding `Mapping` calls.
=> Deprecation Warning Cleanup

altair/examples/bar_chart_sorted.py, altair/examples/beckers_barley_trellis_plot.py, altair/examples/top_k_items.py, altair/examples/top_k_letters.py
I read in `changes.rst` that now you can sort by an encoding channel directly. I thought a few of the examples could be refactored to reflect this. 
Note there were two places where I couldn't replace `EncodingSortField`
- in `beckers_barley_trellis_plot.py` it didn't seem to work with the row encoding. 
- in `sorted_error_bars_with_ci.py` I had trouble because the x encoding was being used twice. 
After going through this process I think the sorting documentation could use an update. Maybe I will make an issue.
=> DOC: refactor some examples which use EncodingSortField

doc/user_guide/marks.rst
This re-adds the image mark example from #1866 that was removed due to https://github.com/vega/vega/issues/2238 preventing the docs from building.
If the image is in the docs rather than the gallery, no thumbnail is required.
CC @eitanlees
=> DOC: add section on image mark

altair/examples/candlestick_chart.py
Something caught my eye today while browsing the website this morning
I think the candlestick example is incorrect. 
I wasn't quite sure why, but changing the encoding type from temporal `T` to ordinal `O` and removing the scale seemed to fix things. A few other cosmetic details were also changed
I am still unsure why the temporal encoding doesn't work. I tried `mark_bar(align='center')` but that didn't help.
A related issue is I don't like having to include the data. I might submit a PR to include an "Open High Low Close" data set into [vega-datasets](https://github.com/vega/vega-datasets) as it is a common dataset format.
=> DOC: fix candlestick example

altair/utils/display.py
=> BUG: use unique chart div ID for HTML renderer

doc/user_guide/transform/timeunit.rst
Changed yearmonthdatehoursseconds to yearmonthdatehours**minutes**seconds
=> Fix typo in available time units doc

doc/user_guide/customization.rst
When plots have categorical data on one or both axis, and when there are a lot of categories, the axis labels may not be useful.  So this is an easy way to remove them.
For this example, I'm just using the same plot from the above example.  If this is too contrived an example, I could come up with something more reasonable.
#1899
=> customization example - how to remove axis labels

altair/vegalite/v3/tests/test_api.py
All test conditions of vegalite/v3/test_api/test_save were previously failing when run. Determined that an open file descriptor automatically returned by tempfile.mkstemp() was blocking read/write access to temp file in question, preventing test from running nominally.
Added line to immediately close the file descriptor to resolve this; afterward all tests in vegalite/v3/test_api.py run and passed.
=> Fixed test_save by closing file descriptor

altair/vegalite/v4/tests/test_api.py
All test conditions of vegalite/v4/test_api/test_save were previously failing when run. Determined that an open file descriptor automatically returned by tempfile.mkstemp() was blocking read/write access to temp file in question, preventing test from running nominally.
Added line to immediately close the file descriptor to resolve this; afterward all tests in vegalite/v4/test_api.py run and passed.
=> Fix broken test: test_api.test_save()

altair/utils/core.py, altair/utils/tests/test_utils.py
Add support for the new dtypes in `utils.sanitize_dataframe` to solve #1922
- [nullable integer datatype](https://pandas.pydata.org/pandas-docs/version/0.25/whatsnew/v0.24.0.html#optional-integer-na-support) 
- [dedicated string dtype](https://pandas.pydata.org/pandas-docs/version/1.0.0/whatsnew/v1.0.0.html#dedicated-string-data-type)
=> Nullable integers and string dtype

tools/schemapi/utils.py
Fixes https://github.com/vega/vega-lite/issues/5838
Tested by running ``python tools/generate_schema_wrapper.py`` and seeing no change for vega-lite v4.0.0, and by running the same command with v4.1.1 and seeing that it executes without failure.
=> MAINT: call url decode definition names

altair/vega/v5/schema/core.py, altair/vegalite/v3/schema/core.py, altair/vegalite/v4/schema/core.py, tools/generate_schema_wrapper.py
I was looking through the schema generation code and realized that all schema objects share the same root schema, so it's less duplicative to implement it via inheritance.
This should have no user-visible impact.
=> MAINT: simplify generated schema definitions

doc/user_guide/compound_charts.rst
I found another place where the interval selection bug (https://github.com/altair-viz/altair/pull/1907) occurred.
=> DOC: fix vconcat example on compound charts guide

altair/utils/deprecation.py, altair/utils/display.py, altair/utils/tests/test_deprecation.py, altair/vegalite/v3/_deprecated.py, altair/vegalite/v4/api.py, doc/user_guide/display_frontends.rst, doc/user_guide/faq.rst
This removes references to the vegascope project in favor of the altair_viewer project, which we have more control over (usage of vegascope around altair package updates has been a challenge in the past)
This also deprecates the ``chart.serve()`` method, because the code in altair_viewer is much more robust and better tested.
=> ENH: add show() method & references to altair_viewer

altair/utils/html.py
Fixes #1984 
The fallback after ``getPreviousElementSibling`` is because in classic Notebook, the script is executed with ``"<head>"`` as the parent node, so the div cannot be located in this manner.
I've tested this in JupyterLab (with multiple views), Jupyter Notebook, Colab, and nbconvert HTML, all work correctly.
@jasongrout, please let me know if you see any issues with this.
=> BUG: html renderer: support multiple views in JupyterLab

.travis.yml, NOTES_FOR_MAINTAINERS.md, doc/getting_started/installation.rst, doc/releases/changes.rst, requirements.txt, setup.py
Following [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html)
This will also unblock a number of nice features, such as f-strings, type hints, code formatting with black, etc.
=> MAINT: bump minimum Python version to 3.6

altair/examples/tests/test_examples.py
This ensures that the examples do not lead to javascript errors.
=> TST: add render test for all examples

altair/_magics.py, altair/utils/data.py, altair/utils/tests/test_data.py, altair/vega/data.py, altair/vegalite/data.py, altair/vegalite/v3/api.py, altair/vegalite/v4/api.py, doc/user_guide/data_transformers.rst
These are functions from ``toolz`` that are exposed in altair's top-level namespace. This PR marks those functions deprecated, so that they can be removed in a future release.
=> MAINT: deprecate alt.curry and alt.pipe

altair/utils/display.py, altair/vegalite/v3/api.py, altair/vegalite/v4/api.py
Some non-standard Python kernels fail to pass ``include`` and ``exclude`` arguments when calling ``_repr_mimebundle_``. This causes issues like https://github.com/altair-viz/altair/issues/2042
This PR should fix the problem, without causing side-effects for standard kernels.
=> MAINT: provide default values for _repr_mimebundle_ include/exclude

.github/workflows/build.yml, .github/workflows/docbuild.yml
With the [0.3 release](https://github.com/altair-viz/altair_viewer/releases/tag/v0.3.0), this is no longer necessary
=> MAINT: remove altair_viewer dev install from CI scripts

altair/examples/bar_with_rolling_mean.py
```python
source = data.wheat()
bar = alt.Chart(source).mark_bar().encode(
x='year:O',
y='wheat:Q'
)
line = alt.Chart(source).mark_line(color='red').transform_window(
rolling_mean='mean(wheat)',
frame=[-9, 0]
).encode(
x='year:O',
y='rolling_mean:Q'
)
(bar + line).properties(width=600)
```
=> Added example of bar chart with rolling mean

altair/examples/line_with_log_scale.py
A new line chart example that shows how to set [a log scale](https://en.wikipedia.org/wiki/Logarithmic_scale).
```python
source = data.population()
alt.Chart(source).mark_line().encode(
x='year:O',
y=alt.Y(
'sum(people)',
scale=alt.Scale(type="log")  # Here the scale is applied
)
)
```
=> Added example with line chart on a logarithmic scale

doc/user_guide/customization.rst
The mentioned example is no longer a good example (due to a Vega-Lite update). Thus, the link was removed.
=> DOC: tiny update

README.md
The citation suggestion was missing volume, number, and pages. I
adjusted according to: https://joss.theoj.org/papers/10.21105/joss.01057#
PCCP was complaining about the lack page or volume number.
=> Fixed citation

altair/examples/line_chart_with_cumsum.py
```python
source = data.wheat()
alt.Chart(source).mark_line().transform_window(
sort=[{'field': 'year'}],
frame=[None, 0],
cumulative_wheat='sum(wheat)',
).encode(
x='year:O',
y='cumulative_wheat:Q'
).properties(width=600)
```
=> Added example of a cumulative line chart

altair/examples/scatter_linked_table.py
Since the contents of this repository are automatically generated, I hope this is the correct place to make this change.
=> Typo correction in scatter_linked_table

doc/user_guide/transform/density.rst
=> Typo correction (density)

doc/user_guide/compound_charts.rst
movies dataset column names have changed to remove the _ replaced by spaces. So the user guide compound chart is not rendering correctly.
=> compound chart changes due to movies dataset column name change

doc/user_guide/custom_renderers.rst, doc/user_guide/display_frontends.rst, doc/user_guide/troubleshooting.rst
This is based of my understanding of [your comment here](https://github.com/altair-viz/altair/issues/2311#issuecomment-705877316) and issue https://github.com/altair-viz/altair/issues/2234. If `'colab'` is the same as `'html'` I can change to reflect that.
close https://github.com/altair-viz/altair/issues/2234
=> Update renderer descriptions for 4.0 and fix mimebundle typo

altair/examples/binned_heatmap.py
I don't think this is needed is it? It seems to work for me without the column name.
=> Remove redundant column name

altair/sphinxext/altairplot.py
The methods ```add_stylesheet``` and ```add_javascript``` in sphinx are deprecated and have started to give warnings. Using Sphinx version 3.2.1 I get:
```../.tox/run/lib/python3.7/site-packages/altair/sphinxext/altairplot.py:327: RemovedInSphinx40Warning: The app.add_stylesheet() is deprecated. Please use app.add_css_file() instead.
app.add_stylesheet("altair-plot.css")
../.tox/run/lib/python3.7/site-packages/altair/sphinxext/altairplot.py:307: RemovedInSphinx40Warning: The app.add_javascript() is deprecated. Please use app.add_js_file() instead.
app.add_javascript(app.config.altairplot_vega_js_url)
../.tox/run/lib/python3.7/site-packages/altair/sphinxext/altairplot.py:308: RemovedInSphinx40Warning: The app.add_javascript() is deprecated. Please use app.add_js_file() instead. …
```
=> Switch to non-deprecated methods in sphinx extension

altair/utils/save.py, altair/vegalite/v4/tests/test_api.py
=> allow Paths in save()

doc/user_guide/marks.rst
Fixed a small mistake in user_guide/marks
- extent='max-min' is not a valid argument -> Changed to extent='min-max'
=> Docs: Flip extent='max-min' to extent='min-max'

altair/utils/data.py
Leaving it implied at pandas' [default of 10](https://github.com/pandas-dev/pandas/blob/5d65e0a3092f3c30169d0c0a3d0227e985104a56/pandas/io/json/_json.py#L55) makes the altair_data_server that uses this method drop numbers between 9.999e-16 and 5e-11, leading to unexpected and imo bad behavior like in https://github.com/altair-viz/altair_data_server/issues/45.
=> Force double_precision=15 in utils.data:_data_to_json_string

altair/examples/london_tube.py
This change will use the colors specified in `line_scale`. Previously `line_scale` was never used.
=> Use colors specified in line_scale

altair/expr/core.py, altair/expr/tests/test_expr.py, altair/vegalite/v3/api.py, altair/vegalite/v3/tests/test_api.py, altair/vegalite/v4/api.py, altair/vegalite/v4/tests/test_api.py
As reported in #2402 , we recently came up against an issue whereby Altair charts could not be deep-copied. The issue is that in three locations a `__getattr__` method is implemented in such a way that it returns a object for any named attribute. This is usually helpful, but it sometimes confuses Python when it coincides with a Python "magic" method/attribute (which are always of form `__<name>__`; and in this case in particular, `__deepcopy__` is looked up but then doesn't behave in the way `copy.deepcopy` expects.
This patch causes Altair to avoid returning generic objects as attributes for Python magic names, fixing this (and other similar) issue(s).
closes #2402
=> Avoid confusing Python by returning generic objects for magic attributes.

altair/examples/simple_scatter_with_errorbars.py
This is a fix to [the simple error bar example](https://altair-viz.github.io/gallery/simple_scatter_with_errorbars.html). Currently the marks extend beyond chart area, like this:
This changes it to:
Btw, I started trying to help out with some of the support related aspect by replying to Altair questions here and on SO, please let me know if you generally prefer to reply yourself instead.
I can also go through the GitHub issues and ping the authors to close the ones that are resolved (or close them myself if you would be ok with that), but since this would generate quite some noise in your inbox, I thought I would ask first if you would like me to do that or not.
=> Prevent marks from extending beyond the chart area in error bar example

doc/user_guide/marks.rst
I hope I'm not missing anything obvious, but it seems trail mark is missing from the [list of marks in the user guide](https://altair-viz.github.io/user_guide/marks.html).
=> DOC: add `mark_trail` to user guide's list of marks

altair/examples/bump_chart.py
I made a bump chart for the example gallery.  It's a mix of this Vega example [Bump Chart](https://vega.github.io/vega-lite/examples/line_bump.html), which I don't think has a direct analogue in the Altair gallery, and this example from the Altair gallery [Window Rank Line Chart](https://altair-viz.github.io/gallery/window_rank.html).
This is my first contribution (to any repository) so I'm very happy for any feedback.
=> Bump chart example

doc/user_guide/transform/filter.rst
There is a a typo in the [documentation](https://altair-viz.github.io/user_guide/transform/filter.html#user-guide-filter-transform) for `.filter_transform()` as  mentioned in #2434, where the description of a chart doesn't match the specification. 
The specification states "here we plot US population distributions for all data except the years 1950-1960...", but the code removes the years 1900-1950 with following filter:
```python
.transform_filter(
{'not': alt.FieldRangePredicate(field='year', range=[1900, 1950])}
)
```
At first, I had fixed the typo by changing the text to say "1900-1950".  But for some reason, I decided it seemed more reasonable to remove the years 1950-1960 rather than 1900-1950.
=> fixed typo in transform_filter documentation 

altair/examples/line_chart_with_datum.py, altair/examples/pacman_chart.py, altair/vegalite/v4/api.py
.cc @mattijn 
I think this is roughly what you had in mind in the previous discussion (https://github.com/altair-viz/altair/pull/2513#issuecomment-960643083). We may want a more sophisticated version of this rather than *always* adding empty data at the top level.
=> Inject empty data at top level for easier datum encodings

altair/utils/core.py
Fixes #2398. 
This PR introduces support for serialising pandas nullable data types for float data (`Float32Dtype` and `Float64Dtype`) that were [introduced](https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.2.0.html#experimental-nullable-data-types-for-float-data) in pandas 1.2.0.
```python
df = pd.DataFrame({'x': [1, 2, 3, 4, 5, 6, 7], 'y': [10, 30, None, 15, None, 40, 20]}, 
dtype=pd.Float32Dtype()) # pd.Float64Dtype()
alt.Chart(df).mark_line(point=True).encode(x='x', y='y')
```
=> support serializing nullable float data

doc/releases/changes.rst
I reviewed the merged PRs since 4.1 and these are the Altair-specific changes I think might be helpful to include in the release notes.
=> Update changelog with PRs merged since the 4.1 release

doc/Makefile
- change tabs to spaces for compatibility with BSD Make
- change `make clean` to a safer command (cf. https://github.com/sphinx-doc/sphinx/issues/8437)
=> MAINT: fix some issues with the Makefile

altair/sphinxext/altairgallery.py, altair/sphinxext/altairplot.py
Closes #2550 
This adds a `:strict:` option to the altair sphinx extension. When set, it ensures that the documentation build fails when a code snippet can't be run. This is meant to prevent code snippets in the documentation from going stale. It is less restrictive than building the documentation with `-W` because warnings for other reasons won't cause the build of the documentation to fail.
=> Add strict option to sphinx extension

doc/user_guide/transform/regression.rst
I assume the addition in the exponential regression is a mistake and instead should be calculated as y = a * e^(b * x), which is also what can be found on the respective vega lite doc page: https://vega.github.io/vega-lite/docs/regression.html where it appears that the same correction was comitted due to a PR by @jakevdp [44123d888fff30c9d975b16f219d63c94e20ede2](https://github.com/vega/vega-lite/pull/5742/commits/44123d888fff30c9d975b16f219d63c94e20ede2)
Similarly, also in some of the other equations there were some typos to be fixed.
=> docs: correcting regression equations

.github/workflows/lint.yml, altair/utils/tests/test_plugin_registry.py, doc/requirements.txt
- Pin mistune since newer versions raise an error. It appears to be unmaintained https://github.com/miyakogi/m2r/issues/66
- Show which files fail black linting by running `black --diff` in the action workflow.
- Fix spacing around exponent operator to pass black linting
=> MAINT: Fix GH actions issues

.github/workflows/build.yml, .github/workflows/docbuild.yml
These pip installs were added in #2528 for installing the dev version of altair viewer. As per https://stackoverflow.com/questions/70663523/the-unauthenticated-git-protocol-on-port-9418-is-no-longer-supported, git will only support secure links in its build files since recently
=> MAINT: Update actions' links to use https

CONTRIBUTING.md
Just noticed a few things in the contributing guideline as I was making my recent PRs.
=> DOCS: Clarify steps in the contributing guidelines

.github/workflows/build.yml, .github/workflows/docbuild.yml, altair/vegalite/v5/api.py
Deprecation warnings do not display for me in the notebook; I think we have to use the special `AltairDeprecationWarning` or the decorator (as is done for 'show' and 'serve'). After this change I get the expected output when trying to use deprecated functionality:
=> MAINT: Make sure that deprecation warnings are displayed

.github/workflows/build.yml, .github/workflows/docbuild.yml
Altair's doctests are currently failing due to a deprecation in Selenium 4.3.0 which is a dependency of `altair-saver` (as reported in https://github.com/altair-viz/altair_saver/issues/104). Until there is a new release of `altair-saver` that addresses this (maybe with https://github.com/altair-viz/altair_saver/pull/105), this PR make sure we can run doctests by pinning the version of `selenium`. 
There will likely still be confusion among people who use the altair-saver library directly until it sees a new release since selenium 4.3.0 seems to be the default version installed with `altair-saver` currently.
=> Pin selenium to avoid doctest breakage from deprecation

altair/examples/us_population_over_time.py
This proposal tidies up one of our case studies so it is polished and better ready for publication.
Before:
After:
=> Tidy up U.S. Population by Age and Sex case study

altair/examples/natural_disasters.py
=> Tidy natural_disasters.py example

altair/sphinxext/altairplot.py, altair/sphinxext/schematable.py, altair/utils/tests/test_mimebundle.py, doc/user_guide/display_frontends.rst
There are small typos in:
- altair/sphinxext/altairplot.py
- altair/sphinxext/schematable.py
- altair/utils/tests/test_mimebundle.py
- doc/user_guide/display_frontends.rst
Fixes:
- Should read `required` rather than `requred`.
- Should read `temporary` rather than `temporay`.
- Should read `aspects` rather than `spects`.
- Should read `render` rather than `rendeer`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

doc/user_guide/data.rst
Fixed a formatting error within the documentation (user_guide -> data.rst).
Deleted the point after "Pandas" so as to make it consistent with the writing style of the other lists inside the same document.
Although I did not make any code changes, this change passes all tests, and I also followed the black formatting step.
=> formatted rst list correctly

altair/examples/line_chart_with_custom_legend.py, doc/user_guide/encoding.rst
Replicated [this](https://vega.github.io/vega-lite/docs/aggregate.html#example-labeling-line-chart) example from vega-lite's site.
The motivation for this is #2645, however I don't know whether to
* leave it as an example for it to be used in the gallery (and be referenced in the [aggregation functions table](https://joelostblom.github.io/altair-docs/user_guide/encoding.html#aggregation-functions)), or
* put it directly under the [Aggregate Transforms](https://joelostblom.github.io/altair-docs/user_guide/encoding.html#aggregation-functions) section, the same way that vega-lite's site does.
=> Added argmax example

altair/utils/schemapi.py, doc/user_guide/API.rst, tools/schemapi/schemapi.py
Improvement on #2670 -- see summary and discussion there
=> use 'UndefinedLike = Any' as the type hint

altair/examples/empirical_cumulative_distribution_function.py
I added a simple example for an eCDF plot as I agree with #2661 that it is helpful to show some simple statistical visualisations that users might know from other libraries such as seaborn (.[ecdfplot](https://seaborn.pydata.org/generated/seaborn.ecdfplot.html))
=> Add gallery example for empirical cumulative distribution function

altair/examples/image_tooltip.py
I can add a section in the userguide after I hear back regarding my VL PR here https://github.com/vega/vega-lite/pull/8048, but I think mentioning the reserved field name needed to render images is good for now.
close #2474
=> Clarify that a special field name is required to render images in tooltips

.github/workflows/build.yml, .github/workflows/docbuild.yml, altair/examples/tests/test_examples.py, altair/utils/mimebundle.py, altair/utils/tests/test_mimebundle.py, doc/user_guide/saving_charts.rst
This PR adds support for saving Altair charts to SVG and PNG static images using the [VlConvert](https://github.com/vega/vl-convert) Python package.
See https://github.com/altair-viz/altair/issues/2662 (opened by @mcp292) for some background on the need for a simpler method for exporting charts as static images.
See https://medium.com/@jonmmease/introducing-vlconvert-c763f0076e89 for background on how VlConvert works, and how it is able to avoid the need for external dependencies like selenium or Node.js.
Example:
```
$ pip install vl-convert-python
```
```python
chart = alt.Chart(data.cars.url).mark_point().encode(
x='Horsepower:Q',
y='Miles_per_Gallon:Q',
color='Origin:N'
)
chart.save('chart.svg')
chart.save('chart.png', …
```
=> Integrate vl-convert for saving to svg and png

doc/user_guide/data.rst, doc/user_guide/marks/index.rst
This PR is linked to this merged PR https://github.com/altair-viz/altair/pull/2607. 
Few changes in the index structure, so the marks also appear in the sidebar.
=> Include marks in sidebar/TOC

altair/vegalite/v5/api.py
Fix https://github.com/altair-viz/altair/issues/2708.
This PR let the default projection within `.project()` define by Vega-Lite instead of Altair.
Default projection in Vega-Lite is `equalEarth`.
=> use default projection from vegalite

doc/requirements.txt, doc/user_guide/data.rst, doc/user_guide/marks/geoshape.rst, doc/user_guide/marks/index.rst
Same as https://github.com/altair-viz/altair/pull/2688, but from direct fork from altair repo. Like this it should be easier to stay in-sync.
When I try to build the docs locally I get the following error:
```cmd
-> saving /Users/mattijnvanhoek/mattijn/altair/doc/_images/scatter_linked_table.png
/Users/mattijnvanhoek/miniconda3/share/vega-lite-cli/node_modules/vega-lite/build/vega-lite.js:40
n = p.length;
^
TypeError: Cannot read properties of undefined (reading 'length')
```
I don't think it is related to this PR, but I like to test locally. @joelostblom, did you face this issue before?
=> Geoshape docs revamp 5.0

CONTRIBUTING.md
Previously, contributing md asked to install "requirement_dev.txt"
but the repo actually contains a requirements_dev.txt file:
=> Fix missing 's' from filename in quick start

altair/utils/schemapi.py, doc/user_guide/API.rst, tools/schemapi/schemapi.py
Fix #2714.
Change from:
```python
UndefinedLike = Any
Undefined: UndefinedLike = UndefinedType()
```
to:
```python
Undefined: Any = UndefinedType()
```
=> Revert undefinedlike

doc/user_guide/saving_charts.rst
Fixes two small formatting issues on the "Saving charts" doc page
=> Fix some formatting issues

doc/user_guide/data.rst, doc/user_guide/interactions.rst, doc/user_guide/times_and_dates.rst, doc/user_guide/transform/aggregate.rst, doc/user_guide/transform/bin.rst, doc/user_guide/transform/calculate.rst, doc/user_guide/transform/density.rst, doc/user_guide/transform/filter.rst, doc/user_guide/transform/flatten.rst, doc/user_guide/transform/fold.rst, doc/user_guide/transform/impute.rst, doc/user_guide/transform/joinaggregate.rst, doc/user_guide/transform/loess.rst, doc/user_guide/transform/lookup.rst, doc/user_guide/transform/pivot.rst, doc/user_guide/transform/quantile.rst, doc/user_guide/transform/regression.rst, doc/user_guide/transform/sample.rst, doc/user_guide/transform/stack.rst, doc/user_guide/transform/timeunit.rst, doc/user_guide/transform/window.rst
I'd suggest to remove 'Transform' from the titles of the transform pages. The navigation bar looks much cleaner this way, especially now that we also have a page for every mark. This is also in line with the vega-lite docs. There are also two other smaller commits in this PR.
=> Improve documentation titles

altair/utils/mimebundle.py
As per the discussion in https://github.com/vega/vl-convert/issues/31, vl-convert is not currently working when the altair data server is enabled. As it seems like it is not straightforward to fix this on the vl-convert side of things, the workaround suggested here makes sure that the default transformer is enabled when using vl-convert for saving. cc @jonmmease
=> Make vl-convert saving work when the data server is enabled

altair/sphinxext/altairplot.py
This adds a toggle to hidden code snippets as discussed in #2720. The main reason we want this is to be able to hide the verbose parameter code by default but show it on demand for interested readers. Live docs here https://joelostblom.github.io/altair-docs/user_guide/times_and_dates.html
There are currently only two other pages that use the `:hide-code:` tag and neither of them suffer from having the toggle added in my opinion:
=> Add toggle to hidden code snippets

RELEASING.md, altair/_magics.py, altair/tests/test_magics.py, altair/vegalite/api.py, altair/vegalite/tests/test_common.py, altair/vegalite/v5/data.py, altair/vegalite/v5/theme.py, doc/_static/chart.html, doc/user_guide/display_frontends.rst, doc/user_guide/internals.rst, doc/user_guide/saving_charts.rst
I grepped the repo for `v4` and noticed a few places where I think it should be replaced with `v5`. I ran this locally with the updated tests in https://github.com/altair-viz/altair/pull/2576 and there are no failures introduced.
=> MAINT: Update from v4 to v5 in some additional files

doc/user_guide/customization.rst, doc/user_guide/data.rst, doc/user_guide/data_transformers.rst, doc/user_guide/display_frontends.rst, doc/user_guide/encoding.rst, doc/user_guide/importing.rst, doc/user_guide/internals.rst, doc/user_guide/times_and_dates.rst
Most of the changes are smaller updates. Most noteworthy is the move of the "Note on browser compatibility" section in "Times and Dates" to the bottom of that page. I still think it's great that its documented but for most users this is not relevant anymore as all modern browsers are now es6 compatible for quite a while, see [https://caniuse.com/\?search\=es6](https://caniuse.com/%5C?search%5C=es6)
=> Various smaller updates to documentation (harmonizing title cases, vega version numbers, browser compatibility, ...)

.github/workflows/build.yml, setup.py
Altair works without issues for me under 3.11 so I added 3.11 in the build GH workflow and the classifier for then Python package.
=> Run tests with Python 3.11

altair/examples/dendrogram.py
I added an example to plot dendrogram following the example shown [here](https://scikit-learn.org/stable/auto_examples/cluster/plot_agglomerative_dendrogram.html). Please review when you have time. Thanks.
=> DOC: add dendrogram example

doc/user_guide/encodings/channel_options.rst
Addressing https://github.com/altair-viz/altair/issues/2604#issuecomment-1366163307
Good catch @mattijn! I just checked and x and y offset channels do not accept any additional arguments, see https://github.com/altair-viz/altair/blob/fbd4f7bac5392b76e439fc3c58dd1b1476343c3e/altair/vegalite/v5/schema/core.py#L9883
I clarified in the introduction that only some channels take additional options.
=> Clarify that not all channels accept additional options

doc/_static/custom.css, doc/conf.py
Fix for #2775.
Unrelated to this but I also hid the `rtd-footer-container` element which created a vertical scrollbar in the primary sidebar on the left side even if it's not needed, i.e. on larger screens.
Before:
After:
=> Fix docs for mobile devices

.github/workflows/build.yml, .github/workflows/docbuild.yml, .github/workflows/lint.yml
Fixes #2777. @mattijn I can't find the warning you describe in #2776. Where was that raise? This PR updates all github actions to their newest versions so that warning might disappear as well.
=> Update github actions

altair/utils/html.py, altair/vegalite/v5/api.py
Like https://github.com/altair-viz/altair/pull/2262, this PR removes the duplicate /, but from the `base_url` instead of the `HTML_TEMPLATE`.
=> enh: remove slash from base_url instead of html_template

Makefile, altair/vegalite/v3/tests/test_api.py, altair/vegalite/v4/tests/test_api.py, altair/vegalite/v5/tests/test_api.py
If vl-convert-python is installed and altair_saver is not, `test_save` failed. For v3 and v4 this was probably introduced with the addition of vl-convert-python, for v5 it is related to #2784. Probably didn't pop up previously as all contributors had altair_saver installed anyway.
=> Fix altair test save if vl-convert-python is installed and altair_saver is not

.github/workflows/build.yml, altair/examples/tests/test_examples.py, altair/utils/tests/test_mimebundle.py, altair/vegalite/v3/tests/test_api.py, altair/vegalite/v4/tests/test_api.py, altair/vegalite/v5/tests/test_api.py, pyproject.toml
Extended the build workflow as suggested by @mattijn here https://github.com/altair-viz/altair/pull/2786#issuecomment-1368090897. Fixed another bug in the process when vl-convert-python was not installed.
I did not mark the rendering of the gallery examples to png for rerunning as that test takes quite some time and I don't think it is necessary to rerun it as this is about converting the examples, not about the behaviour of Altair if one of the engines is not installed.
=> Run tests for both save engines altair_saver and vl-convert-python

altair/utils/schemapi.py, altair/vegalite/v5/schema/channels.py, tools/generate_schema_wrapper.py, tools/schemapi/tests/test_schemapi.py
Fix https://github.com/altair-viz/altair/issues/2802.
This PR modifies the `generate_schema_wrapper.py` so the generated test file is placed in the `tests/utils/` folder. 
I had to change the test file to use absolute imports instead of relative imports as it is moved.
I also ran the `generate_schema_wrapper.py` and `generate_api_docs.py` thad leads to the update of two auto-generated files (utils/schemapi.py and channels.py)
=> Modify generator to move autogenerated test to tests folder

Makefile
Prior to changing this command in #2774, it already had the `--check` argument. This argument makes sure that the status is returned and therefore that the command fails if files would be formatted. I think removing it was unintentional (the reasoning in https://github.com/altair-viz/altair/pull/2774#discussion_r1060521819 was around adding `--diff --color` and not removing `--check`). I prefer if the command fails, else you need to scroll through the console output of pytest to get to the output of black to see the outcome.
=> Add --check to black test command

altair/vegalite/v5/api.py, tests/vegalite/v5/tests/test_layer_props.py
Reading through the old discussions, these properties in subcharts for a LayerChart were the cause of one of the biggest issues in updating to Vega-Lite version 5.
=> Add test for layer properties

.github/workflows/docbuild.yml, CONTRIBUTING.md, sphinxext/altairgallery.py, tests/examples_arguments_syntax/__init__.py, tests/examples_methods_syntax/__init__.py
VlConvert PNG export does not support the [Isotype Emoji](https://altair-viz.github.io/gallery/isotype_emoji.html), so it wasn't suitable as a full drop-in replacement for altair_saver when building docs on CI.
This PR is trying out an idea I had this morning. Interested to hear what folks think.
This PR updates the docs pipeline slightly to support using SVG image thumbnails for select examples (only the isotype_emoji example for now).  Since VlConvert's SVG export of the isotype_emoji example works fine, this makes it possible to use VlConvert to build all of the images in the docs.
I also updated the docs CI job to use VlConvert.
=> docs: Use SVG thumbnail for emoji example and use VlConvert to build docs on CI

altair/utils/display.py, altair/utils/schemapi.py, tests/utils/tests/test_schemapi.py, tools/schemapi/schemapi.py, tools/schemapi/tests/test_schemapi.py
Closes #2800
Tested with jsonschema 4.17.3 (newest) and 3.0.0 (minimum requirement). I had to introduce `$schema` in the test schemas as well so that it takes the same validator for the tests as when validating against the latest vega-lite schema.
=> Dynamically determine jsonschema validator

altair/utils/html.py, altair/utils/save.py, tests/vegalite/v5/tests/test_api.py
This includes the Vega/Vega-Lite/Vega-Embed JavaScript source in the exported html file so that it works offline.  The logic is ported from altair_saver.
See https://github.com/altair-viz/altair/issues/2765
**Note:** Like altair_saver, this pulls the JavaScript source from the `altair_viewer` package. In the future we could talk about whether to include the JavaScript bundles in Altair itself to avoid this dependency.
=> Add inline argument to chart.save() for html export

altair/utils/schemapi.py, altair/vegalite/v5/schema/channels.py, tests/utils/tests/test_schemapi.py, tools/generate_schema_wrapper.py, tools/schemapi/schemapi.py, tools/schemapi/tests/test_schemapi.py
Fixes #2497. CC @joelostblom. It can be verified by using the example code in the mentioned issue.
=> Remove side-effects of calling EncodingChannelMixin.to_dict

tests/vegalite/v5/tests/test_params.py
@joelostblom @mattijn Do these look like the sort of tests we would like for testing the new parameter syntax?  If this looks like the right spirit, I will add more, probably mostly based off the Vega-Lite documentation and the Altair documentation.
By the way @mattijn, I played around with adding property setter syntax like `alt.param().bind(slider)`, but I don't think it's a good idea at this stage.  There's already a lot of custom code related to these parameters (for example `__getattr__` defined [here](https://github.com/altair-viz/altair/blob/af756e9a9549b2bf0f88685d2f93e6224665bf18/altair/vegalite/v5/api.py#L216-L224)) and adding another layer of customization on top of it felt like it was getting overly difficult to maintain.
=> WIP Parameter tests

altair/utils/schemapi.py, tools/schemapi/schemapi.py
Resolves #2819. 
`SchemaBase.__dir__` was introduced in this commit https://github.com/altair-viz/altair/commit/d450c9963fc0943fe871e11d6d387d3143eb6b98 to enable tab completion for the attributes stored in `_kwds`. This makes sense as `SchemaBase` overwrites `__getattr__` so that you can access an attribute `x` which is stored in `_kwds` with `obj.x`. However, I don't think it was intended for that commit to remove all other attributes, especially on top-level objects, from tab completion. This PR adds back the original attribute list from `__dir__` + the attributes stored in `_kwds`.
With this PR:
```python
cars = data.cars.url
scatter = alt.Chart(cars).mark_point().encode(
x='Weight_in_lbs:Q',
y='Horsepower:Q',
color='Origin:N') …
```
=> Add missing object attributes to __dir__

.github/workflows/build.yml, .github/workflows/docbuild.yml, doc/getting_started/installation.rst, doc/requirements.txt, requirements_dev.txt
Moving `altair_viewer` into `requirements_dev.txt` as starting with https://github.com/altair-viz/altair/pull/2807 it needs to be installed to run the tests. Usually, it is installed anyway if someone has `altair_saver` installed but as this is no longer the norm for developers due to the recommendation in `CONTRIBUTING.md` to use `vl-convert-python`.
=> Clean up development and documentation requirements

doc/user_guide/customization.rst, tests/examples_methods_syntax/iowa_electricity.py
For #2748 and #2195
I also added the same example to the Iowa case study
=> Add title section to customization page

altair/utils/schemapi.py, tools/schemapi/schemapi.py
Fixes the bug reported in #2850. Both `enable_debug_mode` and `disable_debug_mode` previously set `DEBUG_MODE` to `True`.
=> Fix disable_debug_mode

doc/user_guide/configuration.rst
The configuration page in the documentation was missing a few `configure_` methods which were added in more recent vega-lite releases. With this PR, all `configure_` methods are documented.
=> Add documentation for remaining config methods

altair/utils/schemapi.py, doc/releases/changes.rst, tools/schemapi/schemapi.py
Fixes #2857 for a 4.2.2 release. CC @mattijn. I already added a changelog entry but without release date. I think it makes sense to release this as soon as possible if you find the time.
Tests pass against the following jsonschema versions which cover the range which is relevant for Altair:
* 3.0 (minimum version required by Altair)
* 4.0
* 4.4
* 4.5
* 4.16.0
* 4.17.3 (newest version)
* 4.17.3 with all format checks installed (this caused the original issue which was already fixed in Altair v4.2.1)
The `FORMAT_CHECKER` attribute on jsonschema validators was introduced in [version 4.5 of jsonschema](https://github.com/python-jsonschema/jsonschema/releases/tag/v4.5.0). Therefore, the compatibility looks as follows:
* Altair 4.2.0 works with jsonschema >=3,<4.17 (just tested this locally to …
=> Fix incompatibility with jsonschema < 4.5

.github/workflows/lint.yml, altair/vegalite/v5/api.py, pyproject.toml, requirements_dev.txt, tests/utils/tests/test_utils.py, tools/schemapi/utils.py
The new release 23 of black also brings some slight changes to the code style, see [here](https://black.readthedocs.io/en/stable/change_log.html#id1). Currently, the black linting workflows on GitHub fail as it installs black 23 but the code base is not yet formatted according to the new rules. This blocks any new or recently changed PRs such as #2846.
This PR:
* Applies those minimal formatting changes so that the black check passes again
* Restricts black to <24 so that this does not happen again in a year (major releases happen beginning of a year)
* Adapt the black target versions to the Python versions which are supported by Altair (3.7-3.11). This is somewhat unrelated to the issue and does not have any effect on the formatting but I thought it's nice to keep this up-to-date. …
=> Reformat code base with black version 23 and restrict version

tools/generate_schema_wrapper.py
The current importing behaviour in the `tools` scripts has some inconsistencies which this PR tries to address. These issues were partially discovered in #2814.
The statement `import generate_api_docs` was previously at the top of `generate_schema_wrapper.py`. In `generate_api_docs.py`, one of the first statements is the import of Altair -> Altair got imported before `generate_schema_wrapper` can update the vegalite files. This was presumably not a big issue so far as this script is usually run multiple times anyway and so the api docs were updated eventually.
This PR solves this by moving the `import generate_api_docs` statement at the end of the `main` function in `generate_schema_wrapper.py`.
If you execute `python tools/generate_api_docs.py` then Python correctly uses Altair from the …
=> Fix Altair import in tools scripts

doc/user_guide/large_datasets.rst
First off, thanks to @binste for including VegaFusion in the new Large Datasets documentation page added in https://github.com/altair-viz/altair/pull/2755.
This PR updates that section with some additional information now that  [VegaFusion 1.0](https://vegafusion.io/posts/2023/2023-01-21_Release_1.0.0.html) is out.
In particular, I want to encourage people to try the VegaFusion mime renderer first, as this provides benefits for the vast majority of Altair charts without requiring a Jupyter Widget extension.
Thanks!
=> Update Large Datasets documentation with VegaFusion 1.0 information

tools/schemapi/tests/test_schemapi.py
In #2842 I applied this change in `tests/utils/tests/test_schemapi.py` instead of `tools/schemapi/tests/test_schemapi.py`. This fixes it so that `python tools/generate_schema_wrapper.py` again runs through without any changes.
=> Apply minor code formatting change in tools script

tests/tests/test_examples.py
In another PR, a change was causing the `test_render_examples_to_chart` test to fail, but I had a hard time locating which specific example was failing.  This PR is an attempt to report the filename.
I tested this PR by temporarily adding an error to one of the example files (I used `:ON` rather than `:O` for an encoding type shorthand).  This is what was reported to me by VS Code:
=> Report filename of failing test

altair/utils/schemapi.py, tests/utils/tests/test_schemapi.py, tools/schemapi/schemapi.py, tools/schemapi/tests/test_schemapi.py
Addresses https://github.com/altair-viz/altair/pull/2568#discussion_r1096814378
Works already well but I'll still want to
=> Use most specific class possible in schema validation errors

doc/conf.py
This PR adds an announcement to the documentation page mentioning:
> This website is for Vega-Altair v5 (release candidate). Visit the [Vega-Altair v4 homepage](https://altair-viz.github.io/altair-viz-v4/) for previous release documentation.
It looks as follow.
I think we will need this at least temporarily.
=> Add announcement to docs

.github/workflows/build.yml
`altair_saver` in currently not maintained and its status is fragile. Since npm 9 has become default in Github Actions our tests are not passing anymore. See also https://github.com/altair-viz/altair_saver/issues/113 & https://github.com/altair-viz/altair_saver/pull/116.
Luckily `vl-convert` ([docs](https://github.com/vega/vl-convert#python)) is running already parallel to `altair_saver` in our Github Actions as it is a near complete alternative.
This PR comment out the part where `altair_saver` is used within Github Actions in the `build.yml` until `altair_saver` is getting maintenance support again.
=> exclude `altair_saver` in `build.yml` as Github Actions tests are not passing anymore

altair/utils/schemapi.py, tests/vegalite/v5/tests/test_api.py, tools/schemapi/schemapi.py
Follow up on #2522. @mattijn @jbloom I believe this resolves #2879.
=> Remove the automatic sort of categoricals for channels that do not support sorting

altair/utils/data.py, altair/vegalite/v5/api.py, doc/releases/changes.rst, doc/user_guide/data.rst
Based on the discussion in https://github.com/altair-viz/altair/issues/2868, this is an attempt to provide modest support for specifying data as a Polars DataFrame.  We do not convert to a pandas DataFrame, so at this point, the encoding type (e.g., `"Q"`, `"N"`, ...) needs to be specified explicitly.  (My reasoning is that it would be easier to add type inference later than to take it away.)
Example:
```
import polars as pl
df = pl.DataFrame(
{
"A": [1, 2, 3, 4, 5],
"cars": ["beetle", "audi", "beetle", "beetle", "beetle"],
"optional": [28, 300, None, 2, -30],
}
)
alt.Chart(df).mark_bar().encode(
x="A:O",
y="optional:Q",
color="cars:N"
)
```
=> Support DataFrame Interchange Protocol (allow Polars DataFrames)

tests/utils/tests/test_schemapi.py, tools/schemapi/tests/test_schemapi.py
Fixes #2894. They switched to `https` and removed the `#` for the `2020-12` schema
=> Fix wrong json schema url in a test

tools/generate_schema_wrapper.py
#2841 Introduced a change here https://github.com/altair-viz/altair/commit/c3f93f072266dc885174124c010422842d223e4e#diff-ff5209c42c54727d16bcb580e10a0b8973304e32333df10d4362b7d4deaefcb6R73 which needs to be applied in the tools script, else it gets overwritten during schema generation. CC @ChristopherDavisUCI, maybe you can quickly double-check if this looks good.
=> Apply minor change from #2841 in correct tools script

doc/conf.py
I think we need some instructions in the docs on how to install the release candidate as `pip install altair` will still install version 4, see https://jugmac00.github.io/til/how-to-install-release-candidates/. CC @mattijn What do you think of this? Had to shorten the existing text to make room for the pip install command.
I did not modify the pip install command on the Installation page as I maybe the announcement is enough and easy to spot and remove once version 5 is out but not sure.
=> Add instructions on how to install release candidate

altair/vegalite/v5/schema/channels.py, altair/vegalite/v5/schema/core.py, tools/generate_schema_wrapper.py, tools/schemapi/codegen.py, tools/schemapi/utils.py
Some attributes on classes are missing descriptions in the docstrings, see for example [`columnPadding` for `alt.Legend`](https://github.com/altair-viz/altair/blob/master/altair/vegalite/v5/schema/core.py#L6808):
```python
...
clipHeight : anyOf(float, :class:`ExprRef`)
columnPadding : anyOf(float, :class:`ExprRef`)
columns : anyOf(float, :class:`ExprRef`)
...
```
These descriptions are then also missing in the documentation as the API references are generated based on these docstrings, see [altair.Legend](https://binste.github.io/altair-docs/user_guide/generated/core/altair.Legend.html):
Due to this, I find myself often having to go to the [vega-lite docs](https://vega.github.io/vega-lite/docs/legend.html#symbol-layout) to find out what an attribute means. However, the description shown …
=> Add missing attribute descriptions

altair/utils/schemapi.py, altair/vegalite/v5/api.py, altair/vegalite/v5/schema/channels.py, altair/vegalite/v5/schema/core.py, doc/getting_started/starting.rst, doc/user_guide/configuration.rst, tools/schemapi/codegen.py, tools/schemapi/schemapi.py
With the addition of method-based attribute setting in #2795, Sphinx started generate the documentation differently for the encoding channels. The documentation for attributes is now the first sentence of the documentation which is defined by `_PropertySetter`:
This is much less informative then what is in the docstring of `altair.X` and which would be shown otherwise:
```python
Attributes
----------
shorthand : string
shorthand for field, aggregate, and type
aggregate : :class:`Aggregate`
Aggregation function for the field (e.g., ``"mean"``, ``"sum"``, ``"median"``,
``"min"``, ``"max"``, ``"count"`` ).
**Default value:** ``undefined`` (None)
**See also:** `aggregate <https://vega.github.io/vega-lite/docs/aggregate.html>`__
documentation.
axis : anyOf(:class:`Axis`, None)
An object …
```
=> Rename 'Attributes' to 'Parameters' to fix documentation formatting

altair/utils/core.py, altair/vegalite/v5/api.py, altair/vegalite/v5/schema/mixins.py, tools/generate_schema_wrapper.py
replaces: https://github.com/altair-viz/altair/pull/2610
fix: https://github.com/altair-viz/altair/issues/2608
@binste, I build the docs, but I could not find the tables of the screenshots in #2610, not sure where I should be able to see changes.
=> Docstring links class transform and mark methods

tools/generate_schema_wrapper.py
CC @joelostblom, no worries!  Moved a change introduced in https://github.com/altair-viz/altair/commit/389b87b7152381530d03e1ced319851da9e3a053#diff-ff5209c42c54727d16bcb580e10a0b8973304e32333df10d4362b7d4deaefcb6 to the schema generation so that `generate_schema_wrapper` again produces no changes if run against current files.
=> Move change introduced in #2824 to tools script

altair/expr/core.py, altair/expr/funcs.py, altair/utils/deprecation.py, altair/utils/display.py, altair/utils/execeval.py, altair/utils/plugin_registry.py, altair/utils/schemapi.py, altair/utils/server.py, altair/vegalite/v5/api.py, altair/vegalite/v5/schema/channels.py, altair/vegalite/v5/schema/mixins.py, altair/vegalite/v5/theme.py, tests/utils/tests/test_core.py, tests/vegalite/v5/tests/test_geo_interface.py, tools/generate_schema_wrapper.py, tools/schemapi/codegen.py, tools/schemapi/schemapi.py, tools/schemapi/utils.py
Small maintenance change. Only removes inheritance of `object` for all classes as this was only necessary to maintain compatibility with Python 2. In Python 3, it does not matter if `object` is specified or not and we can therefore remove it. See https://stackoverflow.com/a/45062077
=> MAINT: Remove inheritance from object for classes

altair/__init__.py, altair/vegalite/v5/api.py
Addresses #2692.
Adds more complete docstrings and signatures for parameter creation functions.  Also deprecates `selection` (in favor of `selection_point` and `selection_interval`).
Although this is primarily about documentation, the signatures were changed, so it is worth checking this carefully.  I did go through the examples [here](https://joelostblom.github.io/altair-docs/user_guide/interactions.html) and they seem to still be working.
This parameters portion of Altair has more customization and divergence from Vega-Lite (I gave one example in https://github.com/altair-viz/altair/issues/2692#issuecomment-1436026066), so these changes will not automatically be updated if changes happen in the Vega-Lite schema.  If anyone sees a more robust way to accomplish this, please let me know or …
=> Update parameter docstrings and signatures

tests/utils/tests/test_schemapi.py
test_schema_validator_selection currently only passes for jsonschema >= 4 as it uses jsonschema draft 202012 which was introduced in jsonschema 4. With this change, the test should pass for all versions of jsonschema which are supported by Altair. Tested against versions 3, 4, and 4.17.3. Issue was brought up in https://github.com/altair-viz/altair/discussions/2599#discussioncomment-5091891.
=> Fix test_schema_validator_selection for jsonschema<4

altair/utils/plugin_registry.py
Fixes deprecationwarning discussed in https://github.com/altair-viz/altair/discussions/2599#discussioncomment-5113306. I used the same approach as they use in SQLAlchemy https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/util/compat.py#L139 which should provide the broadest possible compatibility by relying on the new `select` interface if it is present and else fall back on the old `get`, independent of if the standard library or `importlib_metadata` is used. CC @mattijn. Don't see any deprecation warnings related to this anymore for any Python version we test against.
=> Fix deprecation warning for SelectableGroup in Python 3.7

altair/vegalite/v5/theme.py
Adds missing themes from https://github.com/vega/vega-themes to Altair. Tested all 3.
=> Add vega themes 'excel', 'googlecharts', 'powerbi'

doc/getting_started/installation.rst, doc/getting_started/project_philosophy.rst
Fixes rendering of 2 links which are currently displayed as:
=> Docs: Fix formatting of 2 links

.github/workflows/build.yml
Closes #2906. Tested that it works on another branch in my forked repo, see the failed workflow [here](https://github.com/binste/altair/actions/runs/4330777174/jobs/7562209179):
Tests for this PR fail right now because test_schemapi.py is not "clean" as I added some modifications in the wrong place. Will fix this in another PR.
=> Fail build workflow if generate_schema_wrapper produces changes

doc/getting_started/installation.rst
In my experience, many newbies are thrown by the $ and think they have to type it themselves.
=> Remove $ from bash examples on installation page

altair/vegalite/v5/schema/channels.py, tools/generate_schema_wrapper.py, tools/schemapi/codegen.py, tools/update_init_file.py
This improves on the existing and very nice implementation done by @ChristopherDavisUCI.
* Parse nested anyOf definitions which were so far represented as a single entry with non-specific `**kwds`.
* I also added types for the items in lists, so instead of a generic `list` type hint we get more specific ones such as `List[str]`. Also works for altair classes.
* Furthermore, it type hints enums as [literals](https://mypy.readthedocs.io/en/stable/literal_types.html). This tells a type checker that only the specified values are accepted. Also helpful in VS Code:
All of the above changes together turn this:
```python
def sort(self, **kwds) -> 'Angle':
```
into this
```python
def sort(self, _: List[float], **kwds) -> 'Angle':
...
@overload
def sort(self, _: List[str], **kwds) -> 'Angle':
... …
```
=> Type hints: Improve for encoding channel attributes

altair/utils/mimebundle.py, altair/utils/save.py
Fixes #2953. See that issue for the related discussion. This PR moves the context manager added in #2724 into the `save` function so that it's already used when converting the chart to a dictionary. For all other lines, only the indentation changed.
=> Temporarily use default data transformer while saving a chart

doc/getting_started/installation.rst
This is of course subjective but my take is that introducing the dependencies list at this point is too much to throw at a total n00b and not really what they're on the page to get. I propose cutting it.
=> Cut dependencies from installation page

doc/index.rst
Does it need to be some prominent? Why not put it after summarizing the project for newbies?
=> Move disclaimer to the bottom of the index page

doc/getting_started/overview.rst, doc/getting_started/project_philosophy.rst
These edits correct the formal name of the project to the new Vega-Altair style and move the origin of the name to this space, where it seems more appropriate to me.
=> Consolidate naming history into overview

doc/_static/altair-gallery.css
This is what we have now:
Here's how this change should turn out:
=> Reduce line-height in the gallery thumbnail headlines

doc/user_guide/data.rst
Pandas is listed first in the list. That's good enough, I think.
=> Trim that eliminates redundancy

altair/vegalite/v5/api.py
Fix for https://github.com/altair-viz/altair/issues/3024.
Now the following spec:
```python
iris = data.iris.url
alt.Chart(iris).mark_point().encode(
alt.X(alt.repeat("column"), type='quantitative'),
alt.Y(alt.repeat("row"), type='quantitative'),
color='species:N'
).properties(
width=200,
height=200
).repeat(
row=['petalLength', 'petalWidth'],
column=['sepalLength', 'sepalWidth']
).interactive().to_dict()
```
Returns
```python
{'config': {'view': {'continuousWidth': 300, 'continuousHeight': 300}},
'repeat': {'column': ['sepalLength', 'sepalWidth'],
'row': ['petalLength', 'petalWidth']},
'spec': {'data': {'url': 'https://cdn.jsdelivr.net/npm/vega-datasets@v1.29.0/data/iris.json'},
'mark': {'type': 'point'},
'encoding': {'color': {'field': …
```
=> include underscore after view

altair/vegalite/v5/api.py, tests/vegalite/v5/test_params.py
Fix https://github.com/altair-viz/altair/issues/2849.
- In the `LayerChart` the params of the subcharts are combined, see: https://github.com/altair-viz/altair/blob/master/altair/vegalite/v5/api.py#L2978
- Currently the `view` for these params is populated here: https://github.com/altair-viz/altair/blob/master/altair/vegalite/v5/api.py#L3272. Around here  is a loop on the `subcharts`, as far as I can see, they are not aware of being in a `RepeatChart`.
- But once we reach the `RepeatChart`, we are aware that it is a `LayerChart`, see: https://github.com/altair-viz/altair/blob/master/altair/vegalite/v5/api.py#L2664.
- At this place we also define the view names for the repeat. We can adjust the code here to accommodate for the required behavior.
With this PR we include the `spec` as …
=> include view definitions for a layercharts containing a repeat + toplevel selection parameter

doc/releases/changes.rst, pyproject.toml
Fix #3038.
This PR increases the minimum required version of jsonschema to be `4.0.1` or higher.
=> Increase minimum required jsonschema (`>=4.0.01`) 

doc/user_guide/marks/geoshape.rst
This PR change:
```python
fp = gpd.datasets.get_path('naturalearth_lowres')
gdf_ne = gpd.read_file(fp)  # shapefile
```
into:
```python
url = "https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_countries.zip"
gdf_ne = gpd.read_file(url)  # zipped shapefile
gdf_ne = gdf_ne[["NAME", "CONTINENT", "POP_EST", 'geometry']]
```
As the `datasets` module of the `geopandas` package is deprecated.
I select a subset of used columns as the original file has more than 160 columns.
=> geopandas.datasets is deprecated

pyproject.toml
Currently, when I install altair, I get a couple of extra files in my site-packages directory:
```
python -m env .env
pip install altair
cat .env/lib/python3.11/site-packages/README.md
cat .env/lib/python3.11/site-packages/LICENSE
cat .env/lib/python3.11/site-packages/pyproject.toml
```
These are all altair files. I think these files shouldn't be there 😉 
This PR removes them.
Note: I'm no hatch expert, so I don't fully understand what the benefit of adding these files in `tool.hatch.build` is.
=> Remove extra files in site-packages from wheel

.github/workflows/build.yml
Closes #2801. I tested that the validation fails if I remove the `--disable-formats uri-reference` flag.
Thanks again @sirosen!
=> Add validation of Vega-Lite schema itself

doc/_static/altair-gallery.css, doc/_static/custom.css, doc/_static/theme_overrides.css, doc/case_studies/exploring-weather.rst, doc/getting_started/overview.rst, doc/index.rst, doc/user_guide/api.rst, tools/generate_api_docs.py
The current homepage looks empty on larger screens:
In this PR, I increased the size of the gallery (inspired by the [VL docs](https://vega.github.io/vega-lite/) and added cards with short descriptions about the main sections in the documentation (inspired by the [pandas docs](https://pandas.pydata.org/docs/). You can see the result [here](https://binste.github.io/altair-docs/) or in the screenshots below:
Large screen (27inch 2560x1440):
Laptop (13inch 2560x1664):
Mobile (iPhone SE emulation):
=> Documentation: Improve homepage

altair/vegalite/v5/api.py, tests/test_examples.py
Fixes #3067. When reconstructing a layered chart which has `height`or `width` defined on the top-level with `from_dict`, the code so far checked that the layers have that property set to `Undefined` or to the same value as the layered chart itself. However, it's often the case that the layers don't have the property set at all -> This fix handles those cases.
I also added a test to run a to_json and from_json roundtrip for all examples in the gallery so that we can hopefully catch future regressions to this functionality. I checked that these tests would have caught the bug reported in #3067.
@mattijn Would be great if this fix can still make it into 5.0.1 in case you or someone else has the time to review it.
=> Fix bug in reconstructing layered charts with from_json/from_dict

altair/utils/schemapi.py, altair/vegalite/v5/api.py, tools/schemapi/schemapi.py, tools/update_init_file.py
This PR explicitly specifies and documents the accepted arguments for `to_dict` and `to_json` on top-level chart objects (e.g. `Chart`, `LayerChart`, ...). Previously, these methods used `args` and `kwargs`. This improves the documentation for users, allows us to type hint the arguments, and it unblocks https://github.com/altair-viz/altair/pull/3071#discussion_r1208617735 where it is currently unclear how to best add an additional documented keyword argument `format`.
This might break existing code in case a user passes an unused argument, e.g. `to_dict(this_argument_is_not_used=1`). However, that seems acceptable to me as I don't think it was the intended behavior to allow for arbitrary arguments.
cc @jonmmease. 
Maybe someone else could review it as well. Just in case I'm missing an …
=> Explicitly specify arguments for to_dict and to_json methods for top-level chart objects

tests/examples_arguments_syntax/ridgeline_plot.py, tests/examples_methods_syntax/ridgeline_plot.py
The method-based example did not render properly. The first commit fixes these issues. Closes #3079
In the second commit, I changed the alignment of the months from:
to:
=> Fix ridgeline example

altair/vegalite/v5/display.py, doc/user_guide/display_frontends.rst
Resolves #3070. I updated the documentation which is linked from the error message. This should help users figure out what to do in case they use a Jupyterlab or notebook version which does not support the VL 5 mimetype renderer.
=> Improve troubleshooting docs regarding Vega-Lite 5

.gitignore, pyproject.toml
By switching to `extend-exclude`, black respects gitignore, see https://black.readthedocs.io/en/stable/usage_and_configuration/file_collection_and_discovery.html#gitignore
=> MAINT: Gitignore venv folders and use gitignore for black

tests/examples_arguments_syntax/wheat_wages.py, tests/examples_methods_syntax/wheat_wages.py
Fixed appearance of the Wheat and Wages case study (see Chart below):
As mentioned in #2966 by @joelostblom I oriented myself at the [Vega-Lite example](https://vega.github.io/vega-lite/examples/wheat_wages.html).
Additionally there are some minor code formatting changes introduced (in line with pep8) caused by black's autoformatting.
=> Fixed Wheat and Wages case study

.github/workflows/build.yml, altair/utils/_vegafusion_data.py, altair/utils/core.py, altair/utils/data.py, altair/utils/execeval.py, altair/utils/plugin_registry.py, altair/vegalite/v5/compiler.py, altair/vegalite/v5/data.py, altair/vegalite/v5/display.py, altair/vegalite/v5/schema/channels.py, altair/vegalite/v5/theme.py, doc/releases/changes.rst, pyproject.toml, tools/generate_schema_wrapper.py, tools/update_init_file.py
Python 3.7 is [end-of-life as of 27.06.2023](https://devguide.python.org/versions/). Many other packages (e.g. [Streamlit](https://docs.streamlit.io/library/changelog), [python-jsonschema](https://github.com/python-jsonschema/jsonschema/releases/tag/v4.18.0), ...) have already dropped support for it in minor releases and I'd recommend to do the same to simplify maintenance. Users with 3.7 can still install Altair 5.0.1 which has been a rather stable release so far.
=> Drop support for Python 3.7 which is end-of-life

altair/utils/_transformed_data.py, tests/test_transformed_data.py
Addresses https://github.com/hex-inc/vegafusion/issues/354 on the Altair side. Port to VegaFusion will be done by @jonmmease.
=> Add support to transformed_data for reconstructed charts (with from_dict/from_json)

tests/examples_arguments_syntax/diverging_stacked_bar_chart.py, tests/examples_methods_syntax/diverging_stacked_bar_chart.py
I added @jonmmease 's implementation of the percentage calculation (https://github.com/altair-viz/altair/issues/3101) to the [diverging stacked bar chart example](https://altair-viz.github.io/gallery/diverging_stacked_bar_chart.html).
It was mentioned in  (https://github.com/altair-viz/altair/discussions/3103) that this would be helpful.
The example now slightly differs from the [Vega-Lite example](https://vega.github.io/vega-lite-v2/examples/bar_diverging_stacked.html) since there is a small error in the hard-coded data provided in the Vega-Lite example (percentage should not be 0 when there are 11 answers): 
```
{
"question": "Question 2",
"type": "Strongly agree",
"value": 11,
"percentage": 0,
"percentage_start": 63.6,
"percentage_end": 63.6
}
```
@binste would be great if you can …
=>  copied  percentage calculation in example

tests/examples_arguments_syntax/distributions_and_medians_of_likert_scale_ratings.py, tests/examples_methods_syntax/distributions_and_medians_of_likert_scale_ratings.py
Adapted the example from the [Vega-Lite example](https://vega.github.io/vega-lite/examples/layer_likert.html). This PR will resolve #3098 
The Altair example contains two differences:
- Ordering of y-axis (now alphabetical & ascending)
- Added tooltips to better quantify size of the bubbles
**Vega-Lite**
**Altair**
In the contribution guidelines, it's mentioned that the source data should be named as `source`. This examples contains however two sources. It's maybe worth thinking about adding guidelines for this case and mention them in the [Contribution guidelines](https://github.com/altair-viz/altair/blob/master/CONTRIBUTING.md#how-to-contribute-documentation-to-vega-altair).
=> Distributions and medians of likert scale ratings

.github/workflows/build.yml, altair/utils/_dfi_types.py, altair/utils/core.py, altair/utils/data.py, doc/releases/changes.rst, tests/test_transformed_data.py, tests/utils/test_dataframe_interchange.py, tests/utils/test_mimebundle.py
Closes #3112
After discussion and experimentation in #3112, it looked to me like the best approach for generalizing our column type inference beyond pandas is to look up column names and types in the return value of the `__dataframe__` protocol method. If we do this (rather than convert the input dataset to an arrow table and accessing the arrow schema), we leave it up the the implementation library whether accessing the column type information results in the full conversion of the entire dataset. 
For example, @jcrist noted that today Ibis will eagerly perform a conversion to arrow when the `__dataframe__` method is called. But if there's a motivating use case (like the functionality in this PR) then it would be possible to rework the architecture so that accessing only the column type …
=> Support for type inference for DataFrames using the DataFrame Interchange Protocol

.github/workflows/build.yml, altair/utils/core.py, doc/releases/changes.rst, pyproject.toml, tests/utils/test_core.py
[This import](https://github.com/altair-viz/altair/pull/3114/files#diff-d110e8643c6feff37c22c1a5c7d213b8384177718b8e26edd8e1b8f2ed027a0aR18) introduced in #3114 is not available in Pandas < 1.5 and Altair currently supports Pandas >= 0.18. This PR adds a test run with the lowest supported Pandas version.
@jonmmease Do you know of a good way to make that type check independent of the pandas import? Else, we could fall back on not type-hinting it if necessary. Feel free to push directly to this branch if you have an idea and want to try it out in the GitHub actions workflow.
Pandas 0.18 is from 2016 and we could for sure consider bumping it but I don't think we can go to Pandas 1.5 just yet. Especially not in a minor release of Altair.
=> Fix accidental requirement of Pandas 1.5. Bump minimum Pandas version to 0.25. Run tests with it

altair/utils/data.py, pyproject.toml
=> MAINT: Use importlib.metadata and packaging instead of deprecated pkg_resources

altair/jupyter/js/index.js
Follow up from https://github.com/altair-viz/altair/pull/3119#pullrequestreview-1558483029.
The `https://cdn.jsdelivr.net/npm/lodash-es@4.17.21/lodash.js` entrypoint points to:
```js
/**
* @license
* Lodash (Custom Build) <https://lodash.com/>
* Build: `lodash modularize exports="es" -o ./`
* Copyright OpenJS Foundation and other contributors <https://openjsf.org/>
* Released under MIT license <https://lodash.com/license>
* Based on Underscore.js 1.8.3 <http://underscorejs.org/LICENSE>
* Copyright Jeremy Ashkenas, DocumentCloud and Investigative Reporters & Editors
*/
export { default as add } from './add.js';
export { default as after } from './after.js';
export { default as ary } from './ary.js';
export { default as assign } from './assign.js';
export { default as assignIn } from …
```
=> feat(widget): prefer lodash-es/debounce to reduce import size

altair/utils/schemapi.py, altair/vegalite/v5/api.py, tools/schemapi/schemapi.py
See #2951 for an overview of the type hinting effort. For some methods which construct classes based on their input parameters I took the shortcut of typing them as `Any` for now as I think to make it more specific we would need some more complicated type hints. These are not super relevant for users anyway but happy to take suggestions on how to improve it!
We need to keep the type of `Undefined` as `Any` as long as not all parts of the code are type hinted where `Undefined` is used. Afterwards we can change it to the proper `UndefinedType`.
=> Type hint schemapi.py

doc/user_guide/marks/line.rst
It wasn't obvious how the year was used to create the order. Now you can see that one endpoint is 1956, the other is 2010.
I considered adding mark_text(), but that seemed heavier weight and potentially distracting.
Now, the chart has this tooltip when I hover over the last point:
=> doc: Add tooltip to Line example with custom order

doc/user_guide/marks/line.rst
I didn't like
- How verbose the title was
- How it called this a "scatter plot". It is not.
also:
- was explicit in how the one endpoint is earliest, other is latest
- replaced weird "smart" apostrophe with basic vanilla one
- Normed capitalization of following example
=> docs: line: Improve prose on custom ordering

altair/vegalite/v5/api.py
All other `transform_` methods already have a `Self` return type.
=> Add return type to transform_extent

altair/__init__.py, altair/vegalite/v5/api.py, altair/vegalite/v5/schema/core.py, tools/generate_schema_wrapper.py, tools/update_init_file.py
I noticed in #3143 that `alt.param` sets some attributes on `alt.Parameter` which do not exist on that class when its initialised. That's a problem for mypy as all attributes should exist from the beginning. This PR adds `empty`, `param`, and `param_type` and type hints for the whole class.
I tested with the [Interval examples](https://altair-viz.github.io/user_guide/interactions.html#interval-selections) from the docs to make sure that indeed `empty=Undefined` leads to `empty` not being present in the final chart dict which is the old behaviour when `empty` was not present on the parameter instance at all if it was not defined.
=> Add missing arguments to Parameter and add type hints

altair/vegalite/v5/api.py, pyproject.toml, tools/generate_api_docs.py, tools/generate_schema_wrapper.py, tools/schemapi/codegen.py, tools/schemapi/utils.py, tools/update_init_file.py
This adds type hints to the code generation part. I also used the opportunity to remove some redundant code. This hopefully makes it a bit easier to modify the code generation which I aim to do soon to implement #2854.
As it still generates the exact same Altair code (which is also tested in the PR checks), I'll merge this once all tests pass without a review.
=> Type hints: Code generation

doc/user_guide/encodings/index.rst, doc/user_guide/times_and_dates.rst
This will close #3162 .
Add an example as below comparing using quantitative, ordinal and temporal data type.
With explanation:
To plot the year data as four digit format; i.e. without thousand separator, we recommend converting integer to string data type first, then storing the data as temporal, since directly convert integer to temporal data type would result in an error.
And also close #1365
=> [Doc] Add integers to four digit year format example

doc/user_guide/marks/text.rst
This will close #1055 and close #1976
=> [Doc] Add Label Position Based on Condition Example

doc/about/citing.rst, doc/about/roadmap.rst, doc/user_guide/customization.rst, doc/user_guide/encodings/index.rst
This will close #3182 , #1961 and #2660  .
Rotate axis title example:
close #1961
Sort legend by specific data example:
close #2660 
Add Citing section under About tab
=> [Doc] Update UserGuide: Add Rotate Axis, Sort Legend Example, Citing Section

altair/utils/display.py, altair/utils/html.py, altair/utils/mimebundle.py, altair/utils/save.py, altair/vegalite/v5/api.py, altair/vegalite/v5/display.py
Adds type hints to utils/save.py and utils/mimebundle.py. After this PR and #3208, there are only a few minor steps left in #2951 🥳
=> Type hint utils/save.py and utils/mimebundle.py

altair/utils/save.py, altair/vegalite/v5/api.py
I experience issues with the Null on windows. It appears as if when saving HTML, the template is already utf-8 and when writing the files with the system default code page, there are encoding issues.
Alternatively I see another options to solve my problem.: 
set it only in the
`elif format == "html":`
branch...
=> Update save.py to use utf-8 instead of None per default

altair/utils/_dfi_types.py, altair/utils/core.py, doc/releases/changes.rst
Closes #3294 . As discussed in that issue, I switched to Protocols over ABC classes as other libraries such as Polars of course don't use our own classes but instead have their own implementations -> ABC classes won't type check but Protocols work. 
After that change Polars dataframes still did not satisfy mypy so I digged a bit into the interchange protocol. There are minor differences in how Pandas, Polars, etc. have implemented type hints for the protocol and sometimes even the protocol itself. For example, in Polars `CategoricalDescription.is_dictionary` has type `Literal[True]` as it is indeed always True in the case of Polars. However, the interchange protocol only requires `bool`. As [`TypedDict`s are invariant](https://peps.python.org/pep-0589/#type-consistency), this will not …
=> Fix type checker errors for libraries such as Polars where Altair uses dataframe interchange protocol

doc/releases/changes.rst, doc/user_guide/display_frontends.rst
Adds a very brief section on dashboards to give users a quick overview which frameworks have support for Altair. These are the ones I'm aware off but please let me know if I missed anything!
This was previously discussed in https://github.com/altair-viz/altair/pull/2762 and https://github.com/altair-viz/altair/pull/2415.
=> Docs: Add section on displaying Altair charts in dashboards

doc/user_guide/display_frontends.rst
`utm_medium=altair` url parameter allows the Dash team to track how many users come over from the Altair docs.
=> Docs: Link to new section on Altair in Plotly docs

doc/about/roadmap.rst
Marks 3 items in the roadmap as completed. The formatting looks like this:
=> Docs: Mark completed items in roadmap

tests/examples_methods_syntax/multiple_interactions.py
This is an attempt to modify the original "multiple interaction" example from the Altair-Vega documentation website in regard to the scale created with the checkbox condition for big budget films within the movies dataset. I had experimented with the example on my own to see how the Altair-Vega syntax worked when I realized that the quantitative scale for the alt.Size argument regarding a film's big budget designation wasn't fully accurate considering how the variable is entered. From what I read, the initial transformation in the chart creation creates a nominal scale between two categories of films, which can be labelled as "above $100 mil (big budget)" and "below $100 mil (not big budget)." However, the default scale being set to ':Q' for this variable means that the scale incorrectly …
=> Docs: Modifying scale of "multiple interactions" example and adding legend adjustments

altair/vegalite/v5/api.py
This will close #2545, 
where the usage should be alt.Chart(df, mark=alt.CompositeMarkDef(type='boxplot'))
this PR update definition in https://altair-viz.github.io/user_guide/generated/toplevel/altair.Chart.html,
but for MarkDef in https://altair-viz.github.io/user_guide/generated/core/altair.MarkDef.html
```
The mark type. This could a primitive mark type (one of "bar", "circle", "square", "tick", "line", "area", "point", "geoshape", "rule", and "text" ) or a composite mark type ( "boxplot", "errorband", "errorbar" ).
```
Seems like it's generated from vega-lite-schema and I might need some instruction on where to start
=> [Doc] Fix Chart and MarkDef language

altair/utils/schemapi.py, tools/schemapi/schemapi.py
Closes #3382
This PR substantially improves performance of `alt.Chart.from_dict`.  See #3382 for a detailed description and reprex.
Grateful for any feedback on this PR, e.g. whether the team would prefer I leave the current function as is, or use `functools.lru_cache`, instead of the top-level `jsonschema_version_str = importlib_version("jsonschema")` statement.  Or some other solution.
WIP whilst I make sure the builds/tests pass
=> perf: Improve performance of `Chart.from_dict`

pyproject.toml, tests/examples_arguments_syntax/__init__.py, tests/examples_methods_syntax/__init__.py, tests/test_examples.py
Temporary fix for #3418. Seems like the failing test is flaky and the geopandas pin introduced in #3421 did not solve it as it happened again in https://github.com/vega/altair/actions/runs/9138091817/job/25128832186?pr=3419.
This PR disables the test for now and removes again the pin.
=> ci: remove again geopandas pin and disable flaky test

.github/workflows/build.yml, altair/__init__.py, altair/utils/display.py, altair/utils/mimebundle.py, altair/utils/save.py, altair/vegalite/v5/api.py, doc/getting_started/resources.rst, doc/user_guide/display_frontends.rst, doc/user_guide/large_datasets.rst, doc/user_guide/saving_charts.rst, pyproject.toml, tests/test_examples.py, tests/test_jupyter_chart.py, tests/utils/test_compiler.py, tests/utils/test_mimebundle.py, tests/vegalite/v5/test_api.py, tests/vegalite/v5/test_renderers.py
Now that both altair_viewer and altair_saver are archived and not compatible with Altair anyway, I'd suggest to remove all references to them to clean up the code base a bit. In this PR, I:
* removed all references to altair_viewer
* removed all references to altair_saver except for 1 mention in the docs
* uninstall anywidget and vl-convert-python as well in the build workflow to make sure we don't introduce hard dependencies. This is not directly related to the rest of the PR but hope it's ok for efficiency reasons. Else, happy to take it out!
* added a deprecation warning if someone uses the `webdriver` argument to the `.save` method as it's not relevant for `vl-convert`. I didn't want to remove it just now as users might still have it set although they have switched to `vl-convert` in …
=> ci: Remove references to archived altair_viewer and altair_saver in ci, docs, and tests. Uninstall anywidget and vl-convert-python during one test run

pyproject.toml
[numpy 2.0.0](https://github.com/numpy/numpy/releases/tag/v2.0.0) is now released.
See [numpy-2-migration-guide](https://numpy.org/devdocs/numpy_2_0_migration_guide.html)
Also the `ruff` group `NPY` mentioned in https://github.com/vega/altair/pull/3431 could be useful here, especially [numpy2-deprecation](https://docs.astral.sh/ruff/rules/numpy2-deprecation/) which has an autofix.
I've split this out since at least the pin will need to be merged prior to 5.4.0, but updating any code might be more complicated until `python<3.9` is dropped.
=> ci: prepare for `numpy 2`

.github/dependabot.yaml
Currently, deprecation warnings are being thrown due to actions using out-of-date Node versions ([recent example](https://github.com/vega/altair/actions/runs/9537134309)). Rather than submitting a PR to update them manually, this PR configures Dependabot to regularly submit PRs to update GitHub action versions as needed.
If this PR merges, you can expect Dependabot to immediately submit a PR to update actions to newer versions.
=> ci: Add a Dependabot config to auto-update GitHub action versions

tests/examples_arguments_syntax/line_chart_with_cumsum_faceted.py, tests/examples_methods_syntax/line_chart_with_cumsum_faceted.py
This PR replaces the "Cumulative Wikipedia Donations" example with a new chart, based on issue #2424. The original example was broken and went against the Contribution guideline that requires local datasets, and a new faceted cumulative sum chart was proposed in 2021. This PR incorporates the suggestion made by @jakevdp to improve x-axis labels. The example was developed and proposed by @harabat, but had not been 100% finalized. I made some very small tweaks to get it working in Altair v5 and to incorporate small recommendations in #2424.
- Introduced a new cumulative sum chart to replace the broken (and since-removed) example of Cumulative Wikipedia Donations.
>The following code provides an illustration of a cumulative sum (to replace the broken chart), but also clarifies the styling of …
=> docs: Add example of cumulative line chart with facet

tests/utils/test_utils.py
pandas deprecated `freq='H'` in favour of `freq='h'` to avoid case-sensitivity issues (`'ms'` means millisecond, but `'MS' month-start), `'h'` works on both older and newer versions
=> chore: avoid pandas warning for `freq='H'` in test_utils.py

altair/vegalite/v5/api.py, tools/schemapi/utils.py
=> style: Remove outdated comments about the use of the former _Parameter protocol

altair/utils/schemapi.py, tools/schemapi/schemapi.py
Fixes an issue identified in https://github.com/vega/altair/pull/3431#issuecomment-2194905942 and addresses `typing.Optional`
This is a follow-up PR to #3431, following @binste [comment](https://github.com/vega/altair/pull/3431#issuecomment-2195062569)
=> docs: Fix and improve `alt.Optional` doc

pyproject.toml
Fixes warnings here https://github.com/vega/altair/actions/runs/9733301918/job/26860053484?pr=3452
This was due to `ruff` updating around the same time as https://github.com/vega/altair/pull/3431#issuecomment-2195071162
The `SIM101` rule that it is remapped to is already part of our config
=> fix: remove remapped `ruff` rule `PLR1701`

altair/utils/core.py
Related to https://github.com/vega/altair/pull/3444#issuecomment-2196481574
Ready for review
*This change isn't related to the `sphinx` theme, which seems to be on [a newer version](https://github.com/pydata/pydata-sphinx-theme/releases/tag/v0.15.3). See [table issue](https://github.com/Quansight-Labs/czi-scientific-python-mgmt/issues/50)
I didn't go through trying to fully resolve the `mypy` issues with `@utils.use_signature`. 
However, I've updated the comments for future reference.
=> fix(docs): `@utils.use_signature` formatting

altair/vegalite/v5/schema/_typing.py, altair/vegalite/v5/schema/channels.py, tools/generate_schema_wrapper.py, tools/schemapi/utils.py
This allows a `TypedDict` to be used, where `mypy` previously would have required exactly a `dict`.
The name does not conflict with any existing types/classes in `altair` and has the benefit of being short like `dict`, but more permissive.
I have only added this to `Chart.encode` as I know this does not require the mutability of `dict`, which I cannot confidently say for elsewhere in `altair`.
A future PR could investigate other generated wrappers that use `dict` and either reuse `Map` or add another alias to the `EXTRA_ALIASES` literal.
Fixes https://github.com/vega/altair/pull/3427#discussion_r1662542866
```
cmd [6] | mypy altair tests
tests\vegalite\v5\test_api.py:375: error: Unused "type: ignore" comment  [unused-ignore]
tests\vegalite\v5\test_api.py:376: error: Unused "type: ignore" …
```
=> feat(typing): adds `Map` alias for `Mapping[str, Any]`

altair/utils/data.py, pyproject.toml
The ~~user~~ contributor will see this message:
```bash
altair\utils\data.py:17:5: TID251 `typing.Optional` is banned: Use `Union[T, None]` instead. 
`typing.Optional` is likely to be confused with `altair.Optional`, which have a similar but different semantic meaning. 
See https://github.com/vega/altair/pull/3449 
Found 1 error.
```
Partial fix for https://github.com/vega/altair/pull/3452#discussion_r1663857513
=> feat(typing): Ban `typing.Optional` import using `ruff`

CONTRIBUTING.md, NOTES_FOR_MAINTAINERS.md, README.md, tests/test_toplevel.py
- Update references to `hatch` commands
- Adds two testing sub-sections in `CONTRIBUTING.md`
This is following hiccups in https://github.com/vega/altair/pull/3452 that can be avoided in the future.
Also a very minor change, but used `bash` for the fenced code blocks to highlight comments
=> docs: Update `hatch` guidance

altair/vegalite/v5/api.py
Following https://github.com/vega/altair/pull/3431 a number of these are now importable.
Additionally, I spotted the `encodings` parameter (e.g. in `selection_point`) was annotated with `str`, but should be constrained to only `SingleDefUnitChannel_T`.
=> refactor(typing): Reuse generated `Literal` aliases in `api`

doc/user_guide/encodings/channels.rst
The spelling of the `fillOpacity` channel was incorrect and ignored the camel case.
=> docs: Fix camel case of fillOpacity channel

pyproject.toml
I should have removed this in https://github.com/vega/altair/pull/3426 but better late than never
=> ci: remove `toolz` from `[[tool.mypy.overrides]]`

altair/utils/schemapi.py, tools/schemapi/schemapi.py
This is a relatively minor change, but I think the result is much easier to understand.
There is no observable difference otherwise, confirmed by the tests:
- `test_expression_function_expr`
- `test_expression_function_string`
- [doctest] `altair.vegalite.v5.api.TopLevelMixin.transform_bin`
- [doctest] `altair.vegalite.v5.api.TopLevelMixin.transform_calculate`
- [doctest] `altair.vegalite.v5.api.TopLevelMixin.transform_timeunit`
- [doctest] `altair.vegalite.v5.api.TopLevelMixin.transform_window`
The above were all failing -  before I figured out what the brace escaping in the original was up to.
=> refactor: Simplify `SchemaBase` repr

altair/utils/schemapi.py, tools/schemapi/schemapi.py
Fixes `mypy` error that appeared during a merge https://github.com/vega/altair/actions/runs/9905108163/job/27364368641
```
altair/utils/schemapi.py:423: error: Argument 1 to "join" of "str" has incompatible type "Any | Unset"; expected "Iterable[str]"  [arg-type]
Found 1 error in 1 file (checked 367 source files)
Error: Process completed with exit code 1.
```
This is ready to merge and is blocking for all other PRs
=> fix(typing): Ignore `[arg-type]` error in `_deduplicate_enum_errors`

pyproject.toml
- https://github.com/astral-sh/ruff/releases/tag/0.5.3
- https://docs.astral.sh/ruff/rules/unspecified-encoding/
See 88ec5c8b6e4b8234ca90c0a0e80d9f7dfe41dd44 and https://github.com/vega/altair/pull/3431#discussion_r1629811197 for issue with previous fix
=> ci: bump `ruff>=0.5.3` for `PLW1514` fix

tests/vegalite/v5/test_api.py
`test_ibis_with_date_32` was always emitting the same warning on `3.8`:
```
================================================================================================= warnings summary =================================================================================================  
tests/vegalite/v5/test_api.py::test_ibis_with_date_32   
/altair/altair/vegalite/v5/api.py:233: UserWarning: data of type <class 'ibis.expr.types.relations.Table'> not recognized
warnings.warn(f"data of type {type(data)} not recognized", stacklevel=1)  
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html 
==================================================================================== 210 passed, 1 xfailed, 1 warning in 17.92s …
```
=> test: skip `ibis` test on unsupported `python` version

altair/utils/compiler.py, altair/utils/data.py, altair/utils/display.py, altair/utils/plugin_registry.py, altair/utils/theme.py, altair/vegalite/v5/data.py, tests/utils/test_plugin_registry.py
Fixes
- https://github.com/vega/altair/actions/runs/10020215927/job/27697611769
- https://github.com/vega/altair/actions/runs/10013817103/job/27682236626#step:7:15
- https://github.com/vega/altair/actions/runs/10020215927/job/27697611769
```log
altair/utils/plugin_registry.py:213: error: "PluginType" not callable  [misc]
altair/utils/plugin_registry.py:213: note: Error code "misc" not covered by "type: ignore" comment
Found 1 error in 1 file (checked 369 source files)
Error: Process completed with exit code 1.
```
The release of [Mypy 1.11](https://mypy-lang.blogspot.com/2024/07/mypy-111-released.html?m=1) introduced stricter typing for `functools.partial`.
The existing `# type: ignore` comments were no longer sufficient and correcting everything (whilst not breaking all the derived …
=> fix(typing): Resolve `mypy==1.11.0` issues in `plugin_registry`

tests/examples_arguments_syntax/interactive_bar_select_highlight.py, tests/examples_methods_syntax/interactive_bar_select_highlight.py
Fixes https://github.com/vega/altair/issues/3301
Utilises `alt.when`, introduced in https://github.com/vega/altair/pull/3427
---
@mattijn I thought adding this first would be something to refer to in the follow-up PR discussed in https://github.com/vega/altair/pull/3427#issuecomment-2237588984
Also revisiting since https://github.com/vega/altair/issues/2759#issuecomment-2138158202 I have a better explanation for the `empty=False` placement.
For `select`, the `Parameter` is used twice - once with `empty=False` and another with the default.
Whereas `highlight` is used only once.
I think this could be helpful to add to the `alt.condition(empty)` and each `.when(empty)` doc, as this is a good justification for why you can pass `empty` there. …
=> docs: Add example for *Bar Chart with Highlighting on Hover and Selection on Click*

doc/conf.py
Removes this warning when building docs:
```log
preparing documents... WARNING: unsupported theme option 'footer_items' given
```
=> fix: remove unsupported `sphinx` theme option `'footer_items'`

altair/vegalite/v5/api.py
Partial fix:
- https://github.com/vega/altair/pull/3485#pullrequestreview-2189012089
- https://github.com/vega/altair/pull/3485#issue-2418667202
This was already being [handled internally](https://github.com/vega/altair/blob/24e03154fb93c26eccf72d0d31fc6bc777cc0526/altair/vegalite/v5/api.py#L1516), but now aligns more closely with `when` and provides a documentable argument.
I was hoping to get this doc approved, [before moving onto](https://github.com/vega/altair/discussions/3478#discussioncomment-10104219) `when-then-otherwise` as this is a smaller change - but will be reused there multiple times
=> docs: Add `empty` as a explicit `condition` kwarg

altair/utils/__init__.py, altair/utils/schemapi.py, altair/vegalite/v5/api.py, altair/vegalite/v5/schema/_typing.py, doc/conf.py, tools/generate_schema_wrapper.py, tools/schemapi/schemapi.py, tools/schemapi/utils.py
Planned in:
- https://github.com/vega/altair/pull/3427#discussion_r1683242081
- https://github.com/vega/altair/pull/3480/files/419a4e944f231026322e2c4f137e7a3eb94735e8#r1679197993
Tidying up some of the symbols defined in (my) earlier PRs.
These didn't need to be defined in `api` and can now be more widely used.
- `api._is_undefined` -> `schemapi.is_undefined`
- Added to `utils.__all__`
- `api._OneOrSeq` -> `_typing.OneOrSeq`
=> refactor: Rename and move `is_undefined`, `OneOrSeq`

pyproject.toml
I'm seeing a CI failure in the downstream tests: https://github.com/narwhals-dev/narwhals/actions/runs/10055785067/job/27793203912?pr=587
Thanks for contributing to Altair!
Please follow these guidelines when submitting your PR:
- Describe the purpose of the changes in PR, so that it is easy to understand the implication of the suggested changes.
- Here is a [helpful article about writing effective PR descriptions](https://medium.com/@greenberg/writing-pull-requests-your-coworkers-might-enjoy-reading-9d0307e93da3).
- Include unit tests and documentation for new features
- Ensure that the title is a concise [semantic commit message](https://www.conventionalcommits.org/) (e.g. "feat: Add `embed_options` to charts").
- Append `!` if the change is breaking (e.g. "fix!: Raise error when …
=> ci: include optional dependencies for Polars backend in ibis-framework install

.github/workflows/build.yml
Addresses one item in https://github.com/vega/altair/issues/3497
> This one is a pretty minor fix, and could be added now - since eventually it will be the lower bound.
=> ci: Add `python-version=="3.9"` to github action

pyproject.toml
I left this as a TODO during #3493 and only spotted it after merging.
See for detail:
- https://github.com/vega/altair/pull/3493#issuecomment-2243507107
- https://github.com/vega/altair/pull/3493#issuecomment-2243639106
=> ci(ruff): Remove stale `docstring-code-format` comment

pyproject.toml, tests/utils/test_utils.py
Follow-up: https://github.com/vega/altair/pull/3438
Most of the `numpy` usage is within the test examples, which *is not* run through `ruff`.
Applying all of [`NPY`](https://docs.astral.sh/ruff/rules/#numpy-specific-rules-npy) only required one fix, so AFAIK `altair` is compatible with `NumPy 2.0`.
---
Moving out of draft after checking for issues in `r"tests/examples_.+_syntax/*.py"`
Edit: See https://github.com/vega/altair/pull/3504#issuecomment-2251050382
=> ci: relax `numpy<=2.0.0` constraint

doc/user_guide/customization.rst
Occurs during doc build, due to both variables being used without a defintion.
```py
./doc/Lib/site-packages/sphinxext_altair/altairplot.py:261:
UserWarning: altair-plot: ./altair/doc/user_guide/customization.rst:826 Code Execution failed:
NameError: name 'format_locale' is not defined
warnings.warn(message, stacklevel=1)
```
=> fix: Avoid `sphinx` error "Code Execution failed:NameError: name 'format_locale' is not defined"

pyproject.toml
This PR adds the optional `ipython` dependency `ipykernel`, to avoid the following issue.
This has to be modified to fix:
```bash
>>> python -m uv pip install ipykernel -U --force-reinstall
```
---
I have been manually working around this since we moved from `pip` -> `uv` in https://github.com/vega/altair/pull/3431#issuecomment-2168654915
But this change is much simpler and doesn't need to be repeated for each new environment.
=> build: Add `ipykernel` optional dependency to `dev` group

altair/utils/save.py, altair/vegalite/v5/api.py, doc/user_guide/api.rst, tools/generate_api_docs.py
Partially addresses #3454 
> - Should deprecated features be documented to the same level as their replacements?
>	- Deprecated: https://altair-viz.github.io/user_guide/generated/api/altair.selection_single.html#altair-selection-single 
>	- Replacement: https://altair-viz.github.io/user_guide/generated/api/altair.selection_point.html#altair.selection_point
---
Mainly impacts [API Functions](https://altair-viz.github.io/user_guide/api.html#api-functions) where it is much clearer which `selection_` functions should be used, since 3/5 are no longer there.
=> docs: Undoc deprecated functionality

altair/vegalite/v5/api.py
Seems like this was only missed in one place.
Should've caught this in #3509 but better late than never
=> docs: Remove reference to `altair_saver` in `save`

doc/getting_started/resources.rst
The documentation contains a broken link to the Altair Ally project.
The PR updates the link.
=> docs: Update link to Altair Ally

altair/utils/theme.py, altair/vegalite/v5/theme.py
- https://github.com/vega/vega-themes/pull/587
- https://github.com/pola-rs/polars/pull/17995#issuecomment-2266683585
- https://vega.github.io/vega-themes/?theme=carbonwhite
- https://vega.github.io/vega-themes/?theme=carbong10
- https://vega.github.io/vega-themes/?theme=carbong90
- https://vega.github.io/vega-themes/?theme=carbong100
Support autocomplete for `themes.enable(name)`.
=> feat: Adds 4 missing `carbon` themes, provide autocomplete

doc/user_guide/customization.rst
Resolves 1 item in https://github.com/vega/altair/issues/3519
[Vega Theme Test](https://vega.github.io/vega-themes/?renderer=canvas)
=> docs: Link to `Vega Theme Test` in user guide

tests/examples_arguments_syntax/bump_chart.py, tests/examples_methods_syntax/bump_chart.py, tests/test_examples.py, tests/test_transformed_data.py, tests/utils/test_utils.py, tests/vegalite/v5/test_api.py
pandas has two month-related offsets:
- MonthBegin, which is aliased to 'MS'
- MonthEnd, which is aliased to 'M' and is being renamed to 'ME' (because it was a common source of confusion, people would see 'M' and expect it to mean 'month', not 'month end'... https://github.com/pandas-dev/pandas/issues/9586)
When doing a monthly group-by, I think the first one gives the results that people are usually actually looking for, and is the same across versions, hence removing the need for filterwarnings or version checks
In the `bump_chart.py` example:
- grouping by `'6MS'` means that the windows are:
- [2000-01-01, 2000-07-01)
- [2000-07-01, 2001-01-01)
- ...
- grouping by '6M' (or, now, '6ME') means that the windows are:
- (1999-07-31 23:59:59.999999999, 2000-01-31 23:59:59.999999999]
- …
=> chore: Remove filterwarnings from tests for cross-version pandas compatibility

altair/jupyter/jupyter_chart.py, altair/utils/core.py, altair/utils/save.py, altair/utils/schemapi.py, altair/vegalite/v5/api.py, pyproject.toml, tools/schemapi/schemapi.py, tools/schemapi/utils.py
- https://docs.astral.sh/ruff/rules/complex-structure/#why-is-this-bad
- https://docs.astral.sh/ruff/settings/#lint_mccabe_max-complexity
Previously was set at **18**, the default is **10**.
As the rule was not in `[tool.ruff.lint.select]`, the setting was never used.
Setting such a high limit hides opportunities to simplify large, complex functions.
Many cases were resolved/improved in vega#3431.
There were 2 I fixed in this PR as they were quite simple changes.
The remainder use the *# noqa: C901* comment to serve as a TODO.
=> ci(ruff): Enforce the default `C901` complexity

altair/jupyter/js/index.js, altair/utils/_importers.py, altair/utils/_transformed_data.py, altair/vegalite/v5/schema/__init__.py, altair/vegalite/v5/schema/core.py, altair/vegalite/v5/schema/vega-lite-schema.json, pyproject.toml, tests/vegalite/v5/test_api.py, tools/generate_schema_wrapper.py
Compared to 5.19, it includes the new parameters `react` and `tickBandPaddingInner`.
Edit: I'll need to update the tests next. Note to myself to also update `NOTES_FOR_MAINTAINERSE.md` to mention this.
=> feat: Update Vega-Lite to 5.20.1

altair/utils/core.py, altair/vegalite/v5/schema/channels.py, tests/utils/test_schemapi.py, tools/generate_schema_wrapper.py
=> fix: Raise informative error message if a non-existent column name is passed

pyproject.toml
https://github.com/astral-sh/ruff/releases/tag/0.6.0
Resolves the need for another PR mentioned in https://github.com/vega/altair/pull/3536#discussion_r1715709800
=> ci: bump `ruff>=0.6.0`

pyproject.toml
=> ci: Remove `m2r` from `mypy.overrides`

pyproject.toml
Partially reverts https://github.com/vega/altair/pull/3527
Didn't fix the issue in https://github.com/vega/altair/pull/3515#discussion_r1709995028
Caused a **local** regression when running `hatch test --all`
```cmd
>>> hatch test --python 3.8       
────────────────────────────────────────────────────────────────────────────────────────────────────── hatch-test.py3.8 ───────────────────────────────────────────────────────────────────────────────────────────────────────
× No solution found when resolving dependencies:
╰─▶ Because only the following versions of myst-parser are available:
myst-parser<=0.4.0
myst-parser>=0.5.0,<=0.5.1
myst-parser>=0.6.0,<=0.7.1
myst-parser>=0.8.0,<=0.13.7
myst-parser>=0.14.0
and myst-parser==0.3.0 was yanked (reason: no sphinx pinning), we can
conclude that …
```
=> revert: Remove `sphinx` version constraint

altair/utils/schemapi.py, tools/schemapi/schemapi.py
- #3531 
This PR addresses one [complex-structure](https://docs.astral.sh/ruff/rules/complex-structure/) violation, adds some typing, and gives a little performance boost in `SchemaBase.copy`.
See [each commit message](https://github.com/vega/altair/pull/3543/commits) for more detail on specific changes.
- Initialize an empty set **once** at origin, rather than creating a new list per iteration
- Renamed to `by_ref` in the new private function, to better describe the operation.
- No change to public API.
- Define a partial `copy` to reduce repetition
- Use a genexpr for `args`, to avoid unpacking twice
=> refactor: Simplify `SchemaBase.copy`

altair/utils/schemapi.py, tools/schemapi/schemapi.py
These are all very low-priority, but allows using `"python.analysis.typeCheckingMode": "basic"` in this module, without any warnings.
Planning to investigate improving the peformance of validation, which will be much easier with a live type checker
=> fix(typing): Resolve misc type ignores in `schemapi.py`

tests/utils/test_schemapi.py
Working on a different branch I had to track down the comment explaining that this should display only 3 errors.
The original name lead me to expect 4 errors.
=> test: Rename test to more specific `chart_error_example__four_errors_hide_fourth`

tests/utils/test_schemapi.py
Follows https://github.com/vega/altair/pull/3501#discussion_r1711277924
Simply removes the redundant prefix `"chart_error_example__"`, which only added noise when combined into`"test_chart_validation_errors[chart_error_example__..."` 19 times
=> test: Shorten `test_chart_validation_errors` test ids

altair/utils/_vegafusion_data.py, altair/utils/data.py, altair/vegalite/v5/api.py, pyproject.toml, tests/utils/test_data.py
closes https://github.com/vega/altair/issues/3549
Also addresses the issue brought up in https://github.com/marimo-team/marimo/pull/2006
=> fix: Pass native dataframe to data transformers

altair/utils/__init__.py
Spotted while writing an `__all__` for `schemapi.py` in #3547
=> refactor: Replace an indirect `SchemaBase` import

altair/utils/schemapi.py, altair/vegalite/v5/api.py, tests/vegalite/v5/test_api.py, tools/schemapi/schemapi.py
Fixes 
- https://github.com/vega/altair/pull/3394#issuecomment-2302995453
- https://github.com/vega/altair/pull/3394#issuecomment-2303028521
- https://github.com/vega/altair/actions/runs/10497592890/job/29080773958?pr=3394
---
I originally thought https://github.com/vega/altair/pull/3543 introduced this regression.
Haven't tested on earlier branches, but @mattijn can you check if you can repro on `v5.4.0`?
I think it would be present on there as well
=> fix: Resolve `Then` copy `TypeError`

.gitignore
Related https://github.com/vega/vl-convert/issues/184
Using this directory for type stubs, which is a temporary solve for the `vl_convert` issue
=> ci: Add `typings/` to `.gitignore`

RELEASING.md
I think protecting our main branch is a great idea:
* to prevent accidental pushes to main
* while tests are still running for a PR, you can now use the auto-merge feature. I find this very convenient in other repos as you don't have to check back in a few minutes and then merge but instead, if you click it, it merges automatically once all checks have passed:
I took the liberty to already enable it in [the repo settings](https://github.com/vega/altair/settings) based on https://github.com/vega/altair/pull/3559#issuecomment-2313254486. This PR updates the RELEASING.md file to reflect it.
We can still merge without review which I think is useful for minor changes (typos, minor changes in pyproject.toml, etc.)
Happy to discuss! We can also try it out for a while and always revert back. …
=> docs: Update releasing notes to reflect that main branch is now protected

altair/utils/execeval.py, pyproject.toml, tests/__init__.py, tests/test_examples.py, tests/test_transformed_data.py, tests/utils/test_core.py, tests/utils/test_server.py, tests/utils/test_to_values_narwhals.py, tests/utils/test_utils.py, tests/vegalite/v5/test_api.py
While working on #3547, I've been running the test suite a bunch to identify bottlenecks.
- tools to identify, skip or run only slow tests
- some new, previously repeated mark decorators
- misc refactoring of tests using the above
- docs explaining intended usage
- Locally, this covers most tests that take 2-10 secs.
- In total, **354**/1671 tests are skipped
- reduced runtime 40  -> 20 secs
The **default** behaviour is **unchanged**:
```bash
>>> hatch test 
>>> hatch run test-slow
>>> hatch run test-fast
```
=> test: Adds `test-(slow|fast)` options

altair/utils/core.py, tests/utils/test_core.py
Was kept, but only needed for tests since #3444.
This PR factors out the test dependency, by using `pytest.MonkeyPatch` - to *temporarily* replace the global cache.
As `alt.utils.core.infer_encoding_types` is not public API - this is a safe remove, no need for deprecation.
=> refactor: Remove `channels` parameter in `infer_encoding_types`

NOTES_FOR_MAINTAINERS.md
I made the web analytics public as it's heavily anonymized, no need to hide it: https://views.scientific-python.org/altair-viz.github.io. Matplotlib have also made theirs public at https://views.scientific-python.org/matplotlib.org.
=> docs: Make plausible web analytics public and add link to maintainer notes

altair/utils/core.py, altair/vegalite/v5/api.py, altair/vegalite/v5/schema/core.py, tools/generate_schema_wrapper.py
This PR addresses problems with this decorator that cause the wrong arguments to bind in some cases.
I've tried (and failed) to fix this multiple times over the past 1-2 months, but until now, hadn't come up with a solution that:
- fixed **all** of the cases
- satisfied both `mypy` and `pyright`
After one signature fails in a chain of methods - an IDE (*not `ipython`*) can't understand much that follows. 
Therefore, I consider the issue quite signficant.
- `pyright` is inferring `Overload[...]`, which isn't a form I've seen before
- `Overload[(cb: (T@decorate, ...) -> R@decorate, /) -> ((T@decorate, **P@use_signature) -> R@decorate), (cb: (...) -> R@decorate, /) -> ((**P@use_signature) -> R@decorate)]`
- ~~Whatever the solution is, will most likely be a comment~~
- *Inserted into …
=> fix(typing): Resolve multiple `@utils.use_signature` issues

pyproject.toml
Fixes:
- https://github.com/vega/altair/pull/3536#discussion_r1748968002
- https://github.com/vega/altair/commit/c594e55e76613d0363e3b419a00cb2f920547755
No impact when not using `pylance`, but the default settings don't play nicely with virtual environments.
Any time you do something like "Find all references", it searches > 8000 files - but with this change it is reduced to 300ish.
Results in much faster and more useful language server behavior
<details>
<summary>Screenshot</summary>
</details>
=> ci: Add include patterns for `pyright`

altair/utils/html.py, altair/vegalite/v5/display.py, doc/user_guide/display_frontends.rst
> [Olli](https://mitvis.github.io/olli/) is an open-source library for converting data visualizations into accessible text structures for screen reader users. Starting with an existing visualization specification created with a supported toolkit, Olli produces a keyboard-navigable tree view with descriptions at varying levels of detail. Users can explore these structures both to get an initial overview, and to dive into the data in more detail.
Closes #3575. A possible use case of this is that in a university course where Altair is used in a Jupyter notebook, with a single line of code, `alt.renderer.enable("olli")`, all charts in a notebook can be made accessible for screen reader users.
I've tested this in JupyterLab and VS Code. In JupyterLab, all [Olli …
=> feat: Add 'olli' renderer to generate accessible text structures for screen reader users

pyproject.toml
Recent [versions](https://github.com/microsoft/pylance-release/releases) are producing warnings that cannot be silenced. 
See https://github.com/microsoft/pylance-release/wiki/Settings.json-overridden-by-Pyrightconfig.json-or-Pyproject.toml
Happy to remove in the future if this change gets reverted.
For now I've had to move personal config here sadly.
=> ci(typing): fix support `pylance>=2024.9.1`

tests/vegalite/v5/test_api.py
=> test(typing): Resolve warnings in `test_api.py`

pyproject.toml
- https://github.com/vega/altair/pull/3536#discussion_r1761310603
- https://github.com/vega/altair/discussions/3548#discussioncomment-10406087
- https://github.com/vega/altair/issues/3587
- *This* PR contains **one** of the changes already planned there
- However *that* PR is blocked until https://github.com/geopandas/pyogrio/issues/470
Updates `python_version<"3.13"` -> `python_version<"3.14"`.
This was already required due to multiple instances of importing `typing_extensions` without a version guard.
However, we are also using [PEP 728](https://peps.python.org/pep-0728/) which [hasn't landed in time](https://github.com/vega/altair/pull/3567/commits/9f49ef6003795e4d4a9b214941de203bbaa3b778) for `3.13`.
<details>
<summary>Existing usage on <code>main</code></summary> …
=> ci: Bump `typing_extensions` python to `3.14`

tests/utils/test_to_values_narwhals.py
In Narwhals we'd like to [change the dtype repr to show the time unit](https://github.com/narwhals-dev/narwhals/pull/960) (and, for Datetimes, the time zone)
This doesn't really have an impact on users, they'd just see
```
Field "timedelta" has type "Duration(time_unit='ns')" which is not supported by Altair
```
instead of
```
Field "timedelta" has type "Duration" which is not supported by Altair
```
This PR just future-proofs the Altair test
=> chore: Future-proof Duration type error message test

altair/utils/__init__.py, altair/utils/core.py, altair/utils/schemapi.py, altair/vegalite/v5/api.py, altair/vegalite/v5/schema/channels.py, tests/vegalite/v5/test_api.py, tools/generate_api_docs.py, tools/generate_schema_wrapper.py, tools/schemapi/schemapi.py
Fixes #3552
<details>
<summary><i>Overview of issues by @binste in <a href="https://github.com/vega/altair/issues/3552#issuecomment-2333898482">comment</a></i></summary>
The draft PR is very helpful! Trying to summarise/reword it for myself:
* `Then` should not inherit from `SchemaBase` as it muddies autocompletion
* We need a type hint which lets a `SchemaBase` pass due to `alt.condition` and `alt.when().then().otherwise()`. Can be `SchemaBase` or a protocol
* It's unclear to me when, as a developer, I'd use `SchemaLike`. If I understand it correctly, we mainly introduce it now to make these types work.
* Purpose:
* Fix type errors users might get right now, keeping types as narrow as possible so they are more useful
* Improving UX: keep/improve autocompletion + provide a good visual …
=> fix(typing): Improve `Then` annotations, autocompletion, docs

altair/expr/core.py
Discovered during #3600
https://github.com/vega/altair/pull/3600/commits/21d13e722a4bb466c572710f9171fc15484d5f7a
Will fix these false positives
```py
cmd [3] | mypy altair tests
tests\vegalite\v5\test_api.py:602: error: Argument 2 to "if_" of "expr" has incompatible type "int"; expected "bool | str | OperatorMixin | dict[str, Any] | None"  [arg-type]
expected = alt.expr.if_(alt.datum.b >= 0, 10, -20)
^~
tests\vegalite\v5\test_api.py:602: error: Argument 3 to "if_" of "expr" has incompatible type "int"; expected "bool | str | OperatorMixin | dict[str, Any] | None"  [arg-type]
expected = alt.expr.if_(alt.datum.b >= 0, 10, -20)
^~~
tests\examples_arguments_syntax\one_dot_per_zipcode.py:14: error: Argument 2 to "substring" of "expr" has incompatible type "int"; expected "bool | str | …
```
=> fix(typing): Add missing `float` to `IntoExpression` alias

altair/vegalite/v5/display.py
Discovered after [pushing](https://github.com/vega/altair/actions/runs/11052195855/job/30703733120?pr=3600) on an unrelated PR.
Simply applied an autofix
Due to https://github.com/astral-sh/ruff/releases/tag/0.6.8
=> fix(ruff): Resolve `SIM910` lint in `display.py`

tests/examples_arguments_syntax/calculate_residuals.py, tests/examples_methods_syntax/calculate_residuals.py
Recreation of `vega-lite` example https://vega.github.io/vega-lite/examples/joinaggregate_residual_graph.html
I noticed the last example on [Vega Theme Test](https://vega.github.io/vega-themes/) didn't have an `altair` equivalent.
This PR will also bring us one step closer to https://github.com/vega/altair/issues/3519#issuecomment-2359179155
Really like how concise the methods syntax version ended up
```py
imdb_rating = alt.datum["IMDB_Rating"]
source = data.movies.url
chart = (
alt.Chart(source)
.mark_point()
.transform_filter(imdb_rating != None)
.transform_filter(
alt.FieldRangePredicate("Release_Date", [None, 2019], timeUnit="year")
)
.transform_joinaggregate(Average_Rating="mean(IMDB_Rating)") …
```
=> docs: Adds example Calculate Residuals

.github/release.yml
Related https://github.com/vega/altair/issues/3542
This PR resolves one part of #3542, as agreed in https://github.com/vega/altair/issues/3542#issuecomment-2313042916
https://github.com/vega/altair/pull/3618 will be the first PR to use one of the new labels.
=> ci: Use `breaking`, `deprecation` labels in changelog

tests/__init__.py, tests/utils/test_compiler.py, tests/utils/test_mimebundle.py, tests/vegalite/v5/test_api.py, tests/vegalite/v5/test_renderers.py
- https://github.com/vega/altair/pull/3630#issuecomment-2395091419
```py
tests\vegalite\v5\test_renderers.py:14: error: Incompatible types in assignment (expression has type "None", variable has type Module)  [assignment]
vlc = None
^~~~
tests\vegalite\v5\test_api.py:32: error: Incompatible types in assignment (expression has type "None", variable has type Module)  [assignment]
vlc = None
^~~~
tests\utils\test_mimebundle.py:10: error: Incompatible types in assignment (expression has type "None", variable has type Module)  [assignment]
vlc = None
^~~~
tests\utils\test_compiler.py:10: error: Incompatible types in assignment (expression has type "None", variable has type Module)  [assignment]
vlc = None
^~~~
Found 4 errors in 4 files (checked 332 source files)
```
=> fix: `mypy` 1.12.0 errors

pyproject.toml, tools/generate_schema_wrapper.py
- [fix(typing): Add patch for vl-convert-python=1.7.0](https://github.com/vega/altair/pull/3630/commits/aa00dc12ab99fdb2e0f6082e1c3b1e8c9a799336)
- https://github.com/vega/vl-convert/pull/185
- https://github.com/vega/vl-convert/issues/191
- https://github.com/vega/altair/pull/3600#discussion_r1781010865
I ran into this on another branch, good news is the new stubs are working correctly:
```py
(doc) PS C:\Users\danie\Documents\GitHub\altair> mypy tools
tools\generate_schema_wrapper.py:496: error: Argument 1 to "_vega_lite_props_only" has incompatible type
"dict[Literal['carbong10', 'carbong100', 'carbong90', 'carbonwhite', 'dark', 'excel', 'fivethirtyeight', 'ggplot2', 'googlecharts', 'latimes', 'powerbi', 'quartz', 'urbaninstitute', 'vox'], dict[str, Any]]"; expected
"dict[str, dict[str, …
```
=> ci: Bump `vl-convert-python` to `1.7.0`

altair/vegalite/v5/schema/channels.py, tools/generate_schema_wrapper.py
Fixes #3634, #3554
See comments following https://github.com/vega/altair/issues/3634#issuecomment-2402420120
- https://peps.python.org/pep-0667/
=> fix: Replace unsafe `locals()` manipulation in `Chart.encode`

altair/utils/_importers.py, altair/utils/_vegafusion_data.py, pyproject.toml, tests/test_jupyter_chart.py, tests/test_transformed_data.py
- https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker
- https://github.com/vega/altair/pull/3638#pullrequestreview-2364909390
This can be removed in the future, if stubs are added like in https://github.com/vega/vl-convert/pull/185
=> fix(typing): Add untyped `vegafusion` to `mypy` overrides

pyproject.toml
I commented this out in #3536 to identify remaining typing issues.
All of `"./tools/**/*.py"` is now typed, so re-enabling in the future is very unlikely
=> chore: Remove outdated `schemapi` comment

doc/user_guide/customization.rst
It was not clear from the existing docs how to set individual chart size when using an independent scale with faceted charts and an unequal number of observations.
This adds one more chart example to `user_guide/customization.rst` to show how to vary the size using `alt.Step` to achieve this.
=> docs: adds info with step size/independent scale

altair/vegalite/v5/schema/_config.py, altair/vegalite/v5/schema/channels.py, altair/vegalite/v5/schema/core.py, altair/vegalite/v5/schema/mixins.py, pyproject.toml, tools/schemapi/utils.py, tools/vega_expr.py
The doc stated that `None` would appear after builtins. 
https://github.com/vega/altair/blob/2ba89d508f3eac2d0bfaea53dc74a13c105a0452/tools/schemapi/utils.py#L855-L864
However, this assertion doesn't hold for any `builtin` with a name length greater than 4.
The issue is not new, but became more apparent to me while writing https://github.com/vega/altair/pull/3653#discussion_r1810884346
Below `float` appears after `None`
https://github.com/vega/altair/blob/2ba89d508f3eac2d0bfaea53dc74a13c105a0452/altair/vegalite/v5/schema/_config.py#L5004
https://github.com/vega/altair/blob/e656661e6abe0c84dc548289f62b38dfc7663091/altair/vegalite/v5/schema/_config.py#L5004
I was unable to work out a sorting strategy to achieve what the doc had intended.
Instead, I've opted to always place `None` **last in …
=> fix(typing): Revise generated annotation order

altair/vegalite/v5/schema/_config.py, altair/vegalite/v5/schema/_typing.py, altair/vegalite/v5/schema/channels.py, altair/vegalite/v5/schema/core.py, tools/schemapi/utils.py
Initially covering one very specific case, `PrimitiveValue`.
Targeting that one specifically for use in #3653, where it will be used 3 times in a single annotation.
https://github.com/vega/altair/blob/4714865658994f2cda06f765dc0d31c4a4b4b5bb/altair/vegalite/v5/schema/_typing.py#L218
Having this generated makes manually typing what will be the revision to [`30b5a3c` (#3653)](https://github.com/vega/altair/pull/3653/commits/30b5a3c1a06573366bdd14278b76f42a025a5bab) a bit easier to read.
```py
from collections.abc import Sequence, Mapping
from typing_extensions import TypeAlias, LiteralString
from altair.utils import Optional, SchemaBase, Undefined
from altair.vegalite.v5.schema._typing import PrimitiveValue_T, Temporal, SingleDefUnitChannel_T
_AnyValue: TypeAlias = PrimitiveValue_T | …
```
=> feat(typing): Support generating `Union` aliases

altair/utils/schemapi.py, altair/vegalite/v5/api.py, altair/vegalite/v5/schema/_typing.py, altair/vegalite/v5/schema/channels.py, altair/vegalite/v5/schema/core.py, tests/utils/test_schemapi.py, tests/vegalite/v5/test_params.py, tools/generate_schema_wrapper.py, tools/schemapi/schemapi.py, tools/schemapi/utils.py
Closes #3651
This is now a working solution for #3643.
No user conversions, or dependency on `pandas`/`polars` required:
<details><summary>Code block</summary>
<p>
```py
from datetime import date
source = data.sp500.url
brush = alt.selection_interval(
encodings=["x"], value={"x": (date(2005, 1, 1), date(2009, 1, 1))}
)
base = (
alt.Chart(source, width=600, height=200).mark_area().encode(x="date:T", y="price:Q")
)
upper = base.encode(alt.X("date:T").scale(domain=brush))
lower = base.properties(height=60).add_params(brush)
chart = upper & lower
chart
```
</p>
</details> 
<details><summary>Screenshot</summary>
<p>
</p>
</details> 
<details><summary>Schema output</summary>
<p>
```py
{'config': {'view': {'continuousWidth': 300, …
```
=> feat: Support `datetime.(date|datetime)` as a `SchemaBase` parameter

doc/getting_started/installation.rst, doc/user_guide/saving_charts.rst, pyproject.toml
Simple PR! As in title: proposing `altair[save]` optional dependency group to enable saving to static files (without installing `altair[all]`).
Fixes #3608
=> ci: Moved `vl-convert-python` to `save` dependency group

tests/examples_methods_syntax/layered_chart_with_dual_axis.py
Discovered while writing tests for #3659.
The [User Guide](https://altair-viz.github.io/gallery/layered_chart_with_dual_axis.html) displays the attribute syntax, but the method syntax one was not equivalent.
Results in no `titleColor` being applied and is silently ignored during validation.
**Note**: the warning from `pylance` is only showing due to some local changes I have *on-top* of (https://github.com/vega/altair/pull/3659/commits/1a390194352fd5a21631b363cbd1a75dde430beb)
<details><summary>Code block</summary>
<p>
```py
source = data.seattle_weather()
base = alt.Chart(source).encode(alt.X("month(date):T").title(None))
area = base.mark_area(opacity=0.3, color="#57A44C").encode(
alt.Y("average(temp_max)").title("Avg. Temperature …
```
=> docs: Fix "Layered chart with Dual-Axis" (Method syntax)

altair/vegalite/v5/api.py
Resolves https://github.com/vega/altair/pull/3653#issuecomment-2437209166
Primarily addresses `mark: Mark`, which should be `mark: BrushConfig`.
As @mattijn noted, [interactions-parameter-composition](https://altair-viz.github.io/user_guide/interactions.html#parameter-composition) would produce this waring:
```py
Argument of type "BrushConfig" cannot be assigned to parameter "mark" of type "Optional[Mark]" in function "selection_interval"
Type "BrushConfig" is not assignable to type "Optional[Mark]"
"BrushConfig" is not assignable to "Mark"
"BrushConfig" is not assignable to "UndefinedType"
```
I traced this back to:
- https://github.com/vega/altair/blame/374a07f0aa7605b1d5ef96f9bfd32d73723f3ca9/altair/vegalite/v5/api.py#L523
- Introduction of the annotation
- …
=> docs(typing): Fix inaccurate `selection_interval` signature

tests/examples_arguments_syntax/ranged_dot_plot.py, tests/examples_methods_syntax/ranged_dot_plot.py
Addresses https://github.com/vega/altair/issues/3657#issuecomment-2447634487
This PR refactors the [only example](https://altair-viz.github.io/gallery/ranged_dot_plot.html) we currently have that uses `filter` as a keyword argument.
- Replaces `filter` used as a keyword argument 
- Replaces `dict` filters with `FieldOneOfPredicate`
*There are zero functional changes*
=> docs: Update "Ranged Dot Plot" example

altair/utils/core.py, tests/test_transformed_data.py
Since Narwhals 1.9.0 (release last month), `nw.Datetime` has `time_unit` and `time_zone` metadata, which means that `hash(nw.Datetime)` has changed.
This change only affects the main Narwhals namespace - the `narwhals.stable.v1` namespace (which you're using 🙌 ) is unaffected
The fact that having `narwhals.stable.v1` allowed us to make this change without it affecting any users is a pretty good feeling 😄 
I've rewritten the dtype comparison from
```
elif dtype in {nw.Datetime, nw.Date}:
```
to
```
elif dtype == nw.Datetime or dtype == nw.Date:
```
so that it will also work in the same way if and when you decide to move to `narwhals.stable.v2` (when we get there). There'll be no obligation to perform such a move of course, we'll keep `stable.v1` working as-is, so either way, **there's no …
=> chore: use more robust dtype comparisons, use Narwhals stable API in tests

altair/utils/data.py, pyproject.toml, tests/__init__.py, tests/utils/test_to_values_narwhals.py, tests/utils/test_utils.py, tests/vegalite/v5/test_api.py
as discussed in https://github.com/vega/altair/pull/3591#issuecomment-2453480628
=> ci: use duckdb instead of ibis to test interchange-only support

altair/vegalite/v5/api.py, altair/vegalite/v5/schema/core.py, doc/user_guide/transform/filter.rst, tests/vegalite/v5/test_api.py, tools/generate_schema_wrapper.py, tools/schemapi/codegen.py
Resolves #695
This PR enables the use of logical composition operators (`&`, `|`, `~`) directly on all **12** of:
<details><summary><code>...Predicate</code> classes</summary>
<p>
- `core.FieldEqualPredicate`
- `core.FieldGTEPredicate`
- `core.FieldGTPredicate`
- `core.FieldLTEPredicate`
- `core.FieldLTPredicate`
- `core.FieldOneOfPredicate`
- `core.FieldRangePredicate`
- `core.FieldValidPredicate`
- `core.LogicalAndPredicate`
- `core.LogicalOrPredicate`
- `core.LogicalNotPredicate`
- `core.ParameterPredicate`
</p>
</details> 
It appears this functionality has been desired for some time, but never implemented fully.
`api.SelectionPredicateComposition` already contained the code required to get this working - this PR moves that to `core.PredicateComposition`.
The change is fully backwards …
=> feat: Support `&`, `|`, `~` on all `...Predicate` classes

tests/examples_arguments_syntax/interval_selection.py, tests/examples_methods_syntax/interval_selection.py
This is a partial implementation of #3643, demonstrating how to set initial date ranges in interval selections through a concrete example. This improvement was made possible by the recent datetime support added in #3653 and #3662 by @dangotbanned.
Rather than creating a separate example, I opted to modify the existing interval selection example because:
1. Setting initial ranges is a core feature of interval selections, not a separate use case. Including it in the primary example helps users discover this capability alongside basic usage.
2. The change adds minimal complexity while showing the idiomatic way to set initial values using native datetime objects.
3. A single progressive example provides a clearer learning path than splitting this into two separate examples.
Changes made:
- …
=> docs: Add initial date range to interval selection example

tests/utils/test_utils.py
I missed this one during https://github.com/vega/altair/pull/3672#discussion_r1827053789
Already fixed on my other active PRs (https://github.com/vega/altair/pull/3664/commits/a375ab5d9d2831a911016b057f5ab57f61e3ebe7, https://github.com/vega/altair/pull/3618/commits/565f2719f1f6af53abaae6c13c367fba04378789)
Error doesn't get picked up during CI but locally on windows results in the error below:
```py
F                                                                        [100%]
================================== FAILURES ===================================
_____________________ test_sanitize_pyarrow_table_columns _____________________
[gw0] win32 -- Python 3.12.3 C:\Users\danie\AppData\Local\hatch\env\virtual\altair\CXM7NV9I\doc\Scripts\python.exe
@skip_requires_pyarrow
def …
```
=> test: Add missing `@skip_requires_pyarrow(requires_tzdata=True)`

altair/_magics.py, altair/utils/_dfi_types.py, altair/utils/core.py, altair/vegalite/v5/display.py, pyproject.toml, sphinxext/altairgallery.py, sphinxext/code_ref.py, sphinxext/schematable.py, sphinxext/utils.py, tests/__init__.py, tests/test_magics.py, tests/utils/test_compiler.py, tests/utils/test_core.py, tests/utils/test_data.py, tests/utils/test_html.py, tests/utils/test_mimebundle.py, tests/utils/test_plugin_registry.py, tests/utils/test_schemapi.py, tests/utils/test_utils.py, tests/vegalite/v5/test_geo_interface.py
Follow-up to #3585
- Removes *most* of the directory/file-level ignores
- Fixes some simpler warnings
- Adds explicit ignore comments on remaining issues
See individual commit messages for additional context:
- (https://github.com/vega/altair/pull/3676/commits/8ff345695780a7a47c5ef60253186dd5ed6e665d)
- (https://github.com/vega/altair/pull/3676/commits/2ab9dbf75624e66277e89130f39a546a077471d1)
- (https://github.com/vega/altair/pull/3676/commits/ea2e446d0795a7198ea10b7aa342e88f8b7888d2)
- (https://github.com/vega/altair/pull/3676/commits/35cabf0a4765584d17144921091957196a93672a)
- (https://github.com/vega/altair/pull/3676/commits/d8dcbd899eec6e2df0d1edf59056d49eae8270db)
**No user-facing changes**
=> chore(typing): Resolve or ignore `pyright`-only warnings

altair/vegalite/v5/schema/mixins.py, tools/generate_schema_wrapper.py, tools/schemapi/codegen.py
Closes #3262
This PR is a 2-for-1.
1. Primarily #3262
2. But also reduces `mixins.py` from **3500** to **1600 lines**
What I've done here is created a *dummy* version of each class, where the only difference is the omission of `type`.
The *dummy* is used **only** for the signature & docstring.
If we used [`core.MarkDef`](https://altair-viz.github.io/user_guide/generated/core/altair.MarkDef.html#altair.MarkDef) directly, it always displays `type` first.
I'm assuming that wouldn't be desirable - since we set that explicitly in the method body
https://github.com/user-attachments/assets/83d8f08b-9ce5-4856-8a5b-9e52e8a72f20
<details><summary><i>Remains unchanged</i></summary>
<p>
</p>
</details>
=> feat: Generate docstrings for `mark_` methods

pyproject.toml, tests/utils/test_utils.py
Related https://github.com/vega/altair/commit/0bb4210b5aa5ff22c345946a8e73a432373529ff
In #3631 this stub package has been a huge help in understanding `pyarrow`.
Wanted to split out this dev dependency change for visibility.
Also, the 1 minor change to satisfy `mypy` on a test:
```py
tests\utils\test_utils.py:143: error: Argument 1 to "schema" has incompatible type "list[object]"; expected "Iterable[Field[Any]] | Iterable[tuple[str, DataType]] | Mapping[str, DataType]"  [arg-type]
```
=> ci(typing): Add `pyarrow-stubs` to `dev` dependencies

altair/utils/_transformed_data.py, altair/utils/data.py, altair/utils/display.py, altair/utils/mimebundle.py, altair/utils/plugin_registry.py
- https://github.com/vega/altair/pull/3591
- https://github.com/vega/altair/issues/3620
- https://github.com/vega/altair/pull/3593
- https://github.com/vega/altair/issues/3615
This PR moves the remaining `typing_extensions` imports into version-gated blocks.
I'd been doing this over the past month or so in any PRs that I noticed them in, but these are the last ones.
For anyone new to this issue, this aligns with the dependency spec listed in:
https://github.com/vega/altair/blob/1d576a8e3b8b47bdeae92f09d1733a93afd49fbd/pyproject.toml#L14-L18
=> refactor: Replace unconditional `typing_extensions` imports

altair/_magics.py, altair/utils/_vegafusion_data.py, altair/utils/core.py, altair/utils/data.py, altair/vegalite/v5/api.py, pyproject.toml, tests/utils/test_schemapi.py, tests/vegalite/v5/test_api.py, tests/vegalite/v5/test_params.py, tools/generate_schema_wrapper.py
I'm addressing the API mix noted in https://github.com/vega/altair/pull/3690
Also, seeing as `1.13.1` is now the minimum, you can now use `pass_through` instead of `strict` (https://narwhals-dev.github.io/narwhals/backcompat/#after-stablev1)
=> chore: Use `pass_through` instead of `strict` in `narwhals.from_native`, use stable.v1 API more

altair/vegalite/v5/schema/vega-themes.json, tests/vegalite/v5/test_theme.py, tools/generate_schema_wrapper.py
Related to https://github.com/vega/altair/issues/3666#issuecomment-2450057530
We havent started using these yet, but now they can **now** just be copy/pasted and be a valid theme.
The relevant part of my comment in #3666:
> We also have a lot of example themes you can draw from in [vega-themes.json](https://github.com/vega/altair/blob/main/altair/vegalite/v5/schema/vega-themes.json) For these, they would be defined under the `{"config": ...}` key.
> 
> For example, if you liked the `"category"` pallete from `"carbong10"`
> 
> [altair/altair/vegalite/v5/schema/vega-themes.json](https://github.com/vega/altair/blob/211f7c517d7c005af521b242e51e414a084b8350/altair/vegalite/v5/schema/vega-themes.json#L31-L33)
> 
> https://github.com/vega/altair/blob/211f7c517d7c005af521b242e51e414a084b8350/altai …
=> fix: Add missing top-level `"config"` keys in `vega-themes.json`

altair/_magics.py, altair/utils/_vegafusion_data.py, altair/utils/core.py, altair/utils/data.py, pyproject.toml
This PR updates pyproject.toml to update narwhals to v1.14.2.
Note: v1.14.2 is not yet on conda-forge (https://anaconda.org/conda-forge/narwhals/files)
=> chore: bump narwhals to v1.14.2

altair/utils/core.py, altair/utils/mimebundle.py, altair/utils/plugin_registry.py, altair/vegalite/v5/api.py
Related https://github.com/astral-sh/ruff/issues/14676
The release of [ruff 0.8.1](https://github.com/astral-sh/ruff/releases/tag/0.8.1) triggered these auto-fixes.
**Strongly recommend** reading through the `ruff` issue for details
=> refactor(ruff): Apply `TC006` fixes

altair/utils/core.py, altair/utils/mimebundle.py, altair/utils/schemapi.py, pyproject.toml, tests/utils/test_utils.py, tools/schemapi/schemapi.py
Updating my env revealed a range of *minor* issues.
I'm ignoring (`RUF052`[https://docs.astral.sh/ruff/rules/used-dummy-variable/]), which is a new rule I wouldn't have selected.
```cmd
hatch run ruff check --statistics
17     RUF052  [*] used-dummy-variable
2      RUF046  [*] unnecessary-cast-to-int
1      D403    [*] first-word-uncapitalized
1      RUF043  [ ] pytest-raises-ambiguous-pattern
[*] fixable with `ruff check --fix`
```
Not sure where `numpy.bool[builtins.bool]` is coming from, didn't see it in the stubs
```py
altair\utils\core.py:328: error: Incompatible return value type (got "numpy.bool[builtins.bool]", expected "builtins.bool")  [return-value]
return np.issubdtype(dtype, subtype)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error in 1 file (checked 381 source files)
```
=> chore: fix `ruff`, `mypy` warnings

pyproject.toml
The source of these warnings is [typeshed's config](https://github.com/python/typeshed/blob/2cdda12df78275b98a5d3cdc8a92f93d596d9d5d/pyrightconfig.json).
The new ignore pattern prevents the warnings that were ignored upstream from popping up here.
=> ci(typing): Add bundled stubs to `pyright.ignore`

altair/utils/schemapi.py, tests/utils/test_schemapi.py, tools/schemapi/schemapi.py
Closes #2914
This PR adapts the logic from the code generation, for use in `SchemaValidationError` messages.
<details><summary><code>sort_type_reprs</code></summary>
<p>
https://github.com/vega/altair/blob/48e976ef9388ce08a2e871a0f67ed012b914597a/tools/schemapi/utils.py#L1106-L1146
</p>
</details>
<details><summary><code>SchemaInfo.to_type_repr</code></summary>
<p>
https://github.com/vega/altair/blob/48e976ef9388ce08a2e871a0f67ed012b914597a/tools/schemapi/utils.py#L449-L543
</p>
</details> 
```py
>>> alt.Chart(data.barley()).mark_bar().encode(
...     x=alt.X("variety"),
...     y=alt.Y("sum(yield)", stack="null"),  # should be eg. stack=None
... )
SchemaValidationError: 'null' is an invalid value for `stack`. Valid values are:
- One of …
```
=> feat: Show python types in `ValidationError` messages

altair/vegalite/v5/api.py, altair/vegalite/v5/schema/core.py, tools/generate_schema_wrapper.py, tools/schemapi/utils.py
[Liskov substitution principle (LSP)](https://en.wikipedia.org/wiki/Liskov_substitution_principle)
In addition to the changes this allowed in [`api.py`](https://github.com/vega/altair/pull/3740/files#diff-bbe4e187b18d242a366c820d023afd89041759cb96e4ec66c3f34559a72c2f9d); this PR also removes warnings we *currently* get for a few examples using `alt.LookupData`:
<details><summary><code>main</code></summary>
<p>
```py
Argument of type "str" cannot be assigned to parameter "data" of type "Optional[SchemaBase | Map]"
  Type "str" is not assignable to type "Optional[SchemaBase | Map]"
    "str" is not assignable to "SchemaBase"
    "str" is not assignable to "Mapping[str, Any]"
    "str" is not assignable to "UndefinedType"
```
</p>
</details> …
=> fix(typing): Resolve LSP violation for `ChartType.data`

tools/generate_schema_wrapper.py, tools/schemapi/utils.py
Even after #3736, this still produced over 2k warnings in the logs
- https://github.com/vega/altair/actions/runs/12583082774/job/35069916892#step:9:39
- https://github.com/vega/altair/actions/runs/12583082774/job/35069916892#step:9:2811
> error: Failed to create fix for NonPEP585Annotation: Unable to insert `Sequence` into scope due to name conflict
=> chore(ruff): Fix `UP006` warnings during codegen

altair/utils/schemapi.py, tools/schemapi/schemapi.py
Originally part of (https://github.com/vega/altair/pull/3547/commits/af17d441db83cabe7fcd2088eaa2df75bc00acaa)
Follow-up to (https://github.com/vega/altair/pull/3547#issuecomment-2366877433)
=> fix: Replace circular import in `schemapi.py`

altair/utils/schemapi.py, tests/utils/test_schemapi.py, tools/schemapi/schemapi.py
Fixes #2913
```py
>>> alt.Chart().mark_point().encode(x=alt.datum(1, wrong_argument=1))
SchemaValidationError: `XDatum` has no parameter named 'wrong_argument'
Existing parameter names are:
datum          impute   title   
axis           scale    type    
bandPosition   stack            
See the help for `XDatum` to read the full description of these parameters
```
```py
>>> alt.Chart().mark_point().encode(color=alt.value("red", predicate=True))
SchemaValidationError: `ColorValue` has no parameter named 'predicate'
Existing parameter names are:
value   condition   
See the help for `ColorValue` to read the full description of these parameters
```
- #3752
=> fix: Include `*(Datum|Value)` in `SchemaValidationError`

NOTES_FOR_MAINTAINERS.md, RELEASING.md, altair/utils/__init__.py, altair/utils/_importers.py, altair/utils/schemapi.py, pyproject.toml, tools/__init__.py, tools/generate_schema_wrapper.py, tools/versioning.py
This PR seeks to simplify version bumps of projects we depend on within the https://github.com/vega org.
The new process I'm proposing is documented in https://github.com/vega/altair/blob/5aec51ef8eaf345936436abddd903ea87b86b968/NOTES_FOR_MAINTAINERS.md.
In short, we bump versions in `pyproject.toml` and they propagate to everywhere they were **previously manually maintained**:
https://github.com/vega/altair/blob/0c3c22043f7384f0b2f98a06086fc469de6da9ff/pyproject.toml#L103-L107
> [!NOTE]
> Since resolving (https://github.com/vega/altair/pull/3720#discussion_r1900413483), `vl-convert-python` and `vegafusion` versions are sourced **directly** from `[project.optional-dependencies]`.
The new module https://github.com/vega/altair/blob/5aec51ef8eaf345936436abddd903ea87b86b968/tools/versioning.py …
=> refactor: Centralize `Vega` project versioning

pyproject.toml, sphinxext/utils.py
Fixes #3762
This is only a doc dependency, no user-facing changes
- #3095
- #3099
- https://github.com/python-pillow/Pillow/issues/7275#issuecomment-1629754198
Now installs latest version with no issues
https://github.com/vega/altair/actions/runs/12689910049/job/35369638575?pr=3764#step:5:90
```log
+ pillow==11.1.0
```
=> ci: Unpin `pillow`, allow `>=10.0.0`

altair/utils/save.py, altair/utils/schemapi.py, altair/vegalite/v5/api.py, altair/vegalite/v5/display.py, pyproject.toml, sphinxext/code_ref.py, sphinxext/schematable.py, tests/__init__.py, tests/utils/test_plugin_registry.py, tests/utils/test_schemapi.py, tools/generate_schema_wrapper.py, tools/schemapi/schemapi.py, tools/update_init_file.py, tools/vega_expr.py
Resolves #3765
Unblocks https://github.com/vega/altair/pull/3747 ([CI failure](https://github.com/vega/altair/actions/runs/12698005027/job/35395529522))
- (cc9aa8492b05a7e678b3a48eb2d57851a98e2a20) should be enough to pass CI
- Going through the past few releases to 
- Update remapped rule codes (e.g. `TCH` -> `TC`)
- Review what we have selected as preview
- Port over some redundancies I identified in (https://github.com/vega/vega-datasets/pull/647/commits/02286f38f6ecaf657dc5fb0d9a9cbb9d83dafb1b)
- Run the `ruff` tables **only** through `taplo` (https://github.com/vega/altair/pull/3766/commits/92f5947fffcf17f66966fabf577363dfea1d634f)
- https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml
- https://taplo.tamasfe.dev/configuration/formatter-options.html
=> chore(ruff): Update to `0.9.0`

altair/utils/schemapi.py, tests/__init__.py, tests/utils/test_utils.py, tests/vegalite/v5/test_renderers.py, tools/schemapi/schemapi.py
Related:
- https://github.com/vega/altair/actions/runs/12810882256/job/35718940621?pr=3631
- #3766
- https://github.com/astral-sh/ruff/pull/15201#issuecomment-2582567602
=> chore(ruff): Fix `0.9.2` lints

.github/ISSUE_TEMPLATE/bug-report.yml
A simple indicator of whether or not a maintainer has responded yet
Pretty common label used in other projects https://github.com/search?q=label%3Aneeds-triage&type=issues
The two labels have a lot of contrast - so should be easy to spot
=> chore: Add `needs-triage` to new bug reports

tests/__init__.py
Originally added in https://github.com/vega/altair/commit/e1290d4384d4926c24f22a3a23f103e284cfbe1e
Trying to reduce the size of #3631.
This change is atomic and useful enough on its own.
https://github.com/vega/altair/blob/7d6b81de44f63645429976d0a62f43db0dc52221/tests/test_datasets.py#L52-L71
=> test: Make `skip_requires_pyarrow` compatible w/ `pytest.param`

pyproject.toml
Disables the non-blocking warning that appeared since (https://github.com/vega/altair/pull/3747/commits/1d01fa047638d879c0c93c1d8023a8e547824945)
- [Before](https://github.com/vega/altair/actions/runs/12843721674/job/35815966648?pr=3747#step:8:13)
- [After](https://github.com/vega/altair/actions/runs/12844184300/job/35816910571?pr=3775#step:8:13)
> tests\examples_methods_syntax\deviation_ellipses.py:56: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
> tests\examples_arguments_syntax\deviation_ellipses.py:56: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
I don't consider this useful because:
1. The signature annotations were removed …
=> ci(typing): Disable `mypy` `[annotation-unchecked]` on examples

uv.lock
Seems to have been a bug that was resolved in https://github.com/astral-sh/uv/issues/10689
Essentially, each time I've switched branches this change keeps trying to happen.
Shouldn't be an issue following https://github.com/astral-sh/uv/releases/tag/0.5.21
=> ci(uv): Remove dynamic version from `uv.lock`

pyproject.toml, uv.lock
Contains a fix (https://github.com/narwhals-dev/narwhals/pull/1934) for https://github.com/vega/altair/pull/3631#discussion_r1934313255
=> ci: bump `narwhals>=1.25.1`

doc/user_guide/marks/geoshape.rst, tests/examples_arguments_syntax/interval_selection_map_quakes.py, tests/examples_methods_syntax/interval_selection_map_quakes.py
=> docs: Resolve `geopandas.read_file(...)` warnings

pyproject.toml, uv.lock
Will unblock (https://github.com/vega/altair/pull/3631#discussion_r1937953187)
Upstreamed some of #3631 to `narwhals` in https://github.com/narwhals-dev/narwhals/issues/1912
=> ci: bump `narwhals>=1.26.0`

altair/expr/__init__.py, altair/vegalite/v5/api.py, tests/vegalite/v5/test_api.py, tools/vega_expr.py
Fixes broken links that show up e.g. [here](https://altair-viz.github.io/user_guide/generated/api/altair.param.html) after `user_guide/interactions.html` was split into separate pages.
=> docs: fix broken links

altair/utils/schemapi.py, tests/test_transformed_data.py, tools/schemapi/schemapi.py
Spotted during an upstream integration test
- https://github.com/narwhals-dev/narwhals/pull/2110#issuecomment-2687936504
IIRC, I added `strict` before it was [deprecated](https://narwhals-dev.github.io/narwhals/backcompat/#breaking-changes-carried-out-so-far) to help match an `@overload`.
Since then, the `@overload` definitions in `narwhals` have improved - meaning the default **doesn't** need to be passed in for us to get it typing correctly
- #3693
- https://github.com/narwhals-dev/narwhals/pull/2110
=> chore: Remove deprecated `nw.from_native(..., strict=True)`

pyproject.toml
Moving the config here allows for inheriting **user-specific** excludes - which are currently overriden.
I've been having issues with `ruff` wanting to fix my `.venv` and this lets me remove those warnings (without polluting our `pyproject.toml`).
Can always add to our excludes *later* if anyone else encounters the same issue
<details><summary>Screenshot</summary>
<p>
Without local config
</p>
</details> 
```toml
extend-exclude = [
"AppData/**/*.py", ".python", ".venv", "../../../**/Lib"
]
```
- https://docs.astral.sh/ruff/settings/#extend-exclude
- https://docs.astral.sh/ruff/configuration/#config-file-discovery
=> ci(ruff): move `exclude` to `extend-exclude`

altair/expr/core.py, altair/vegalite/v5/__init__.py, tests/expr/test_expr.py
Numpy 2.0 has changed the representation of scalars (e.g., `repr(np.int64(0))` used to be `'0'` but became `np.int64(0)` ([related issue](https://github.com/h5py/h5py/issues/2456)). Due to this change, numpy constants can no longer be used in altair expressions for, e.g., filtering. This is inconvenient, as iterating over a numpy array returns such scalars.
Given that numpy is such a fundamental part of the scientific Python ecosystem, and is often used in conjunction with plotting tasks, I propose that Altair could special-case numpy scalars and unpack them into Python scalars to re-enable the numpy 1.x behavior of numpy constants being usable in altair expressions. This PR implements a simple solution for this.
=> feat: Allow numpy scalars in altair expressions

altair/jupyter/js/index.js, altair/utils/schemapi.py, altair/vegalite/v5/display.py, doc/_static/chart.html, doc/conf.py, doc/user_guide/saving_charts.rst, pyproject.toml, tests/vegalite/v5/test_api.py, tools/versioning.py
Please follow these guidelines:
- bump version of vega embed, as it fixes my issue with tooltips on nbconvert --to slides
- no additonal tests
- Use [semantic commit messages](https://www.conventionalcommits.org/), e.g., `"feat: Add embed_options to charts"`.
- Add `!` for breaking changes (e.g., `"fix!: Raise error when embed_options is None"`).
- **feat**: New feature
- **fix**: Bug fix
- **docs**: Documentation changes
- **style**: Code style changes (no functionality change)
- **refactor**: Code restructuring
- **perf**: Performance improvements
- **test**: Add or fix tests
- **build**: Changes to build system or dependencies
- **ci**: CI configuration changes
- **chore**: Miscellaneous tasks
- **revert**: Reverts a commit
=> chore: Vegaembed bump

tests/examples_arguments_syntax/waterfall_chart.py
Update the waterfall_chart.py colors to have green be positive and red be negative. 
Similar to the vega example ( [waterfall_chart](https://vega.github.io/vega-lite/examples/waterfall_chart.html) )
Below is the updated example
=> docs: Update the waterfall_chart.py colors
